# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.company_data1 import CompanyData1
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server import util

from diag_server.openapi_server.models.company_data1 import CompanyData1  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501

class CompanyRevisionInfoResolved(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, company_data_ref=None, company_data=None, revision_label=None, state=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """CompanyRevisionInfoResolved - a model defined in OpenAPI

        :param company_data_ref: The company_data_ref of this CompanyRevisionInfoResolved.  # noqa: E501
        :type company_data_ref: OdxLinkRef
        :param company_data: The company_data of this CompanyRevisionInfoResolved.  # noqa: E501
        :type company_data: CompanyData1
        :param revision_label: The revision_label of this CompanyRevisionInfoResolved.  # noqa: E501
        :type revision_label: str
        :param state: The state of this CompanyRevisionInfoResolved.  # noqa: E501
        :type state: str
        :param perma_id: The perma_id of this CompanyRevisionInfoResolved.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this CompanyRevisionInfoResolved.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this CompanyRevisionInfoResolved.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'company_data_ref': OdxLinkRef,
            'company_data': CompanyData1,
            'revision_label': str,
            'state': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'company_data_ref': 'company_data_ref',
            'company_data': 'company_data',
            'revision_label': 'revision_label',
            'state': 'state',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._company_data_ref = company_data_ref
        self._company_data = company_data
        self._revision_label = revision_label
        self._state = state
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'CompanyRevisionInfoResolved':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CompanyRevisionInfoResolved of this CompanyRevisionInfoResolved.  # noqa: E501
        :rtype: CompanyRevisionInfoResolved
        """
        return util.deserialize_model(dikt, cls)

    @property
    def company_data_ref(self) -> OdxLinkRef:
        """Gets the company_data_ref of this CompanyRevisionInfoResolved.


        :return: The company_data_ref of this CompanyRevisionInfoResolved.
        :rtype: OdxLinkRef
        """
        return self._company_data_ref

    @company_data_ref.setter
    def company_data_ref(self, company_data_ref: OdxLinkRef):
        """Sets the company_data_ref of this CompanyRevisionInfoResolved.


        :param company_data_ref: The company_data_ref of this CompanyRevisionInfoResolved.
        :type company_data_ref: OdxLinkRef
        """

        self._company_data_ref = company_data_ref

    @property
    def company_data(self) -> CompanyData1:
        """Gets the company_data of this CompanyRevisionInfoResolved.


        :return: The company_data of this CompanyRevisionInfoResolved.
        :rtype: CompanyData1
        """
        return self._company_data

    @company_data.setter
    def company_data(self, company_data: CompanyData1):
        """Sets the company_data of this CompanyRevisionInfoResolved.


        :param company_data: The company_data of this CompanyRevisionInfoResolved.
        :type company_data: CompanyData1
        """

        self._company_data = company_data

    @property
    def revision_label(self) -> str:
        """Gets the revision_label of this CompanyRevisionInfoResolved.


        :return: The revision_label of this CompanyRevisionInfoResolved.
        :rtype: str
        """
        return self._revision_label

    @revision_label.setter
    def revision_label(self, revision_label: str):
        """Sets the revision_label of this CompanyRevisionInfoResolved.


        :param revision_label: The revision_label of this CompanyRevisionInfoResolved.
        :type revision_label: str
        """

        self._revision_label = revision_label

    @property
    def state(self) -> str:
        """Gets the state of this CompanyRevisionInfoResolved.


        :return: The state of this CompanyRevisionInfoResolved.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this CompanyRevisionInfoResolved.


        :param state: The state of this CompanyRevisionInfoResolved.
        :type state: str
        """

        self._state = state

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this CompanyRevisionInfoResolved.


        :return: The perma_id of this CompanyRevisionInfoResolved.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this CompanyRevisionInfoResolved.


        :param perma_id: The perma_id of this CompanyRevisionInfoResolved.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this CompanyRevisionInfoResolved.


        :return: The ephemeral_id of this CompanyRevisionInfoResolved.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this CompanyRevisionInfoResolved.


        :param ephemeral_id: The ephemeral_id of this CompanyRevisionInfoResolved.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this CompanyRevisionInfoResolved.


        :return: The class_name of this CompanyRevisionInfoResolved.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this CompanyRevisionInfoResolved.


        :param class_name: The class_name of this CompanyRevisionInfoResolved.
        :type class_name: str
        """

        self._class_name = class_name
