# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.config_record import ConfigRecord
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server.models.valid_base_variant import ValidBaseVariant
from diag_server.openapi_server import util

from diag_server.openapi_server.models.config_record import ConfigRecord  # noqa: E501
from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501
from diag_server.openapi_server.models.valid_base_variant import ValidBaseVariant  # noqa: E501

class ConfigData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, valid_base_variants=None, config_records=None, sdgs=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """ConfigData - a model defined in OpenAPI

        :param short_name: The short_name of this ConfigData.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this ConfigData.  # noqa: E501
        :type long_name: str
        :param description: The description of this ConfigData.  # noqa: E501
        :type description: Description
        :param valid_base_variants: The valid_base_variants of this ConfigData.  # noqa: E501
        :type valid_base_variants: List[ValidBaseVariant]
        :param config_records: The config_records of this ConfigData.  # noqa: E501
        :type config_records: List[ConfigRecord]
        :param sdgs: The sdgs of this ConfigData.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param perma_id: The perma_id of this ConfigData.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this ConfigData.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this ConfigData.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'valid_base_variants': List[ValidBaseVariant],
            'config_records': List[ConfigRecord],
            'sdgs': List[SpecialDataGroup],
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'valid_base_variants': 'valid_base_variants',
            'config_records': 'config_records',
            'sdgs': 'sdgs',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._valid_base_variants = valid_base_variants
        self._config_records = config_records
        self._sdgs = sdgs
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfigData of this ConfigData.  # noqa: E501
        :rtype: ConfigData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this ConfigData.


        :return: The short_name of this ConfigData.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this ConfigData.


        :param short_name: The short_name of this ConfigData.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this ConfigData.


        :return: The long_name of this ConfigData.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this ConfigData.


        :param long_name: The long_name of this ConfigData.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this ConfigData.


        :return: The description of this ConfigData.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this ConfigData.


        :param description: The description of this ConfigData.
        :type description: Description
        """

        self._description = description

    @property
    def valid_base_variants(self) -> List[ValidBaseVariant]:
        """Gets the valid_base_variants of this ConfigData.


        :return: The valid_base_variants of this ConfigData.
        :rtype: List[ValidBaseVariant]
        """
        return self._valid_base_variants

    @valid_base_variants.setter
    def valid_base_variants(self, valid_base_variants: List[ValidBaseVariant]):
        """Sets the valid_base_variants of this ConfigData.


        :param valid_base_variants: The valid_base_variants of this ConfigData.
        :type valid_base_variants: List[ValidBaseVariant]
        """

        self._valid_base_variants = valid_base_variants

    @property
    def config_records(self) -> List[ConfigRecord]:
        """Gets the config_records of this ConfigData.


        :return: The config_records of this ConfigData.
        :rtype: List[ConfigRecord]
        """
        return self._config_records

    @config_records.setter
    def config_records(self, config_records: List[ConfigRecord]):
        """Sets the config_records of this ConfigData.


        :param config_records: The config_records of this ConfigData.
        :type config_records: List[ConfigRecord]
        """

        self._config_records = config_records

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this ConfigData.


        :return: The sdgs of this ConfigData.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this ConfigData.


        :param sdgs: The sdgs of this ConfigData.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this ConfigData.


        :return: The perma_id of this ConfigData.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this ConfigData.


        :param perma_id: The perma_id of this ConfigData.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this ConfigData.


        :return: The ephemeral_id of this ConfigData.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this ConfigData.


        :param ephemeral_id: The ephemeral_id of this ConfigData.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this ConfigData.


        :return: The class_name of this ConfigData.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this ConfigData.


        :param class_name: The class_name of this ConfigData.
        :type class_name: str
        """

        self._class_name = class_name
