# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.audience import Audience
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.filter import Filter
from diag_server.openapi_server.models.flashdata import Flashdata
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server.models.own_ident import OwnIdent
from diag_server.openapi_server.models.security import Security
from diag_server.openapi_server.models.segment import Segment
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server.models.target_addr_offset import TargetAddrOffset
from diag_server.openapi_server import util

from diag_server.openapi_server.models.audience import Audience  # noqa: E501
from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.filter import Filter  # noqa: E501
from diag_server.openapi_server.models.flashdata import Flashdata  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501
from diag_server.openapi_server.models.own_ident import OwnIdent  # noqa: E501
from diag_server.openapi_server.models.security import Security  # noqa: E501
from diag_server.openapi_server.models.segment import Segment  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501
from diag_server.openapi_server.models.target_addr_offset import TargetAddrOffset  # noqa: E501

class DatablockResolved(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, logical_block_index=None, flashdata_ref=None, flashdata=None, filters=None, segments=None, target_addr_offset=None, own_idents=None, securities=None, sdgs=None, audience=None, data_type=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """DatablockResolved - a model defined in OpenAPI

        :param short_name: The short_name of this DatablockResolved.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this DatablockResolved.  # noqa: E501
        :type long_name: str
        :param description: The description of this DatablockResolved.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this DatablockResolved.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this DatablockResolved.  # noqa: E501
        :type oid: str
        :param logical_block_index: The logical_block_index of this DatablockResolved.  # noqa: E501
        :type logical_block_index: int
        :param flashdata_ref: The flashdata_ref of this DatablockResolved.  # noqa: E501
        :type flashdata_ref: OdxLinkRef
        :param flashdata: The flashdata of this DatablockResolved.  # noqa: E501
        :type flashdata: Flashdata
        :param filters: The filters of this DatablockResolved.  # noqa: E501
        :type filters: List[Filter]
        :param segments: The segments of this DatablockResolved.  # noqa: E501
        :type segments: List[Segment]
        :param target_addr_offset: The target_addr_offset of this DatablockResolved.  # noqa: E501
        :type target_addr_offset: TargetAddrOffset
        :param own_idents: The own_idents of this DatablockResolved.  # noqa: E501
        :type own_idents: List[OwnIdent]
        :param securities: The securities of this DatablockResolved.  # noqa: E501
        :type securities: List[Security]
        :param sdgs: The sdgs of this DatablockResolved.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param audience: The audience of this DatablockResolved.  # noqa: E501
        :type audience: Audience
        :param data_type: The data_type of this DatablockResolved.  # noqa: E501
        :type data_type: str
        :param perma_id: The perma_id of this DatablockResolved.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this DatablockResolved.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this DatablockResolved.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'logical_block_index': int,
            'flashdata_ref': OdxLinkRef,
            'flashdata': Flashdata,
            'filters': List[Filter],
            'segments': List[Segment],
            'target_addr_offset': TargetAddrOffset,
            'own_idents': List[OwnIdent],
            'securities': List[Security],
            'sdgs': List[SpecialDataGroup],
            'audience': Audience,
            'data_type': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'logical_block_index': 'logical_block_index',
            'flashdata_ref': 'flashdata_ref',
            'flashdata': 'flashdata',
            'filters': 'filters',
            'segments': 'segments',
            'target_addr_offset': 'target_addr_offset',
            'own_idents': 'own_idents',
            'securities': 'securities',
            'sdgs': 'sdgs',
            'audience': 'audience',
            'data_type': 'data_type',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._logical_block_index = logical_block_index
        self._flashdata_ref = flashdata_ref
        self._flashdata = flashdata
        self._filters = filters
        self._segments = segments
        self._target_addr_offset = target_addr_offset
        self._own_idents = own_idents
        self._securities = securities
        self._sdgs = sdgs
        self._audience = audience
        self._data_type = data_type
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'DatablockResolved':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DatablockResolved of this DatablockResolved.  # noqa: E501
        :rtype: DatablockResolved
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this DatablockResolved.


        :return: The short_name of this DatablockResolved.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this DatablockResolved.


        :param short_name: The short_name of this DatablockResolved.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this DatablockResolved.


        :return: The long_name of this DatablockResolved.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this DatablockResolved.


        :param long_name: The long_name of this DatablockResolved.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this DatablockResolved.


        :return: The description of this DatablockResolved.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this DatablockResolved.


        :param description: The description of this DatablockResolved.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this DatablockResolved.


        :return: The odx_id of this DatablockResolved.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this DatablockResolved.


        :param odx_id: The odx_id of this DatablockResolved.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this DatablockResolved.


        :return: The oid of this DatablockResolved.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this DatablockResolved.


        :param oid: The oid of this DatablockResolved.
        :type oid: str
        """

        self._oid = oid

    @property
    def logical_block_index(self) -> int:
        """Gets the logical_block_index of this DatablockResolved.


        :return: The logical_block_index of this DatablockResolved.
        :rtype: int
        """
        return self._logical_block_index

    @logical_block_index.setter
    def logical_block_index(self, logical_block_index: int):
        """Sets the logical_block_index of this DatablockResolved.


        :param logical_block_index: The logical_block_index of this DatablockResolved.
        :type logical_block_index: int
        """

        self._logical_block_index = logical_block_index

    @property
    def flashdata_ref(self) -> OdxLinkRef:
        """Gets the flashdata_ref of this DatablockResolved.


        :return: The flashdata_ref of this DatablockResolved.
        :rtype: OdxLinkRef
        """
        return self._flashdata_ref

    @flashdata_ref.setter
    def flashdata_ref(self, flashdata_ref: OdxLinkRef):
        """Sets the flashdata_ref of this DatablockResolved.


        :param flashdata_ref: The flashdata_ref of this DatablockResolved.
        :type flashdata_ref: OdxLinkRef
        """

        self._flashdata_ref = flashdata_ref

    @property
    def flashdata(self) -> Flashdata:
        """Gets the flashdata of this DatablockResolved.


        :return: The flashdata of this DatablockResolved.
        :rtype: Flashdata
        """
        return self._flashdata

    @flashdata.setter
    def flashdata(self, flashdata: Flashdata):
        """Sets the flashdata of this DatablockResolved.


        :param flashdata: The flashdata of this DatablockResolved.
        :type flashdata: Flashdata
        """

        self._flashdata = flashdata

    @property
    def filters(self) -> List[Filter]:
        """Gets the filters of this DatablockResolved.


        :return: The filters of this DatablockResolved.
        :rtype: List[Filter]
        """
        return self._filters

    @filters.setter
    def filters(self, filters: List[Filter]):
        """Sets the filters of this DatablockResolved.


        :param filters: The filters of this DatablockResolved.
        :type filters: List[Filter]
        """

        self._filters = filters

    @property
    def segments(self) -> List[Segment]:
        """Gets the segments of this DatablockResolved.


        :return: The segments of this DatablockResolved.
        :rtype: List[Segment]
        """
        return self._segments

    @segments.setter
    def segments(self, segments: List[Segment]):
        """Sets the segments of this DatablockResolved.


        :param segments: The segments of this DatablockResolved.
        :type segments: List[Segment]
        """

        self._segments = segments

    @property
    def target_addr_offset(self) -> TargetAddrOffset:
        """Gets the target_addr_offset of this DatablockResolved.


        :return: The target_addr_offset of this DatablockResolved.
        :rtype: TargetAddrOffset
        """
        return self._target_addr_offset

    @target_addr_offset.setter
    def target_addr_offset(self, target_addr_offset: TargetAddrOffset):
        """Sets the target_addr_offset of this DatablockResolved.


        :param target_addr_offset: The target_addr_offset of this DatablockResolved.
        :type target_addr_offset: TargetAddrOffset
        """

        self._target_addr_offset = target_addr_offset

    @property
    def own_idents(self) -> List[OwnIdent]:
        """Gets the own_idents of this DatablockResolved.


        :return: The own_idents of this DatablockResolved.
        :rtype: List[OwnIdent]
        """
        return self._own_idents

    @own_idents.setter
    def own_idents(self, own_idents: List[OwnIdent]):
        """Sets the own_idents of this DatablockResolved.


        :param own_idents: The own_idents of this DatablockResolved.
        :type own_idents: List[OwnIdent]
        """

        self._own_idents = own_idents

    @property
    def securities(self) -> List[Security]:
        """Gets the securities of this DatablockResolved.


        :return: The securities of this DatablockResolved.
        :rtype: List[Security]
        """
        return self._securities

    @securities.setter
    def securities(self, securities: List[Security]):
        """Sets the securities of this DatablockResolved.


        :param securities: The securities of this DatablockResolved.
        :type securities: List[Security]
        """

        self._securities = securities

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this DatablockResolved.


        :return: The sdgs of this DatablockResolved.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this DatablockResolved.


        :param sdgs: The sdgs of this DatablockResolved.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def audience(self) -> Audience:
        """Gets the audience of this DatablockResolved.


        :return: The audience of this DatablockResolved.
        :rtype: Audience
        """
        return self._audience

    @audience.setter
    def audience(self, audience: Audience):
        """Sets the audience of this DatablockResolved.


        :param audience: The audience of this DatablockResolved.
        :type audience: Audience
        """

        self._audience = audience

    @property
    def data_type(self) -> str:
        """Gets the data_type of this DatablockResolved.


        :return: The data_type of this DatablockResolved.
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type: str):
        """Sets the data_type of this DatablockResolved.


        :param data_type: The data_type of this DatablockResolved.
        :type data_type: str
        """

        self._data_type = data_type

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this DatablockResolved.


        :return: The perma_id of this DatablockResolved.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this DatablockResolved.


        :param perma_id: The perma_id of this DatablockResolved.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this DatablockResolved.


        :return: The ephemeral_id of this DatablockResolved.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this DatablockResolved.


        :param ephemeral_id: The ephemeral_id of this DatablockResolved.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this DatablockResolved.


        :return: The class_name of this DatablockResolved.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this DatablockResolved.


        :param class_name: The class_name of this DatablockResolved.
        :type class_name: str
        """

        self._class_name = class_name
