# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server import util


class DiagClassType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    STARTCOMM = 'STARTCOMM'
    STOPCOMM = 'STOPCOMM'
    VARIANTIDENTIFICATION = 'VARIANTIDENTIFICATION'
    READ_MINUS_DYN_MINUS_DEFINED_MINUS_MESSAGE = 'READ-DYN-DEFINED-MESSAGE'
    DYN_MINUS_DEF_MINUS_MESSAGE = 'DYN-DEF-MESSAGE'
    CLEAR_MINUS_DYN_MINUS_DEF_MINUS_MESSAGE = 'CLEAR-DYN-DEF-MESSAGE'
    def __init__(self):  # noqa: E501
        """DiagClassType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DiagClassType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiagClassType of this DiagClassType.  # noqa: E501
        :rtype: DiagClassType
        """
        return util.deserialize_model(dikt, cls)
