# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.diagnostic_data_set_descriptor import DiagnosticDataSetDescriptor
from diag_server.openapi_server import util

from diag_server.openapi_server.models.diagnostic_data_set_descriptor import DiagnosticDataSetDescriptor  # noqa: E501

class DiagnosticDataCollection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """DiagnosticDataCollection - a model defined in OpenAPI

        :param items: The items of this DiagnosticDataCollection.  # noqa: E501
        :type items: List[DiagnosticDataSetDescriptor]
        """
        self.openapi_types = {
            'items': List[DiagnosticDataSetDescriptor]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'DiagnosticDataCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiagnosticDataCollection of this DiagnosticDataCollection.  # noqa: E501
        :rtype: DiagnosticDataCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[DiagnosticDataSetDescriptor]:
        """Gets the items of this DiagnosticDataCollection.


        :return: The items of this DiagnosticDataCollection.
        :rtype: List[DiagnosticDataSetDescriptor]
        """
        return self._items

    @items.setter
    def items(self, items: List[DiagnosticDataSetDescriptor]):
        """Sets the items of this DiagnosticDataCollection.


        :param items: The items of this DiagnosticDataCollection.
        :type items: List[DiagnosticDataSetDescriptor]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
