# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.dtc_connector import DtcConnector
from diag_server.openapi_server.models.env_data_connector import EnvDataConnector
from diag_server.openapi_server.models.function_diag_comm_connector import FunctionDiagCommConnector
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.table_row_connector import TableRowConnector
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.dtc_connector import DtcConnector  # noqa: E501
from diag_server.openapi_server.models.env_data_connector import EnvDataConnector  # noqa: E501
from diag_server.openapi_server.models.function_diag_comm_connector import FunctionDiagCommConnector  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.table_row_connector import TableRowConnector  # noqa: E501

class DiagObjectConnector(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, function_diag_comm_connectors=None, table_row_connectors=None, env_data_connectors=None, dtc_connectors=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """DiagObjectConnector - a model defined in OpenAPI

        :param short_name: The short_name of this DiagObjectConnector.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this DiagObjectConnector.  # noqa: E501
        :type long_name: str
        :param description: The description of this DiagObjectConnector.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this DiagObjectConnector.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this DiagObjectConnector.  # noqa: E501
        :type oid: str
        :param function_diag_comm_connectors: The function_diag_comm_connectors of this DiagObjectConnector.  # noqa: E501
        :type function_diag_comm_connectors: List[FunctionDiagCommConnector]
        :param table_row_connectors: The table_row_connectors of this DiagObjectConnector.  # noqa: E501
        :type table_row_connectors: List[TableRowConnector]
        :param env_data_connectors: The env_data_connectors of this DiagObjectConnector.  # noqa: E501
        :type env_data_connectors: List[EnvDataConnector]
        :param dtc_connectors: The dtc_connectors of this DiagObjectConnector.  # noqa: E501
        :type dtc_connectors: List[DtcConnector]
        :param perma_id: The perma_id of this DiagObjectConnector.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this DiagObjectConnector.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this DiagObjectConnector.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'function_diag_comm_connectors': List[FunctionDiagCommConnector],
            'table_row_connectors': List[TableRowConnector],
            'env_data_connectors': List[EnvDataConnector],
            'dtc_connectors': List[DtcConnector],
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'function_diag_comm_connectors': 'function_diag_comm_connectors',
            'table_row_connectors': 'table_row_connectors',
            'env_data_connectors': 'env_data_connectors',
            'dtc_connectors': 'dtc_connectors',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._function_diag_comm_connectors = function_diag_comm_connectors
        self._table_row_connectors = table_row_connectors
        self._env_data_connectors = env_data_connectors
        self._dtc_connectors = dtc_connectors
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'DiagObjectConnector':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiagObjectConnector of this DiagObjectConnector.  # noqa: E501
        :rtype: DiagObjectConnector
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this DiagObjectConnector.


        :return: The short_name of this DiagObjectConnector.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this DiagObjectConnector.


        :param short_name: The short_name of this DiagObjectConnector.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this DiagObjectConnector.


        :return: The long_name of this DiagObjectConnector.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this DiagObjectConnector.


        :param long_name: The long_name of this DiagObjectConnector.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this DiagObjectConnector.


        :return: The description of this DiagObjectConnector.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this DiagObjectConnector.


        :param description: The description of this DiagObjectConnector.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this DiagObjectConnector.


        :return: The odx_id of this DiagObjectConnector.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this DiagObjectConnector.


        :param odx_id: The odx_id of this DiagObjectConnector.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this DiagObjectConnector.


        :return: The oid of this DiagObjectConnector.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this DiagObjectConnector.


        :param oid: The oid of this DiagObjectConnector.
        :type oid: str
        """

        self._oid = oid

    @property
    def function_diag_comm_connectors(self) -> List[FunctionDiagCommConnector]:
        """Gets the function_diag_comm_connectors of this DiagObjectConnector.


        :return: The function_diag_comm_connectors of this DiagObjectConnector.
        :rtype: List[FunctionDiagCommConnector]
        """
        return self._function_diag_comm_connectors

    @function_diag_comm_connectors.setter
    def function_diag_comm_connectors(self, function_diag_comm_connectors: List[FunctionDiagCommConnector]):
        """Sets the function_diag_comm_connectors of this DiagObjectConnector.


        :param function_diag_comm_connectors: The function_diag_comm_connectors of this DiagObjectConnector.
        :type function_diag_comm_connectors: List[FunctionDiagCommConnector]
        """

        self._function_diag_comm_connectors = function_diag_comm_connectors

    @property
    def table_row_connectors(self) -> List[TableRowConnector]:
        """Gets the table_row_connectors of this DiagObjectConnector.


        :return: The table_row_connectors of this DiagObjectConnector.
        :rtype: List[TableRowConnector]
        """
        return self._table_row_connectors

    @table_row_connectors.setter
    def table_row_connectors(self, table_row_connectors: List[TableRowConnector]):
        """Sets the table_row_connectors of this DiagObjectConnector.


        :param table_row_connectors: The table_row_connectors of this DiagObjectConnector.
        :type table_row_connectors: List[TableRowConnector]
        """

        self._table_row_connectors = table_row_connectors

    @property
    def env_data_connectors(self) -> List[EnvDataConnector]:
        """Gets the env_data_connectors of this DiagObjectConnector.


        :return: The env_data_connectors of this DiagObjectConnector.
        :rtype: List[EnvDataConnector]
        """
        return self._env_data_connectors

    @env_data_connectors.setter
    def env_data_connectors(self, env_data_connectors: List[EnvDataConnector]):
        """Sets the env_data_connectors of this DiagObjectConnector.


        :param env_data_connectors: The env_data_connectors of this DiagObjectConnector.
        :type env_data_connectors: List[EnvDataConnector]
        """

        self._env_data_connectors = env_data_connectors

    @property
    def dtc_connectors(self) -> List[DtcConnector]:
        """Gets the dtc_connectors of this DiagObjectConnector.


        :return: The dtc_connectors of this DiagObjectConnector.
        :rtype: List[DtcConnector]
        """
        return self._dtc_connectors

    @dtc_connectors.setter
    def dtc_connectors(self, dtc_connectors: List[DtcConnector]):
        """Sets the dtc_connectors of this DiagObjectConnector.


        :param dtc_connectors: The dtc_connectors of this DiagObjectConnector.
        :type dtc_connectors: List[DtcConnector]
        """

        self._dtc_connectors = dtc_connectors

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this DiagObjectConnector.


        :return: The perma_id of this DiagObjectConnector.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this DiagObjectConnector.


        :param perma_id: The perma_id of this DiagObjectConnector.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this DiagObjectConnector.


        :return: The ephemeral_id of this DiagObjectConnector.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this DiagObjectConnector.


        :param ephemeral_id: The ephemeral_id of this DiagObjectConnector.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this DiagObjectConnector.


        :return: The class_name of this DiagObjectConnector.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this DiagObjectConnector.


        :param class_name: The class_name of this DiagObjectConnector.
        :type class_name: str
        """

        self._class_name = class_name
