# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.diag_comm_with_data_sets_variant_refs import DiagCommWithDataSetsVariantRefs
from diag_server.openapi_server.models.diagnostic_data_set_descriptor import DiagnosticDataSetDescriptor
from diag_server.openapi_server.models.diagnostic_variant import DiagnosticVariant
from diag_server.openapi_server import util

from diag_server.openapi_server.models.diag_comm_with_data_sets_variant_refs import DiagCommWithDataSetsVariantRefs  # noqa: E501
from diag_server.openapi_server.models.diagnostic_data_set_descriptor import DiagnosticDataSetDescriptor  # noqa: E501
from diag_server.openapi_server.models.diagnostic_variant import DiagnosticVariant  # noqa: E501

class DiagCommsOfVariantsOfDataSetsCollection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, diagnostic_data_sets=None, variants=None, diag_comms=None):  # noqa: E501
        """DiagCommsOfVariantsOfDataSetsCollection - a model defined in OpenAPI

        :param diagnostic_data_sets: The diagnostic_data_sets of this DiagCommsOfVariantsOfDataSetsCollection.  # noqa: E501
        :type diagnostic_data_sets: List[DiagnosticDataSetDescriptor]
        :param variants: The variants of this DiagCommsOfVariantsOfDataSetsCollection.  # noqa: E501
        :type variants: List[DiagnosticVariant]
        :param diag_comms: The diag_comms of this DiagCommsOfVariantsOfDataSetsCollection.  # noqa: E501
        :type diag_comms: List[DiagCommWithDataSetsVariantRefs]
        """
        self.openapi_types = {
            'diagnostic_data_sets': List[DiagnosticDataSetDescriptor],
            'variants': List[DiagnosticVariant],
            'diag_comms': List[DiagCommWithDataSetsVariantRefs]
        }

        self.attribute_map = {
            'diagnostic_data_sets': 'diagnostic_data_sets',
            'variants': 'variants',
            'diag_comms': 'diag_comms'
        }

        self._diagnostic_data_sets = diagnostic_data_sets
        self._variants = variants
        self._diag_comms = diag_comms

    @classmethod
    def from_dict(cls, dikt) -> 'DiagCommsOfVariantsOfDataSetsCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiagCommsOfVariantsOfDataSetsCollection of this DiagCommsOfVariantsOfDataSetsCollection.  # noqa: E501
        :rtype: DiagCommsOfVariantsOfDataSetsCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def diagnostic_data_sets(self) -> List[DiagnosticDataSetDescriptor]:
        """Gets the diagnostic_data_sets of this DiagCommsOfVariantsOfDataSetsCollection.


        :return: The diagnostic_data_sets of this DiagCommsOfVariantsOfDataSetsCollection.
        :rtype: List[DiagnosticDataSetDescriptor]
        """
        return self._diagnostic_data_sets

    @diagnostic_data_sets.setter
    def diagnostic_data_sets(self, diagnostic_data_sets: List[DiagnosticDataSetDescriptor]):
        """Sets the diagnostic_data_sets of this DiagCommsOfVariantsOfDataSetsCollection.


        :param diagnostic_data_sets: The diagnostic_data_sets of this DiagCommsOfVariantsOfDataSetsCollection.
        :type diagnostic_data_sets: List[DiagnosticDataSetDescriptor]
        """

        self._diagnostic_data_sets = diagnostic_data_sets

    @property
    def variants(self) -> List[DiagnosticVariant]:
        """Gets the variants of this DiagCommsOfVariantsOfDataSetsCollection.


        :return: The variants of this DiagCommsOfVariantsOfDataSetsCollection.
        :rtype: List[DiagnosticVariant]
        """
        return self._variants

    @variants.setter
    def variants(self, variants: List[DiagnosticVariant]):
        """Sets the variants of this DiagCommsOfVariantsOfDataSetsCollection.


        :param variants: The variants of this DiagCommsOfVariantsOfDataSetsCollection.
        :type variants: List[DiagnosticVariant]
        """

        self._variants = variants

    @property
    def diag_comms(self) -> List[DiagCommWithDataSetsVariantRefs]:
        """Gets the diag_comms of this DiagCommsOfVariantsOfDataSetsCollection.


        :return: The diag_comms of this DiagCommsOfVariantsOfDataSetsCollection.
        :rtype: List[DiagCommWithDataSetsVariantRefs]
        """
        return self._diag_comms

    @diag_comms.setter
    def diag_comms(self, diag_comms: List[DiagCommWithDataSetsVariantRefs]):
        """Sets the diag_comms of this DiagCommsOfVariantsOfDataSetsCollection.


        :param diag_comms: The diag_comms of this DiagCommsOfVariantsOfDataSetsCollection.
        :type diag_comms: List[DiagCommWithDataSetsVariantRefs]
        """

        self._diag_comms = diag_comms
