# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.diagnostic_layer_container_info import DiagnosticLayerContainerInfo
from diag_server.openapi_server import util

from diag_server.openapi_server.models.diagnostic_layer_container_info import DiagnosticLayerContainerInfo  # noqa: E501

class DiagnosticDataSetDescriptor(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, perma_id=None, ephemeral_id=None, display_name=None, file_name=None, creation_date=None, last_modified=None, version=None, diagnostic_layer_containers=None):  # noqa: E501
        """DiagnosticDataSetDescriptor - a model defined in OpenAPI

        :param perma_id: The perma_id of this DiagnosticDataSetDescriptor.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this DiagnosticDataSetDescriptor.  # noqa: E501
        :type ephemeral_id: int
        :param display_name: The display_name of this DiagnosticDataSetDescriptor.  # noqa: E501
        :type display_name: str
        :param file_name: The file_name of this DiagnosticDataSetDescriptor.  # noqa: E501
        :type file_name: str
        :param creation_date: The creation_date of this DiagnosticDataSetDescriptor.  # noqa: E501
        :type creation_date: datetime
        :param last_modified: The last_modified of this DiagnosticDataSetDescriptor.  # noqa: E501
        :type last_modified: datetime
        :param version: The version of this DiagnosticDataSetDescriptor.  # noqa: E501
        :type version: str
        :param diagnostic_layer_containers: The diagnostic_layer_containers of this DiagnosticDataSetDescriptor.  # noqa: E501
        :type diagnostic_layer_containers: List[DiagnosticLayerContainerInfo]
        """
        self.openapi_types = {
            'perma_id': str,
            'ephemeral_id': int,
            'display_name': str,
            'file_name': str,
            'creation_date': datetime,
            'last_modified': datetime,
            'version': str,
            'diagnostic_layer_containers': List[DiagnosticLayerContainerInfo]
        }

        self.attribute_map = {
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'display_name': 'display_name',
            'file_name': 'file_name',
            'creation_date': 'creation_date',
            'last_modified': 'last_modified',
            'version': 'version',
            'diagnostic_layer_containers': 'diagnostic_layer_containers'
        }

        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._display_name = display_name
        self._file_name = file_name
        self._creation_date = creation_date
        self._last_modified = last_modified
        self._version = version
        self._diagnostic_layer_containers = diagnostic_layer_containers

    @classmethod
    def from_dict(cls, dikt) -> 'DiagnosticDataSetDescriptor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiagnosticDataSetDescriptor of this DiagnosticDataSetDescriptor.  # noqa: E501
        :rtype: DiagnosticDataSetDescriptor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this DiagnosticDataSetDescriptor.


        :return: The perma_id of this DiagnosticDataSetDescriptor.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this DiagnosticDataSetDescriptor.


        :param perma_id: The perma_id of this DiagnosticDataSetDescriptor.
        :type perma_id: str
        """
        if perma_id is None:
            raise ValueError("Invalid value for `perma_id`, must not be `None`")  # noqa: E501

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this DiagnosticDataSetDescriptor.


        :return: The ephemeral_id of this DiagnosticDataSetDescriptor.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this DiagnosticDataSetDescriptor.


        :param ephemeral_id: The ephemeral_id of this DiagnosticDataSetDescriptor.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def display_name(self) -> str:
        """Gets the display_name of this DiagnosticDataSetDescriptor.


        :return: The display_name of this DiagnosticDataSetDescriptor.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this DiagnosticDataSetDescriptor.


        :param display_name: The display_name of this DiagnosticDataSetDescriptor.
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def file_name(self) -> str:
        """Gets the file_name of this DiagnosticDataSetDescriptor.


        :return: The file_name of this DiagnosticDataSetDescriptor.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name: str):
        """Sets the file_name of this DiagnosticDataSetDescriptor.


        :param file_name: The file_name of this DiagnosticDataSetDescriptor.
        :type file_name: str
        """

        self._file_name = file_name

    @property
    def creation_date(self) -> datetime:
        """Gets the creation_date of this DiagnosticDataSetDescriptor.


        :return: The creation_date of this DiagnosticDataSetDescriptor.
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: datetime):
        """Sets the creation_date of this DiagnosticDataSetDescriptor.


        :param creation_date: The creation_date of this DiagnosticDataSetDescriptor.
        :type creation_date: datetime
        """

        self._creation_date = creation_date

    @property
    def last_modified(self) -> datetime:
        """Gets the last_modified of this DiagnosticDataSetDescriptor.


        :return: The last_modified of this DiagnosticDataSetDescriptor.
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified: datetime):
        """Sets the last_modified of this DiagnosticDataSetDescriptor.


        :param last_modified: The last_modified of this DiagnosticDataSetDescriptor.
        :type last_modified: datetime
        """

        self._last_modified = last_modified

    @property
    def version(self) -> str:
        """Gets the version of this DiagnosticDataSetDescriptor.


        :return: The version of this DiagnosticDataSetDescriptor.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this DiagnosticDataSetDescriptor.


        :param version: The version of this DiagnosticDataSetDescriptor.
        :type version: str
        """

        self._version = version

    @property
    def diagnostic_layer_containers(self) -> List[DiagnosticLayerContainerInfo]:
        """Gets the diagnostic_layer_containers of this DiagnosticDataSetDescriptor.


        :return: The diagnostic_layer_containers of this DiagnosticDataSetDescriptor.
        :rtype: List[DiagnosticLayerContainerInfo]
        """
        return self._diagnostic_layer_containers

    @diagnostic_layer_containers.setter
    def diagnostic_layer_containers(self, diagnostic_layer_containers: List[DiagnosticLayerContainerInfo]):
        """Sets the diagnostic_layer_containers of this DiagnosticDataSetDescriptor.


        :param diagnostic_layer_containers: The diagnostic_layer_containers of this DiagnosticDataSetDescriptor.
        :type diagnostic_layer_containers: List[DiagnosticLayerContainerInfo]
        """

        self._diagnostic_layer_containers = diagnostic_layer_containers
