# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server import util


class DocType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    FLASH = 'FLASH'
    CONTAINER = 'CONTAINER'
    LAYER = 'LAYER'
    MULTIPLE_MINUS_ECU_MINUS_JOB_MINUS_SPEC = 'MULTIPLE-ECU-JOB-SPEC'
    COMPARAM_MINUS_SPEC = 'COMPARAM-SPEC'
    VEHICLE_MINUS_INFO_MINUS_SPEC = 'VEHICLE-INFO-SPEC'
    COMPARAM_MINUS_SUBSET = 'COMPARAM-SUBSET'
    ECU_MINUS_CONFIG = 'ECU-CONFIG'
    FUNCTION_MINUS_DICTIONARY_MINUS_SPEC = 'FUNCTION-DICTIONARY-SPEC'
    def __init__(self):  # noqa: E501
        """DocType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DocType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocType of this DocType.  # noqa: E501
        :rtype: DocType
        """
        return util.deserialize_model(dikt, cls)
