# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.dop_base import DopBase
from diag_server.openapi_server import util

from diag_server.openapi_server.models.dop_base import DopBase  # noqa: E501

class DopWithOriginLayerInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dop=None, origin_layer_perma_id=None, origin_layer_ephemeral_id=None, origin_layer_short_name=None, origin_layer_type=None):  # noqa: E501
        """DopWithOriginLayerInfo - a model defined in OpenAPI

        :param dop: The dop of this DopWithOriginLayerInfo.  # noqa: E501
        :type dop: DopBase
        :param origin_layer_perma_id: The origin_layer_perma_id of this DopWithOriginLayerInfo.  # noqa: E501
        :type origin_layer_perma_id: str
        :param origin_layer_ephemeral_id: The origin_layer_ephemeral_id of this DopWithOriginLayerInfo.  # noqa: E501
        :type origin_layer_ephemeral_id: int
        :param origin_layer_short_name: The origin_layer_short_name of this DopWithOriginLayerInfo.  # noqa: E501
        :type origin_layer_short_name: str
        :param origin_layer_type: The origin_layer_type of this DopWithOriginLayerInfo.  # noqa: E501
        :type origin_layer_type: str
        """
        self.openapi_types = {
            'dop': DopBase,
            'origin_layer_perma_id': str,
            'origin_layer_ephemeral_id': int,
            'origin_layer_short_name': str,
            'origin_layer_type': str
        }

        self.attribute_map = {
            'dop': 'dop',
            'origin_layer_perma_id': 'origin_layer_perma_id',
            'origin_layer_ephemeral_id': 'origin_layer_ephemeral_id',
            'origin_layer_short_name': 'origin_layer_short_name',
            'origin_layer_type': 'origin_layer_type'
        }

        self._dop = dop
        self._origin_layer_perma_id = origin_layer_perma_id
        self._origin_layer_ephemeral_id = origin_layer_ephemeral_id
        self._origin_layer_short_name = origin_layer_short_name
        self._origin_layer_type = origin_layer_type

    @classmethod
    def from_dict(cls, dikt) -> 'DopWithOriginLayerInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DopWithOriginLayerInfo of this DopWithOriginLayerInfo.  # noqa: E501
        :rtype: DopWithOriginLayerInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dop(self) -> DopBase:
        """Gets the dop of this DopWithOriginLayerInfo.


        :return: The dop of this DopWithOriginLayerInfo.
        :rtype: DopBase
        """
        return self._dop

    @dop.setter
    def dop(self, dop: DopBase):
        """Sets the dop of this DopWithOriginLayerInfo.


        :param dop: The dop of this DopWithOriginLayerInfo.
        :type dop: DopBase
        """

        self._dop = dop

    @property
    def origin_layer_perma_id(self) -> str:
        """Gets the origin_layer_perma_id of this DopWithOriginLayerInfo.


        :return: The origin_layer_perma_id of this DopWithOriginLayerInfo.
        :rtype: str
        """
        return self._origin_layer_perma_id

    @origin_layer_perma_id.setter
    def origin_layer_perma_id(self, origin_layer_perma_id: str):
        """Sets the origin_layer_perma_id of this DopWithOriginLayerInfo.


        :param origin_layer_perma_id: The origin_layer_perma_id of this DopWithOriginLayerInfo.
        :type origin_layer_perma_id: str
        """

        self._origin_layer_perma_id = origin_layer_perma_id

    @property
    def origin_layer_ephemeral_id(self) -> int:
        """Gets the origin_layer_ephemeral_id of this DopWithOriginLayerInfo.


        :return: The origin_layer_ephemeral_id of this DopWithOriginLayerInfo.
        :rtype: int
        """
        return self._origin_layer_ephemeral_id

    @origin_layer_ephemeral_id.setter
    def origin_layer_ephemeral_id(self, origin_layer_ephemeral_id: int):
        """Sets the origin_layer_ephemeral_id of this DopWithOriginLayerInfo.


        :param origin_layer_ephemeral_id: The origin_layer_ephemeral_id of this DopWithOriginLayerInfo.
        :type origin_layer_ephemeral_id: int
        """

        self._origin_layer_ephemeral_id = origin_layer_ephemeral_id

    @property
    def origin_layer_short_name(self) -> str:
        """Gets the origin_layer_short_name of this DopWithOriginLayerInfo.


        :return: The origin_layer_short_name of this DopWithOriginLayerInfo.
        :rtype: str
        """
        return self._origin_layer_short_name

    @origin_layer_short_name.setter
    def origin_layer_short_name(self, origin_layer_short_name: str):
        """Sets the origin_layer_short_name of this DopWithOriginLayerInfo.


        :param origin_layer_short_name: The origin_layer_short_name of this DopWithOriginLayerInfo.
        :type origin_layer_short_name: str
        """

        self._origin_layer_short_name = origin_layer_short_name

    @property
    def origin_layer_type(self) -> str:
        """Gets the origin_layer_type of this DopWithOriginLayerInfo.


        :return: The origin_layer_type of this DopWithOriginLayerInfo.
        :rtype: str
        """
        return self._origin_layer_type

    @origin_layer_type.setter
    def origin_layer_type(self, origin_layer_type: str):
        """Sets the origin_layer_type of this DopWithOriginLayerInfo.


        :param origin_layer_type: The origin_layer_type of this DopWithOriginLayerInfo.
        :type origin_layer_type: str
        """

        self._origin_layer_type = origin_layer_type
