# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.diagnostic_trouble_code import DiagnosticTroubleCode
from diag_server.openapi_server.models.odx_doc_fragment import OdxDocFragment
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server.models.text import Text
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.diagnostic_trouble_code import DiagnosticTroubleCode  # noqa: E501
from diag_server.openapi_server.models.odx_doc_fragment import OdxDocFragment  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501
from diag_server.openapi_server.models.text import Text  # noqa: E501

class DtcDopDtcsRawInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, trouble_code=None, display_trouble_code=None, text=None, level=None, sdgs=None, is_temporary_raw=None, is_temporary=None, perma_id=None, ephemeral_id=None, class_name=None, ref_id=None, ref_docs=None, resolved_object_perma_id=None, resolved_object_ephemeral_id=None, resolved_object_short_name=None):  # noqa: E501
        """DtcDopDtcsRawInner - a model defined in OpenAPI

        :param short_name: The short_name of this DtcDopDtcsRawInner.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this DtcDopDtcsRawInner.  # noqa: E501
        :type long_name: str
        :param description: The description of this DtcDopDtcsRawInner.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this DtcDopDtcsRawInner.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this DtcDopDtcsRawInner.  # noqa: E501
        :type oid: str
        :param trouble_code: The trouble_code of this DtcDopDtcsRawInner.  # noqa: E501
        :type trouble_code: int
        :param display_trouble_code: The display_trouble_code of this DtcDopDtcsRawInner.  # noqa: E501
        :type display_trouble_code: str
        :param text: The text of this DtcDopDtcsRawInner.  # noqa: E501
        :type text: Text
        :param level: The level of this DtcDopDtcsRawInner.  # noqa: E501
        :type level: int
        :param sdgs: The sdgs of this DtcDopDtcsRawInner.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param is_temporary_raw: The is_temporary_raw of this DtcDopDtcsRawInner.  # noqa: E501
        :type is_temporary_raw: bool
        :param is_temporary: The is_temporary of this DtcDopDtcsRawInner.  # noqa: E501
        :type is_temporary: bool
        :param perma_id: The perma_id of this DtcDopDtcsRawInner.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this DtcDopDtcsRawInner.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this DtcDopDtcsRawInner.  # noqa: E501
        :type class_name: str
        :param ref_id: The ref_id of this DtcDopDtcsRawInner.  # noqa: E501
        :type ref_id: str
        :param ref_docs: The ref_docs of this DtcDopDtcsRawInner.  # noqa: E501
        :type ref_docs: List[OdxDocFragment]
        :param resolved_object_perma_id: The resolved_object_perma_id of this DtcDopDtcsRawInner.  # noqa: E501
        :type resolved_object_perma_id: str
        :param resolved_object_ephemeral_id: The resolved_object_ephemeral_id of this DtcDopDtcsRawInner.  # noqa: E501
        :type resolved_object_ephemeral_id: int
        :param resolved_object_short_name: The resolved_object_short_name of this DtcDopDtcsRawInner.  # noqa: E501
        :type resolved_object_short_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'trouble_code': int,
            'display_trouble_code': str,
            'text': Text,
            'level': int,
            'sdgs': List[SpecialDataGroup],
            'is_temporary_raw': bool,
            'is_temporary': bool,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str,
            'ref_id': str,
            'ref_docs': List[OdxDocFragment],
            'resolved_object_perma_id': str,
            'resolved_object_ephemeral_id': int,
            'resolved_object_short_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'trouble_code': 'trouble_code',
            'display_trouble_code': 'display_trouble_code',
            'text': 'text',
            'level': 'level',
            'sdgs': 'sdgs',
            'is_temporary_raw': 'is_temporary_raw',
            'is_temporary': 'is_temporary',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name',
            'ref_id': 'ref_id',
            'ref_docs': 'ref_docs',
            'resolved_object_perma_id': 'resolved_object_perma_id',
            'resolved_object_ephemeral_id': 'resolved_object_ephemeral_id',
            'resolved_object_short_name': 'resolved_object_short_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._trouble_code = trouble_code
        self._display_trouble_code = display_trouble_code
        self._text = text
        self._level = level
        self._sdgs = sdgs
        self._is_temporary_raw = is_temporary_raw
        self._is_temporary = is_temporary
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name
        self._ref_id = ref_id
        self._ref_docs = ref_docs
        self._resolved_object_perma_id = resolved_object_perma_id
        self._resolved_object_ephemeral_id = resolved_object_ephemeral_id
        self._resolved_object_short_name = resolved_object_short_name

    @classmethod
    def from_dict(cls, dikt) -> 'DtcDopDtcsRawInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DtcDop_dtcs_raw_inner of this DtcDopDtcsRawInner.  # noqa: E501
        :rtype: DtcDopDtcsRawInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this DtcDopDtcsRawInner.


        :return: The short_name of this DtcDopDtcsRawInner.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this DtcDopDtcsRawInner.


        :param short_name: The short_name of this DtcDopDtcsRawInner.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this DtcDopDtcsRawInner.


        :return: The long_name of this DtcDopDtcsRawInner.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this DtcDopDtcsRawInner.


        :param long_name: The long_name of this DtcDopDtcsRawInner.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this DtcDopDtcsRawInner.


        :return: The description of this DtcDopDtcsRawInner.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this DtcDopDtcsRawInner.


        :param description: The description of this DtcDopDtcsRawInner.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this DtcDopDtcsRawInner.


        :return: The odx_id of this DtcDopDtcsRawInner.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this DtcDopDtcsRawInner.


        :param odx_id: The odx_id of this DtcDopDtcsRawInner.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this DtcDopDtcsRawInner.


        :return: The oid of this DtcDopDtcsRawInner.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this DtcDopDtcsRawInner.


        :param oid: The oid of this DtcDopDtcsRawInner.
        :type oid: str
        """

        self._oid = oid

    @property
    def trouble_code(self) -> int:
        """Gets the trouble_code of this DtcDopDtcsRawInner.


        :return: The trouble_code of this DtcDopDtcsRawInner.
        :rtype: int
        """
        return self._trouble_code

    @trouble_code.setter
    def trouble_code(self, trouble_code: int):
        """Sets the trouble_code of this DtcDopDtcsRawInner.


        :param trouble_code: The trouble_code of this DtcDopDtcsRawInner.
        :type trouble_code: int
        """

        self._trouble_code = trouble_code

    @property
    def display_trouble_code(self) -> str:
        """Gets the display_trouble_code of this DtcDopDtcsRawInner.


        :return: The display_trouble_code of this DtcDopDtcsRawInner.
        :rtype: str
        """
        return self._display_trouble_code

    @display_trouble_code.setter
    def display_trouble_code(self, display_trouble_code: str):
        """Sets the display_trouble_code of this DtcDopDtcsRawInner.


        :param display_trouble_code: The display_trouble_code of this DtcDopDtcsRawInner.
        :type display_trouble_code: str
        """

        self._display_trouble_code = display_trouble_code

    @property
    def text(self) -> Text:
        """Gets the text of this DtcDopDtcsRawInner.


        :return: The text of this DtcDopDtcsRawInner.
        :rtype: Text
        """
        return self._text

    @text.setter
    def text(self, text: Text):
        """Sets the text of this DtcDopDtcsRawInner.


        :param text: The text of this DtcDopDtcsRawInner.
        :type text: Text
        """

        self._text = text

    @property
    def level(self) -> int:
        """Gets the level of this DtcDopDtcsRawInner.


        :return: The level of this DtcDopDtcsRawInner.
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level: int):
        """Sets the level of this DtcDopDtcsRawInner.


        :param level: The level of this DtcDopDtcsRawInner.
        :type level: int
        """

        self._level = level

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this DtcDopDtcsRawInner.


        :return: The sdgs of this DtcDopDtcsRawInner.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this DtcDopDtcsRawInner.


        :param sdgs: The sdgs of this DtcDopDtcsRawInner.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def is_temporary_raw(self) -> bool:
        """Gets the is_temporary_raw of this DtcDopDtcsRawInner.


        :return: The is_temporary_raw of this DtcDopDtcsRawInner.
        :rtype: bool
        """
        return self._is_temporary_raw

    @is_temporary_raw.setter
    def is_temporary_raw(self, is_temporary_raw: bool):
        """Sets the is_temporary_raw of this DtcDopDtcsRawInner.


        :param is_temporary_raw: The is_temporary_raw of this DtcDopDtcsRawInner.
        :type is_temporary_raw: bool
        """

        self._is_temporary_raw = is_temporary_raw

    @property
    def is_temporary(self) -> bool:
        """Gets the is_temporary of this DtcDopDtcsRawInner.


        :return: The is_temporary of this DtcDopDtcsRawInner.
        :rtype: bool
        """
        return self._is_temporary

    @is_temporary.setter
    def is_temporary(self, is_temporary: bool):
        """Sets the is_temporary of this DtcDopDtcsRawInner.


        :param is_temporary: The is_temporary of this DtcDopDtcsRawInner.
        :type is_temporary: bool
        """

        self._is_temporary = is_temporary

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this DtcDopDtcsRawInner.


        :return: The perma_id of this DtcDopDtcsRawInner.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this DtcDopDtcsRawInner.


        :param perma_id: The perma_id of this DtcDopDtcsRawInner.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this DtcDopDtcsRawInner.


        :return: The ephemeral_id of this DtcDopDtcsRawInner.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this DtcDopDtcsRawInner.


        :param ephemeral_id: The ephemeral_id of this DtcDopDtcsRawInner.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this DtcDopDtcsRawInner.


        :return: The class_name of this DtcDopDtcsRawInner.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this DtcDopDtcsRawInner.


        :param class_name: The class_name of this DtcDopDtcsRawInner.
        :type class_name: str
        """

        self._class_name = class_name

    @property
    def ref_id(self) -> str:
        """Gets the ref_id of this DtcDopDtcsRawInner.


        :return: The ref_id of this DtcDopDtcsRawInner.
        :rtype: str
        """
        return self._ref_id

    @ref_id.setter
    def ref_id(self, ref_id: str):
        """Sets the ref_id of this DtcDopDtcsRawInner.


        :param ref_id: The ref_id of this DtcDopDtcsRawInner.
        :type ref_id: str
        """

        self._ref_id = ref_id

    @property
    def ref_docs(self) -> List[OdxDocFragment]:
        """Gets the ref_docs of this DtcDopDtcsRawInner.


        :return: The ref_docs of this DtcDopDtcsRawInner.
        :rtype: List[OdxDocFragment]
        """
        return self._ref_docs

    @ref_docs.setter
    def ref_docs(self, ref_docs: List[OdxDocFragment]):
        """Sets the ref_docs of this DtcDopDtcsRawInner.


        :param ref_docs: The ref_docs of this DtcDopDtcsRawInner.
        :type ref_docs: List[OdxDocFragment]
        """

        self._ref_docs = ref_docs

    @property
    def resolved_object_perma_id(self) -> str:
        """Gets the resolved_object_perma_id of this DtcDopDtcsRawInner.


        :return: The resolved_object_perma_id of this DtcDopDtcsRawInner.
        :rtype: str
        """
        return self._resolved_object_perma_id

    @resolved_object_perma_id.setter
    def resolved_object_perma_id(self, resolved_object_perma_id: str):
        """Sets the resolved_object_perma_id of this DtcDopDtcsRawInner.


        :param resolved_object_perma_id: The resolved_object_perma_id of this DtcDopDtcsRawInner.
        :type resolved_object_perma_id: str
        """

        self._resolved_object_perma_id = resolved_object_perma_id

    @property
    def resolved_object_ephemeral_id(self) -> int:
        """Gets the resolved_object_ephemeral_id of this DtcDopDtcsRawInner.


        :return: The resolved_object_ephemeral_id of this DtcDopDtcsRawInner.
        :rtype: int
        """
        return self._resolved_object_ephemeral_id

    @resolved_object_ephemeral_id.setter
    def resolved_object_ephemeral_id(self, resolved_object_ephemeral_id: int):
        """Sets the resolved_object_ephemeral_id of this DtcDopDtcsRawInner.


        :param resolved_object_ephemeral_id: The resolved_object_ephemeral_id of this DtcDopDtcsRawInner.
        :type resolved_object_ephemeral_id: int
        """

        self._resolved_object_ephemeral_id = resolved_object_ephemeral_id

    @property
    def resolved_object_short_name(self) -> str:
        """Gets the resolved_object_short_name of this DtcDopDtcsRawInner.


        :return: The resolved_object_short_name of this DtcDopDtcsRawInner.
        :rtype: str
        """
        return self._resolved_object_short_name

    @resolved_object_short_name.setter
    def resolved_object_short_name(self, resolved_object_short_name: str):
        """Sets the resolved_object_short_name of this DtcDopDtcsRawInner.


        :param resolved_object_short_name: The resolved_object_short_name of this DtcDopDtcsRawInner.
        :type resolved_object_short_name: str
        """

        self._resolved_object_short_name = resolved_object_short_name
