# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.diag_comm_resolved import DiagCommResolved
from diag_server.openapi_server.models.dyn_id_def_mode_info_selection_table_refs_inner import DynIdDefModeInfoSelectionTableRefsInner
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server.models.table import Table
from diag_server.openapi_server import util

from diag_server.openapi_server.models.diag_comm_resolved import DiagCommResolved  # noqa: E501
from diag_server.openapi_server.models.dyn_id_def_mode_info_selection_table_refs_inner import DynIdDefModeInfoSelectionTableRefsInner  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501
from diag_server.openapi_server.models.table import Table  # noqa: E501

class DynIdDefModeInfoResolved(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, def_mode=None, clear_dyn_def_message_ref=None, clear_dyn_def_message=None, clear_dyn_def_message_snref=None, read_dyn_def_message_ref=None, read_dyn_def_message=None, read_dyn_def_message_snref=None, dyn_def_message_ref=None, dyn_def_message=None, dyn_def_message_snref=None, supported_dyn_ids=None, selection_table_refs=None, selection_tables=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """DynIdDefModeInfoResolved - a model defined in OpenAPI

        :param def_mode: The def_mode of this DynIdDefModeInfoResolved.  # noqa: E501
        :type def_mode: str
        :param clear_dyn_def_message_ref: The clear_dyn_def_message_ref of this DynIdDefModeInfoResolved.  # noqa: E501
        :type clear_dyn_def_message_ref: OdxLinkRef
        :param clear_dyn_def_message: The clear_dyn_def_message of this DynIdDefModeInfoResolved.  # noqa: E501
        :type clear_dyn_def_message: DiagCommResolved
        :param clear_dyn_def_message_snref: The clear_dyn_def_message_snref of this DynIdDefModeInfoResolved.  # noqa: E501
        :type clear_dyn_def_message_snref: str
        :param read_dyn_def_message_ref: The read_dyn_def_message_ref of this DynIdDefModeInfoResolved.  # noqa: E501
        :type read_dyn_def_message_ref: OdxLinkRef
        :param read_dyn_def_message: The read_dyn_def_message of this DynIdDefModeInfoResolved.  # noqa: E501
        :type read_dyn_def_message: DiagCommResolved
        :param read_dyn_def_message_snref: The read_dyn_def_message_snref of this DynIdDefModeInfoResolved.  # noqa: E501
        :type read_dyn_def_message_snref: str
        :param dyn_def_message_ref: The dyn_def_message_ref of this DynIdDefModeInfoResolved.  # noqa: E501
        :type dyn_def_message_ref: OdxLinkRef
        :param dyn_def_message: The dyn_def_message of this DynIdDefModeInfoResolved.  # noqa: E501
        :type dyn_def_message: DiagCommResolved
        :param dyn_def_message_snref: The dyn_def_message_snref of this DynIdDefModeInfoResolved.  # noqa: E501
        :type dyn_def_message_snref: str
        :param supported_dyn_ids: The supported_dyn_ids of this DynIdDefModeInfoResolved.  # noqa: E501
        :type supported_dyn_ids: List[str]
        :param selection_table_refs: The selection_table_refs of this DynIdDefModeInfoResolved.  # noqa: E501
        :type selection_table_refs: List[DynIdDefModeInfoSelectionTableRefsInner]
        :param selection_tables: The selection_tables of this DynIdDefModeInfoResolved.  # noqa: E501
        :type selection_tables: List[Table]
        :param perma_id: The perma_id of this DynIdDefModeInfoResolved.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this DynIdDefModeInfoResolved.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this DynIdDefModeInfoResolved.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'def_mode': str,
            'clear_dyn_def_message_ref': OdxLinkRef,
            'clear_dyn_def_message': DiagCommResolved,
            'clear_dyn_def_message_snref': str,
            'read_dyn_def_message_ref': OdxLinkRef,
            'read_dyn_def_message': DiagCommResolved,
            'read_dyn_def_message_snref': str,
            'dyn_def_message_ref': OdxLinkRef,
            'dyn_def_message': DiagCommResolved,
            'dyn_def_message_snref': str,
            'supported_dyn_ids': List[str],
            'selection_table_refs': List[DynIdDefModeInfoSelectionTableRefsInner],
            'selection_tables': List[Table],
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'def_mode': 'def_mode',
            'clear_dyn_def_message_ref': 'clear_dyn_def_message_ref',
            'clear_dyn_def_message': 'clear_dyn_def_message',
            'clear_dyn_def_message_snref': 'clear_dyn_def_message_snref',
            'read_dyn_def_message_ref': 'read_dyn_def_message_ref',
            'read_dyn_def_message': 'read_dyn_def_message',
            'read_dyn_def_message_snref': 'read_dyn_def_message_snref',
            'dyn_def_message_ref': 'dyn_def_message_ref',
            'dyn_def_message': 'dyn_def_message',
            'dyn_def_message_snref': 'dyn_def_message_snref',
            'supported_dyn_ids': 'supported_dyn_ids',
            'selection_table_refs': 'selection_table_refs',
            'selection_tables': 'selection_tables',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._def_mode = def_mode
        self._clear_dyn_def_message_ref = clear_dyn_def_message_ref
        self._clear_dyn_def_message = clear_dyn_def_message
        self._clear_dyn_def_message_snref = clear_dyn_def_message_snref
        self._read_dyn_def_message_ref = read_dyn_def_message_ref
        self._read_dyn_def_message = read_dyn_def_message
        self._read_dyn_def_message_snref = read_dyn_def_message_snref
        self._dyn_def_message_ref = dyn_def_message_ref
        self._dyn_def_message = dyn_def_message
        self._dyn_def_message_snref = dyn_def_message_snref
        self._supported_dyn_ids = supported_dyn_ids
        self._selection_table_refs = selection_table_refs
        self._selection_tables = selection_tables
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'DynIdDefModeInfoResolved':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DynIdDefModeInfoResolved of this DynIdDefModeInfoResolved.  # noqa: E501
        :rtype: DynIdDefModeInfoResolved
        """
        return util.deserialize_model(dikt, cls)

    @property
    def def_mode(self) -> str:
        """Gets the def_mode of this DynIdDefModeInfoResolved.


        :return: The def_mode of this DynIdDefModeInfoResolved.
        :rtype: str
        """
        return self._def_mode

    @def_mode.setter
    def def_mode(self, def_mode: str):
        """Sets the def_mode of this DynIdDefModeInfoResolved.


        :param def_mode: The def_mode of this DynIdDefModeInfoResolved.
        :type def_mode: str
        """

        self._def_mode = def_mode

    @property
    def clear_dyn_def_message_ref(self) -> OdxLinkRef:
        """Gets the clear_dyn_def_message_ref of this DynIdDefModeInfoResolved.


        :return: The clear_dyn_def_message_ref of this DynIdDefModeInfoResolved.
        :rtype: OdxLinkRef
        """
        return self._clear_dyn_def_message_ref

    @clear_dyn_def_message_ref.setter
    def clear_dyn_def_message_ref(self, clear_dyn_def_message_ref: OdxLinkRef):
        """Sets the clear_dyn_def_message_ref of this DynIdDefModeInfoResolved.


        :param clear_dyn_def_message_ref: The clear_dyn_def_message_ref of this DynIdDefModeInfoResolved.
        :type clear_dyn_def_message_ref: OdxLinkRef
        """

        self._clear_dyn_def_message_ref = clear_dyn_def_message_ref

    @property
    def clear_dyn_def_message(self) -> DiagCommResolved:
        """Gets the clear_dyn_def_message of this DynIdDefModeInfoResolved.


        :return: The clear_dyn_def_message of this DynIdDefModeInfoResolved.
        :rtype: DiagCommResolved
        """
        return self._clear_dyn_def_message

    @clear_dyn_def_message.setter
    def clear_dyn_def_message(self, clear_dyn_def_message: DiagCommResolved):
        """Sets the clear_dyn_def_message of this DynIdDefModeInfoResolved.


        :param clear_dyn_def_message: The clear_dyn_def_message of this DynIdDefModeInfoResolved.
        :type clear_dyn_def_message: DiagCommResolved
        """

        self._clear_dyn_def_message = clear_dyn_def_message

    @property
    def clear_dyn_def_message_snref(self) -> str:
        """Gets the clear_dyn_def_message_snref of this DynIdDefModeInfoResolved.


        :return: The clear_dyn_def_message_snref of this DynIdDefModeInfoResolved.
        :rtype: str
        """
        return self._clear_dyn_def_message_snref

    @clear_dyn_def_message_snref.setter
    def clear_dyn_def_message_snref(self, clear_dyn_def_message_snref: str):
        """Sets the clear_dyn_def_message_snref of this DynIdDefModeInfoResolved.


        :param clear_dyn_def_message_snref: The clear_dyn_def_message_snref of this DynIdDefModeInfoResolved.
        :type clear_dyn_def_message_snref: str
        """

        self._clear_dyn_def_message_snref = clear_dyn_def_message_snref

    @property
    def read_dyn_def_message_ref(self) -> OdxLinkRef:
        """Gets the read_dyn_def_message_ref of this DynIdDefModeInfoResolved.


        :return: The read_dyn_def_message_ref of this DynIdDefModeInfoResolved.
        :rtype: OdxLinkRef
        """
        return self._read_dyn_def_message_ref

    @read_dyn_def_message_ref.setter
    def read_dyn_def_message_ref(self, read_dyn_def_message_ref: OdxLinkRef):
        """Sets the read_dyn_def_message_ref of this DynIdDefModeInfoResolved.


        :param read_dyn_def_message_ref: The read_dyn_def_message_ref of this DynIdDefModeInfoResolved.
        :type read_dyn_def_message_ref: OdxLinkRef
        """

        self._read_dyn_def_message_ref = read_dyn_def_message_ref

    @property
    def read_dyn_def_message(self) -> DiagCommResolved:
        """Gets the read_dyn_def_message of this DynIdDefModeInfoResolved.


        :return: The read_dyn_def_message of this DynIdDefModeInfoResolved.
        :rtype: DiagCommResolved
        """
        return self._read_dyn_def_message

    @read_dyn_def_message.setter
    def read_dyn_def_message(self, read_dyn_def_message: DiagCommResolved):
        """Sets the read_dyn_def_message of this DynIdDefModeInfoResolved.


        :param read_dyn_def_message: The read_dyn_def_message of this DynIdDefModeInfoResolved.
        :type read_dyn_def_message: DiagCommResolved
        """

        self._read_dyn_def_message = read_dyn_def_message

    @property
    def read_dyn_def_message_snref(self) -> str:
        """Gets the read_dyn_def_message_snref of this DynIdDefModeInfoResolved.


        :return: The read_dyn_def_message_snref of this DynIdDefModeInfoResolved.
        :rtype: str
        """
        return self._read_dyn_def_message_snref

    @read_dyn_def_message_snref.setter
    def read_dyn_def_message_snref(self, read_dyn_def_message_snref: str):
        """Sets the read_dyn_def_message_snref of this DynIdDefModeInfoResolved.


        :param read_dyn_def_message_snref: The read_dyn_def_message_snref of this DynIdDefModeInfoResolved.
        :type read_dyn_def_message_snref: str
        """

        self._read_dyn_def_message_snref = read_dyn_def_message_snref

    @property
    def dyn_def_message_ref(self) -> OdxLinkRef:
        """Gets the dyn_def_message_ref of this DynIdDefModeInfoResolved.


        :return: The dyn_def_message_ref of this DynIdDefModeInfoResolved.
        :rtype: OdxLinkRef
        """
        return self._dyn_def_message_ref

    @dyn_def_message_ref.setter
    def dyn_def_message_ref(self, dyn_def_message_ref: OdxLinkRef):
        """Sets the dyn_def_message_ref of this DynIdDefModeInfoResolved.


        :param dyn_def_message_ref: The dyn_def_message_ref of this DynIdDefModeInfoResolved.
        :type dyn_def_message_ref: OdxLinkRef
        """

        self._dyn_def_message_ref = dyn_def_message_ref

    @property
    def dyn_def_message(self) -> DiagCommResolved:
        """Gets the dyn_def_message of this DynIdDefModeInfoResolved.


        :return: The dyn_def_message of this DynIdDefModeInfoResolved.
        :rtype: DiagCommResolved
        """
        return self._dyn_def_message

    @dyn_def_message.setter
    def dyn_def_message(self, dyn_def_message: DiagCommResolved):
        """Sets the dyn_def_message of this DynIdDefModeInfoResolved.


        :param dyn_def_message: The dyn_def_message of this DynIdDefModeInfoResolved.
        :type dyn_def_message: DiagCommResolved
        """

        self._dyn_def_message = dyn_def_message

    @property
    def dyn_def_message_snref(self) -> str:
        """Gets the dyn_def_message_snref of this DynIdDefModeInfoResolved.


        :return: The dyn_def_message_snref of this DynIdDefModeInfoResolved.
        :rtype: str
        """
        return self._dyn_def_message_snref

    @dyn_def_message_snref.setter
    def dyn_def_message_snref(self, dyn_def_message_snref: str):
        """Sets the dyn_def_message_snref of this DynIdDefModeInfoResolved.


        :param dyn_def_message_snref: The dyn_def_message_snref of this DynIdDefModeInfoResolved.
        :type dyn_def_message_snref: str
        """

        self._dyn_def_message_snref = dyn_def_message_snref

    @property
    def supported_dyn_ids(self) -> List[str]:
        """Gets the supported_dyn_ids of this DynIdDefModeInfoResolved.


        :return: The supported_dyn_ids of this DynIdDefModeInfoResolved.
        :rtype: List[str]
        """
        return self._supported_dyn_ids

    @supported_dyn_ids.setter
    def supported_dyn_ids(self, supported_dyn_ids: List[str]):
        """Sets the supported_dyn_ids of this DynIdDefModeInfoResolved.


        :param supported_dyn_ids: The supported_dyn_ids of this DynIdDefModeInfoResolved.
        :type supported_dyn_ids: List[str]
        """

        self._supported_dyn_ids = supported_dyn_ids

    @property
    def selection_table_refs(self) -> List[DynIdDefModeInfoSelectionTableRefsInner]:
        """Gets the selection_table_refs of this DynIdDefModeInfoResolved.


        :return: The selection_table_refs of this DynIdDefModeInfoResolved.
        :rtype: List[DynIdDefModeInfoSelectionTableRefsInner]
        """
        return self._selection_table_refs

    @selection_table_refs.setter
    def selection_table_refs(self, selection_table_refs: List[DynIdDefModeInfoSelectionTableRefsInner]):
        """Sets the selection_table_refs of this DynIdDefModeInfoResolved.


        :param selection_table_refs: The selection_table_refs of this DynIdDefModeInfoResolved.
        :type selection_table_refs: List[DynIdDefModeInfoSelectionTableRefsInner]
        """

        self._selection_table_refs = selection_table_refs

    @property
    def selection_tables(self) -> List[Table]:
        """Gets the selection_tables of this DynIdDefModeInfoResolved.


        :return: The selection_tables of this DynIdDefModeInfoResolved.
        :rtype: List[Table]
        """
        return self._selection_tables

    @selection_tables.setter
    def selection_tables(self, selection_tables: List[Table]):
        """Sets the selection_tables of this DynIdDefModeInfoResolved.


        :param selection_tables: The selection_tables of this DynIdDefModeInfoResolved.
        :type selection_tables: List[Table]
        """

        self._selection_tables = selection_tables

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this DynIdDefModeInfoResolved.


        :return: The perma_id of this DynIdDefModeInfoResolved.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this DynIdDefModeInfoResolved.


        :param perma_id: The perma_id of this DynIdDefModeInfoResolved.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this DynIdDefModeInfoResolved.


        :return: The ephemeral_id of this DynIdDefModeInfoResolved.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this DynIdDefModeInfoResolved.


        :param ephemeral_id: The ephemeral_id of this DynIdDefModeInfoResolved.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this DynIdDefModeInfoResolved.


        :return: The class_name of this DynIdDefModeInfoResolved.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this DynIdDefModeInfoResolved.


        :param class_name: The class_name of this DynIdDefModeInfoResolved.
        :type class_name: str
        """

        self._class_name = class_name
