# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.odx_doc_fragment import OdxDocFragment
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server import util

from diag_server.openapi_server.models.odx_doc_fragment import OdxDocFragment  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501

class DynIdDefModeInfoSelectionTableRefsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ref_id=None, ref_docs=None, resolved_object_perma_id=None, resolved_object_ephemeral_id=None, resolved_object_short_name=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """DynIdDefModeInfoSelectionTableRefsInner - a model defined in OpenAPI

        :param ref_id: The ref_id of this DynIdDefModeInfoSelectionTableRefsInner.  # noqa: E501
        :type ref_id: str
        :param ref_docs: The ref_docs of this DynIdDefModeInfoSelectionTableRefsInner.  # noqa: E501
        :type ref_docs: List[OdxDocFragment]
        :param resolved_object_perma_id: The resolved_object_perma_id of this DynIdDefModeInfoSelectionTableRefsInner.  # noqa: E501
        :type resolved_object_perma_id: str
        :param resolved_object_ephemeral_id: The resolved_object_ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.  # noqa: E501
        :type resolved_object_ephemeral_id: int
        :param resolved_object_short_name: The resolved_object_short_name of this DynIdDefModeInfoSelectionTableRefsInner.  # noqa: E501
        :type resolved_object_short_name: str
        :param perma_id: The perma_id of this DynIdDefModeInfoSelectionTableRefsInner.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this DynIdDefModeInfoSelectionTableRefsInner.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'ref_id': str,
            'ref_docs': List[OdxDocFragment],
            'resolved_object_perma_id': str,
            'resolved_object_ephemeral_id': int,
            'resolved_object_short_name': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'ref_id': 'ref_id',
            'ref_docs': 'ref_docs',
            'resolved_object_perma_id': 'resolved_object_perma_id',
            'resolved_object_ephemeral_id': 'resolved_object_ephemeral_id',
            'resolved_object_short_name': 'resolved_object_short_name',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._ref_id = ref_id
        self._ref_docs = ref_docs
        self._resolved_object_perma_id = resolved_object_perma_id
        self._resolved_object_ephemeral_id = resolved_object_ephemeral_id
        self._resolved_object_short_name = resolved_object_short_name
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'DynIdDefModeInfoSelectionTableRefsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DynIdDefModeInfo_selection_table_refs_inner of this DynIdDefModeInfoSelectionTableRefsInner.  # noqa: E501
        :rtype: DynIdDefModeInfoSelectionTableRefsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ref_id(self) -> str:
        """Gets the ref_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :return: The ref_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :rtype: str
        """
        return self._ref_id

    @ref_id.setter
    def ref_id(self, ref_id: str):
        """Sets the ref_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :param ref_id: The ref_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :type ref_id: str
        """

        self._ref_id = ref_id

    @property
    def ref_docs(self) -> List[OdxDocFragment]:
        """Gets the ref_docs of this DynIdDefModeInfoSelectionTableRefsInner.


        :return: The ref_docs of this DynIdDefModeInfoSelectionTableRefsInner.
        :rtype: List[OdxDocFragment]
        """
        return self._ref_docs

    @ref_docs.setter
    def ref_docs(self, ref_docs: List[OdxDocFragment]):
        """Sets the ref_docs of this DynIdDefModeInfoSelectionTableRefsInner.


        :param ref_docs: The ref_docs of this DynIdDefModeInfoSelectionTableRefsInner.
        :type ref_docs: List[OdxDocFragment]
        """

        self._ref_docs = ref_docs

    @property
    def resolved_object_perma_id(self) -> str:
        """Gets the resolved_object_perma_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :return: The resolved_object_perma_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :rtype: str
        """
        return self._resolved_object_perma_id

    @resolved_object_perma_id.setter
    def resolved_object_perma_id(self, resolved_object_perma_id: str):
        """Sets the resolved_object_perma_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :param resolved_object_perma_id: The resolved_object_perma_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :type resolved_object_perma_id: str
        """

        self._resolved_object_perma_id = resolved_object_perma_id

    @property
    def resolved_object_ephemeral_id(self) -> int:
        """Gets the resolved_object_ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :return: The resolved_object_ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :rtype: int
        """
        return self._resolved_object_ephemeral_id

    @resolved_object_ephemeral_id.setter
    def resolved_object_ephemeral_id(self, resolved_object_ephemeral_id: int):
        """Sets the resolved_object_ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :param resolved_object_ephemeral_id: The resolved_object_ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :type resolved_object_ephemeral_id: int
        """

        self._resolved_object_ephemeral_id = resolved_object_ephemeral_id

    @property
    def resolved_object_short_name(self) -> str:
        """Gets the resolved_object_short_name of this DynIdDefModeInfoSelectionTableRefsInner.


        :return: The resolved_object_short_name of this DynIdDefModeInfoSelectionTableRefsInner.
        :rtype: str
        """
        return self._resolved_object_short_name

    @resolved_object_short_name.setter
    def resolved_object_short_name(self, resolved_object_short_name: str):
        """Sets the resolved_object_short_name of this DynIdDefModeInfoSelectionTableRefsInner.


        :param resolved_object_short_name: The resolved_object_short_name of this DynIdDefModeInfoSelectionTableRefsInner.
        :type resolved_object_short_name: str
        """

        self._resolved_object_short_name = resolved_object_short_name

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :return: The perma_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :param perma_id: The perma_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :return: The ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.


        :param ephemeral_id: The ephemeral_id of this DynIdDefModeInfoSelectionTableRefsInner.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this DynIdDefModeInfoSelectionTableRefsInner.


        :return: The class_name of this DynIdDefModeInfoSelectionTableRefsInner.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this DynIdDefModeInfoSelectionTableRefsInner.


        :param class_name: The class_name of this DynIdDefModeInfoSelectionTableRefsInner.
        :type class_name: str
        """

        self._class_name = class_name
