# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.admin_data import AdminData
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.mem import Mem
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.phys_mem import PhysMem
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server import util

from diag_server.openapi_server.models.admin_data import AdminData  # noqa: E501
from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.mem import Mem  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.phys_mem import PhysMem  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501

class EcuMem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, admin_data=None, mem=None, phys_mem=None, sdgs=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """EcuMem - a model defined in OpenAPI

        :param short_name: The short_name of this EcuMem.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this EcuMem.  # noqa: E501
        :type long_name: str
        :param description: The description of this EcuMem.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this EcuMem.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this EcuMem.  # noqa: E501
        :type oid: str
        :param admin_data: The admin_data of this EcuMem.  # noqa: E501
        :type admin_data: AdminData
        :param mem: The mem of this EcuMem.  # noqa: E501
        :type mem: Mem
        :param phys_mem: The phys_mem of this EcuMem.  # noqa: E501
        :type phys_mem: PhysMem
        :param sdgs: The sdgs of this EcuMem.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param perma_id: The perma_id of this EcuMem.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this EcuMem.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this EcuMem.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'admin_data': AdminData,
            'mem': Mem,
            'phys_mem': PhysMem,
            'sdgs': List[SpecialDataGroup],
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'admin_data': 'admin_data',
            'mem': 'mem',
            'phys_mem': 'phys_mem',
            'sdgs': 'sdgs',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._admin_data = admin_data
        self._mem = mem
        self._phys_mem = phys_mem
        self._sdgs = sdgs
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'EcuMem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EcuMem of this EcuMem.  # noqa: E501
        :rtype: EcuMem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this EcuMem.


        :return: The short_name of this EcuMem.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this EcuMem.


        :param short_name: The short_name of this EcuMem.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this EcuMem.


        :return: The long_name of this EcuMem.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this EcuMem.


        :param long_name: The long_name of this EcuMem.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this EcuMem.


        :return: The description of this EcuMem.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this EcuMem.


        :param description: The description of this EcuMem.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this EcuMem.


        :return: The odx_id of this EcuMem.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this EcuMem.


        :param odx_id: The odx_id of this EcuMem.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this EcuMem.


        :return: The oid of this EcuMem.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this EcuMem.


        :param oid: The oid of this EcuMem.
        :type oid: str
        """

        self._oid = oid

    @property
    def admin_data(self) -> AdminData:
        """Gets the admin_data of this EcuMem.


        :return: The admin_data of this EcuMem.
        :rtype: AdminData
        """
        return self._admin_data

    @admin_data.setter
    def admin_data(self, admin_data: AdminData):
        """Sets the admin_data of this EcuMem.


        :param admin_data: The admin_data of this EcuMem.
        :type admin_data: AdminData
        """

        self._admin_data = admin_data

    @property
    def mem(self) -> Mem:
        """Gets the mem of this EcuMem.


        :return: The mem of this EcuMem.
        :rtype: Mem
        """
        return self._mem

    @mem.setter
    def mem(self, mem: Mem):
        """Sets the mem of this EcuMem.


        :param mem: The mem of this EcuMem.
        :type mem: Mem
        """

        self._mem = mem

    @property
    def phys_mem(self) -> PhysMem:
        """Gets the phys_mem of this EcuMem.


        :return: The phys_mem of this EcuMem.
        :rtype: PhysMem
        """
        return self._phys_mem

    @phys_mem.setter
    def phys_mem(self, phys_mem: PhysMem):
        """Sets the phys_mem of this EcuMem.


        :param phys_mem: The phys_mem of this EcuMem.
        :type phys_mem: PhysMem
        """

        self._phys_mem = phys_mem

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this EcuMem.


        :return: The sdgs of this EcuMem.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this EcuMem.


        :param sdgs: The sdgs of this EcuMem.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this EcuMem.


        :return: The perma_id of this EcuMem.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this EcuMem.


        :param perma_id: The perma_id of this EcuMem.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this EcuMem.


        :return: The ephemeral_id of this EcuMem.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this EcuMem.


        :param ephemeral_id: The ephemeral_id of this EcuMem.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this EcuMem.


        :return: The class_name of this EcuMem.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this EcuMem.


        :param class_name: The class_name of this EcuMem.
        :type class_name: str
        """

        self._class_name = class_name
