# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.encrypt_compress_method_type import EncryptCompressMethodType
from diag_server.openapi_server.models.limit_value import LimitValue
from diag_server.openapi_server import util

from diag_server.openapi_server.models.encrypt_compress_method_type import EncryptCompressMethodType  # noqa: E501
from diag_server.openapi_server.models.limit_value import LimitValue  # noqa: E501

class EncryptCompressMethod(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value_raw=None, value=None, value_type=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """EncryptCompressMethod - a model defined in OpenAPI

        :param value_raw: The value_raw of this EncryptCompressMethod.  # noqa: E501
        :type value_raw: str
        :param value: The value of this EncryptCompressMethod.  # noqa: E501
        :type value: LimitValue
        :param value_type: The value_type of this EncryptCompressMethod.  # noqa: E501
        :type value_type: EncryptCompressMethodType
        :param perma_id: The perma_id of this EncryptCompressMethod.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this EncryptCompressMethod.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this EncryptCompressMethod.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'value_raw': str,
            'value': LimitValue,
            'value_type': EncryptCompressMethodType,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'value_raw': 'value_raw',
            'value': 'value',
            'value_type': 'value_type',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._value_raw = value_raw
        self._value = value
        self._value_type = value_type
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'EncryptCompressMethod':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EncryptCompressMethod of this EncryptCompressMethod.  # noqa: E501
        :rtype: EncryptCompressMethod
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value_raw(self) -> str:
        """Gets the value_raw of this EncryptCompressMethod.


        :return: The value_raw of this EncryptCompressMethod.
        :rtype: str
        """
        return self._value_raw

    @value_raw.setter
    def value_raw(self, value_raw: str):
        """Sets the value_raw of this EncryptCompressMethod.


        :param value_raw: The value_raw of this EncryptCompressMethod.
        :type value_raw: str
        """

        self._value_raw = value_raw

    @property
    def value(self) -> LimitValue:
        """Gets the value of this EncryptCompressMethod.


        :return: The value of this EncryptCompressMethod.
        :rtype: LimitValue
        """
        return self._value

    @value.setter
    def value(self, value: LimitValue):
        """Sets the value of this EncryptCompressMethod.


        :param value: The value of this EncryptCompressMethod.
        :type value: LimitValue
        """

        self._value = value

    @property
    def value_type(self) -> EncryptCompressMethodType:
        """Gets the value_type of this EncryptCompressMethod.


        :return: The value_type of this EncryptCompressMethod.
        :rtype: EncryptCompressMethodType
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type: EncryptCompressMethodType):
        """Sets the value_type of this EncryptCompressMethod.


        :param value_type: The value_type of this EncryptCompressMethod.
        :type value_type: EncryptCompressMethodType
        """

        self._value_type = value_type

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this EncryptCompressMethod.


        :return: The perma_id of this EncryptCompressMethod.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this EncryptCompressMethod.


        :param perma_id: The perma_id of this EncryptCompressMethod.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this EncryptCompressMethod.


        :return: The ephemeral_id of this EncryptCompressMethod.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this EncryptCompressMethod.


        :param ephemeral_id: The ephemeral_id of this EncryptCompressMethod.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this EncryptCompressMethod.


        :return: The class_name of this EncryptCompressMethod.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this EncryptCompressMethod.


        :param class_name: The class_name of this EncryptCompressMethod.
        :type class_name: str
        """

        self._class_name = class_name
