# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501

class EnvDataConnector(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, env_data_desc_ref=None, env_data_snref=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """EnvDataConnector - a model defined in OpenAPI

        :param short_name: The short_name of this EnvDataConnector.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this EnvDataConnector.  # noqa: E501
        :type long_name: str
        :param description: The description of this EnvDataConnector.  # noqa: E501
        :type description: Description
        :param env_data_desc_ref: The env_data_desc_ref of this EnvDataConnector.  # noqa: E501
        :type env_data_desc_ref: OdxLinkRef
        :param env_data_snref: The env_data_snref of this EnvDataConnector.  # noqa: E501
        :type env_data_snref: str
        :param perma_id: The perma_id of this EnvDataConnector.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this EnvDataConnector.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this EnvDataConnector.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'env_data_desc_ref': OdxLinkRef,
            'env_data_snref': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'env_data_desc_ref': 'env_data_desc_ref',
            'env_data_snref': 'env_data_snref',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._env_data_desc_ref = env_data_desc_ref
        self._env_data_snref = env_data_snref
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'EnvDataConnector':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EnvDataConnector of this EnvDataConnector.  # noqa: E501
        :rtype: EnvDataConnector
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this EnvDataConnector.


        :return: The short_name of this EnvDataConnector.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this EnvDataConnector.


        :param short_name: The short_name of this EnvDataConnector.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this EnvDataConnector.


        :return: The long_name of this EnvDataConnector.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this EnvDataConnector.


        :param long_name: The long_name of this EnvDataConnector.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this EnvDataConnector.


        :return: The description of this EnvDataConnector.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this EnvDataConnector.


        :param description: The description of this EnvDataConnector.
        :type description: Description
        """

        self._description = description

    @property
    def env_data_desc_ref(self) -> OdxLinkRef:
        """Gets the env_data_desc_ref of this EnvDataConnector.


        :return: The env_data_desc_ref of this EnvDataConnector.
        :rtype: OdxLinkRef
        """
        return self._env_data_desc_ref

    @env_data_desc_ref.setter
    def env_data_desc_ref(self, env_data_desc_ref: OdxLinkRef):
        """Sets the env_data_desc_ref of this EnvDataConnector.


        :param env_data_desc_ref: The env_data_desc_ref of this EnvDataConnector.
        :type env_data_desc_ref: OdxLinkRef
        """

        self._env_data_desc_ref = env_data_desc_ref

    @property
    def env_data_snref(self) -> str:
        """Gets the env_data_snref of this EnvDataConnector.


        :return: The env_data_snref of this EnvDataConnector.
        :rtype: str
        """
        return self._env_data_snref

    @env_data_snref.setter
    def env_data_snref(self, env_data_snref: str):
        """Sets the env_data_snref of this EnvDataConnector.


        :param env_data_snref: The env_data_snref of this EnvDataConnector.
        :type env_data_snref: str
        """

        self._env_data_snref = env_data_snref

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this EnvDataConnector.


        :return: The perma_id of this EnvDataConnector.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this EnvDataConnector.


        :param perma_id: The perma_id of this EnvDataConnector.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this EnvDataConnector.


        :return: The ephemeral_id of this EnvDataConnector.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this EnvDataConnector.


        :param ephemeral_id: The ephemeral_id of this EnvDataConnector.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this EnvDataConnector.


        :return: The class_name of this EnvDataConnector.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this EnvDataConnector.


        :param class_name: The class_name of this EnvDataConnector.
        :type class_name: str
        """

        self._class_name = class_name
