# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.admin_data import AdminData
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server import util

from diag_server.openapi_server.models.admin_data import AdminData  # noqa: E501
from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501

class Field(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, admin_data=None, sdgs=None, structure_ref=None, structure_snref=None, env_data_desc_ref=None, env_data_desc_snref=None, is_visible_raw=None, is_visible=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """Field - a model defined in OpenAPI

        :param short_name: The short_name of this Field.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this Field.  # noqa: E501
        :type long_name: str
        :param description: The description of this Field.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this Field.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this Field.  # noqa: E501
        :type oid: str
        :param admin_data: The admin_data of this Field.  # noqa: E501
        :type admin_data: AdminData
        :param sdgs: The sdgs of this Field.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param structure_ref: The structure_ref of this Field.  # noqa: E501
        :type structure_ref: OdxLinkRef
        :param structure_snref: The structure_snref of this Field.  # noqa: E501
        :type structure_snref: str
        :param env_data_desc_ref: The env_data_desc_ref of this Field.  # noqa: E501
        :type env_data_desc_ref: OdxLinkRef
        :param env_data_desc_snref: The env_data_desc_snref of this Field.  # noqa: E501
        :type env_data_desc_snref: str
        :param is_visible_raw: The is_visible_raw of this Field.  # noqa: E501
        :type is_visible_raw: bool
        :param is_visible: The is_visible of this Field.  # noqa: E501
        :type is_visible: bool
        :param perma_id: The perma_id of this Field.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this Field.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this Field.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'admin_data': AdminData,
            'sdgs': List[SpecialDataGroup],
            'structure_ref': OdxLinkRef,
            'structure_snref': str,
            'env_data_desc_ref': OdxLinkRef,
            'env_data_desc_snref': str,
            'is_visible_raw': bool,
            'is_visible': bool,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'admin_data': 'admin_data',
            'sdgs': 'sdgs',
            'structure_ref': 'structure_ref',
            'structure_snref': 'structure_snref',
            'env_data_desc_ref': 'env_data_desc_ref',
            'env_data_desc_snref': 'env_data_desc_snref',
            'is_visible_raw': 'is_visible_raw',
            'is_visible': 'is_visible',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._admin_data = admin_data
        self._sdgs = sdgs
        self._structure_ref = structure_ref
        self._structure_snref = structure_snref
        self._env_data_desc_ref = env_data_desc_ref
        self._env_data_desc_snref = env_data_desc_snref
        self._is_visible_raw = is_visible_raw
        self._is_visible = is_visible
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'Field':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Field of this Field.  # noqa: E501
        :rtype: Field
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this Field.


        :return: The short_name of this Field.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this Field.


        :param short_name: The short_name of this Field.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this Field.


        :return: The long_name of this Field.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this Field.


        :param long_name: The long_name of this Field.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this Field.


        :return: The description of this Field.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this Field.


        :param description: The description of this Field.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this Field.


        :return: The odx_id of this Field.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this Field.


        :param odx_id: The odx_id of this Field.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this Field.


        :return: The oid of this Field.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this Field.


        :param oid: The oid of this Field.
        :type oid: str
        """

        self._oid = oid

    @property
    def admin_data(self) -> AdminData:
        """Gets the admin_data of this Field.


        :return: The admin_data of this Field.
        :rtype: AdminData
        """
        return self._admin_data

    @admin_data.setter
    def admin_data(self, admin_data: AdminData):
        """Sets the admin_data of this Field.


        :param admin_data: The admin_data of this Field.
        :type admin_data: AdminData
        """

        self._admin_data = admin_data

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this Field.


        :return: The sdgs of this Field.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this Field.


        :param sdgs: The sdgs of this Field.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def structure_ref(self) -> OdxLinkRef:
        """Gets the structure_ref of this Field.


        :return: The structure_ref of this Field.
        :rtype: OdxLinkRef
        """
        return self._structure_ref

    @structure_ref.setter
    def structure_ref(self, structure_ref: OdxLinkRef):
        """Sets the structure_ref of this Field.


        :param structure_ref: The structure_ref of this Field.
        :type structure_ref: OdxLinkRef
        """

        self._structure_ref = structure_ref

    @property
    def structure_snref(self) -> str:
        """Gets the structure_snref of this Field.


        :return: The structure_snref of this Field.
        :rtype: str
        """
        return self._structure_snref

    @structure_snref.setter
    def structure_snref(self, structure_snref: str):
        """Sets the structure_snref of this Field.


        :param structure_snref: The structure_snref of this Field.
        :type structure_snref: str
        """

        self._structure_snref = structure_snref

    @property
    def env_data_desc_ref(self) -> OdxLinkRef:
        """Gets the env_data_desc_ref of this Field.


        :return: The env_data_desc_ref of this Field.
        :rtype: OdxLinkRef
        """
        return self._env_data_desc_ref

    @env_data_desc_ref.setter
    def env_data_desc_ref(self, env_data_desc_ref: OdxLinkRef):
        """Sets the env_data_desc_ref of this Field.


        :param env_data_desc_ref: The env_data_desc_ref of this Field.
        :type env_data_desc_ref: OdxLinkRef
        """

        self._env_data_desc_ref = env_data_desc_ref

    @property
    def env_data_desc_snref(self) -> str:
        """Gets the env_data_desc_snref of this Field.


        :return: The env_data_desc_snref of this Field.
        :rtype: str
        """
        return self._env_data_desc_snref

    @env_data_desc_snref.setter
    def env_data_desc_snref(self, env_data_desc_snref: str):
        """Sets the env_data_desc_snref of this Field.


        :param env_data_desc_snref: The env_data_desc_snref of this Field.
        :type env_data_desc_snref: str
        """

        self._env_data_desc_snref = env_data_desc_snref

    @property
    def is_visible_raw(self) -> bool:
        """Gets the is_visible_raw of this Field.


        :return: The is_visible_raw of this Field.
        :rtype: bool
        """
        return self._is_visible_raw

    @is_visible_raw.setter
    def is_visible_raw(self, is_visible_raw: bool):
        """Sets the is_visible_raw of this Field.


        :param is_visible_raw: The is_visible_raw of this Field.
        :type is_visible_raw: bool
        """

        self._is_visible_raw = is_visible_raw

    @property
    def is_visible(self) -> bool:
        """Gets the is_visible of this Field.


        :return: The is_visible of this Field.
        :rtype: bool
        """
        return self._is_visible

    @is_visible.setter
    def is_visible(self, is_visible: bool):
        """Sets the is_visible of this Field.


        :param is_visible: The is_visible of this Field.
        :type is_visible: bool
        """

        self._is_visible = is_visible

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this Field.


        :return: The perma_id of this Field.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this Field.


        :param perma_id: The perma_id of this Field.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this Field.


        :return: The ephemeral_id of this Field.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this Field.


        :param ephemeral_id: The ephemeral_id of this Field.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this Field.


        :return: The class_name of this Field.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this Field.


        :param class_name: The class_name of this Field.
        :type class_name: str
        """

        self._class_name = class_name
