# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501

class IdentifiableElement(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """IdentifiableElement - a model defined in OpenAPI

        :param short_name: The short_name of this IdentifiableElement.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this IdentifiableElement.  # noqa: E501
        :type long_name: str
        :param description: The description of this IdentifiableElement.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this IdentifiableElement.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this IdentifiableElement.  # noqa: E501
        :type oid: str
        :param perma_id: The perma_id of this IdentifiableElement.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this IdentifiableElement.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this IdentifiableElement.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'IdentifiableElement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IdentifiableElement of this IdentifiableElement.  # noqa: E501
        :rtype: IdentifiableElement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this IdentifiableElement.


        :return: The short_name of this IdentifiableElement.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this IdentifiableElement.


        :param short_name: The short_name of this IdentifiableElement.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this IdentifiableElement.


        :return: The long_name of this IdentifiableElement.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this IdentifiableElement.


        :param long_name: The long_name of this IdentifiableElement.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this IdentifiableElement.


        :return: The description of this IdentifiableElement.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this IdentifiableElement.


        :param description: The description of this IdentifiableElement.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this IdentifiableElement.


        :return: The odx_id of this IdentifiableElement.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this IdentifiableElement.


        :param odx_id: The odx_id of this IdentifiableElement.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this IdentifiableElement.


        :return: The oid of this IdentifiableElement.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this IdentifiableElement.


        :param oid: The oid of this IdentifiableElement.
        :type oid: str
        """

        self._oid = oid

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this IdentifiableElement.


        :return: The perma_id of this IdentifiableElement.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this IdentifiableElement.


        :param perma_id: The perma_id of this IdentifiableElement.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this IdentifiableElement.


        :return: The ephemeral_id of this IdentifiableElement.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this IdentifiableElement.


        :param ephemeral_id: The ephemeral_id of this IdentifiableElement.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this IdentifiableElement.


        :return: The class_name of this IdentifiableElement.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this IdentifiableElement.


        :param class_name: The class_name of this IdentifiableElement.
        :type class_name: str
        """

        self._class_name = class_name
