# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501

class InputParam(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, physical_default_value=None, dop_base_ref=None, oid=None, semantic=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """InputParam - a model defined in OpenAPI

        :param short_name: The short_name of this InputParam.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this InputParam.  # noqa: E501
        :type long_name: str
        :param description: The description of this InputParam.  # noqa: E501
        :type description: Description
        :param physical_default_value: The physical_default_value of this InputParam.  # noqa: E501
        :type physical_default_value: str
        :param dop_base_ref: The dop_base_ref of this InputParam.  # noqa: E501
        :type dop_base_ref: OdxLinkRef
        :param oid: The oid of this InputParam.  # noqa: E501
        :type oid: str
        :param semantic: The semantic of this InputParam.  # noqa: E501
        :type semantic: str
        :param perma_id: The perma_id of this InputParam.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this InputParam.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this InputParam.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'physical_default_value': str,
            'dop_base_ref': OdxLinkRef,
            'oid': str,
            'semantic': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'physical_default_value': 'physical_default_value',
            'dop_base_ref': 'dop_base_ref',
            'oid': 'oid',
            'semantic': 'semantic',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._physical_default_value = physical_default_value
        self._dop_base_ref = dop_base_ref
        self._oid = oid
        self._semantic = semantic
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'InputParam':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InputParam of this InputParam.  # noqa: E501
        :rtype: InputParam
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this InputParam.


        :return: The short_name of this InputParam.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this InputParam.


        :param short_name: The short_name of this InputParam.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this InputParam.


        :return: The long_name of this InputParam.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this InputParam.


        :param long_name: The long_name of this InputParam.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this InputParam.


        :return: The description of this InputParam.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this InputParam.


        :param description: The description of this InputParam.
        :type description: Description
        """

        self._description = description

    @property
    def physical_default_value(self) -> str:
        """Gets the physical_default_value of this InputParam.


        :return: The physical_default_value of this InputParam.
        :rtype: str
        """
        return self._physical_default_value

    @physical_default_value.setter
    def physical_default_value(self, physical_default_value: str):
        """Sets the physical_default_value of this InputParam.


        :param physical_default_value: The physical_default_value of this InputParam.
        :type physical_default_value: str
        """

        self._physical_default_value = physical_default_value

    @property
    def dop_base_ref(self) -> OdxLinkRef:
        """Gets the dop_base_ref of this InputParam.


        :return: The dop_base_ref of this InputParam.
        :rtype: OdxLinkRef
        """
        return self._dop_base_ref

    @dop_base_ref.setter
    def dop_base_ref(self, dop_base_ref: OdxLinkRef):
        """Sets the dop_base_ref of this InputParam.


        :param dop_base_ref: The dop_base_ref of this InputParam.
        :type dop_base_ref: OdxLinkRef
        """

        self._dop_base_ref = dop_base_ref

    @property
    def oid(self) -> str:
        """Gets the oid of this InputParam.


        :return: The oid of this InputParam.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this InputParam.


        :param oid: The oid of this InputParam.
        :type oid: str
        """

        self._oid = oid

    @property
    def semantic(self) -> str:
        """Gets the semantic of this InputParam.


        :return: The semantic of this InputParam.
        :rtype: str
        """
        return self._semantic

    @semantic.setter
    def semantic(self, semantic: str):
        """Sets the semantic of this InputParam.


        :param semantic: The semantic of this InputParam.
        :type semantic: str
        """

        self._semantic = semantic

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this InputParam.


        :return: The perma_id of this InputParam.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this InputParam.


        :param perma_id: The perma_id of this InputParam.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this InputParam.


        :return: The ephemeral_id of this InputParam.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this InputParam.


        :param ephemeral_id: The ephemeral_id of this InputParam.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this InputParam.


        :return: The class_name of this InputParam.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this InputParam.


        :param class_name: The class_name of this InputParam.
        :type class_name: str
        """

        self._class_name = class_name
