# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.dataformat import Dataformat
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.encrypt_compress_method import EncryptCompressMethod
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server import util

from diag_server.openapi_server.models.dataformat import Dataformat  # noqa: E501
from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.encrypt_compress_method import EncryptCompressMethod  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501

class InternFlashdata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, size_length=None, address_length=None, dataformat=None, encrypt_compress_method=None, data=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """InternFlashdata - a model defined in OpenAPI

        :param short_name: The short_name of this InternFlashdata.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this InternFlashdata.  # noqa: E501
        :type long_name: str
        :param description: The description of this InternFlashdata.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this InternFlashdata.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this InternFlashdata.  # noqa: E501
        :type oid: str
        :param size_length: The size_length of this InternFlashdata.  # noqa: E501
        :type size_length: int
        :param address_length: The address_length of this InternFlashdata.  # noqa: E501
        :type address_length: int
        :param dataformat: The dataformat of this InternFlashdata.  # noqa: E501
        :type dataformat: Dataformat
        :param encrypt_compress_method: The encrypt_compress_method of this InternFlashdata.  # noqa: E501
        :type encrypt_compress_method: EncryptCompressMethod
        :param data: The data of this InternFlashdata.  # noqa: E501
        :type data: str
        :param perma_id: The perma_id of this InternFlashdata.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this InternFlashdata.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this InternFlashdata.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'size_length': int,
            'address_length': int,
            'dataformat': Dataformat,
            'encrypt_compress_method': EncryptCompressMethod,
            'data': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'size_length': 'size_length',
            'address_length': 'address_length',
            'dataformat': 'dataformat',
            'encrypt_compress_method': 'encrypt_compress_method',
            'data': 'data',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._size_length = size_length
        self._address_length = address_length
        self._dataformat = dataformat
        self._encrypt_compress_method = encrypt_compress_method
        self._data = data
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'InternFlashdata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InternFlashdata of this InternFlashdata.  # noqa: E501
        :rtype: InternFlashdata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this InternFlashdata.


        :return: The short_name of this InternFlashdata.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this InternFlashdata.


        :param short_name: The short_name of this InternFlashdata.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this InternFlashdata.


        :return: The long_name of this InternFlashdata.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this InternFlashdata.


        :param long_name: The long_name of this InternFlashdata.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this InternFlashdata.


        :return: The description of this InternFlashdata.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this InternFlashdata.


        :param description: The description of this InternFlashdata.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this InternFlashdata.


        :return: The odx_id of this InternFlashdata.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this InternFlashdata.


        :param odx_id: The odx_id of this InternFlashdata.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this InternFlashdata.


        :return: The oid of this InternFlashdata.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this InternFlashdata.


        :param oid: The oid of this InternFlashdata.
        :type oid: str
        """

        self._oid = oid

    @property
    def size_length(self) -> int:
        """Gets the size_length of this InternFlashdata.


        :return: The size_length of this InternFlashdata.
        :rtype: int
        """
        return self._size_length

    @size_length.setter
    def size_length(self, size_length: int):
        """Sets the size_length of this InternFlashdata.


        :param size_length: The size_length of this InternFlashdata.
        :type size_length: int
        """

        self._size_length = size_length

    @property
    def address_length(self) -> int:
        """Gets the address_length of this InternFlashdata.


        :return: The address_length of this InternFlashdata.
        :rtype: int
        """
        return self._address_length

    @address_length.setter
    def address_length(self, address_length: int):
        """Sets the address_length of this InternFlashdata.


        :param address_length: The address_length of this InternFlashdata.
        :type address_length: int
        """

        self._address_length = address_length

    @property
    def dataformat(self) -> Dataformat:
        """Gets the dataformat of this InternFlashdata.


        :return: The dataformat of this InternFlashdata.
        :rtype: Dataformat
        """
        return self._dataformat

    @dataformat.setter
    def dataformat(self, dataformat: Dataformat):
        """Sets the dataformat of this InternFlashdata.


        :param dataformat: The dataformat of this InternFlashdata.
        :type dataformat: Dataformat
        """

        self._dataformat = dataformat

    @property
    def encrypt_compress_method(self) -> EncryptCompressMethod:
        """Gets the encrypt_compress_method of this InternFlashdata.


        :return: The encrypt_compress_method of this InternFlashdata.
        :rtype: EncryptCompressMethod
        """
        return self._encrypt_compress_method

    @encrypt_compress_method.setter
    def encrypt_compress_method(self, encrypt_compress_method: EncryptCompressMethod):
        """Sets the encrypt_compress_method of this InternFlashdata.


        :param encrypt_compress_method: The encrypt_compress_method of this InternFlashdata.
        :type encrypt_compress_method: EncryptCompressMethod
        """

        self._encrypt_compress_method = encrypt_compress_method

    @property
    def data(self) -> str:
        """Gets the data of this InternFlashdata.


        :return: The data of this InternFlashdata.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this InternFlashdata.


        :param data: The data of this InternFlashdata.
        :type data: str
        """

        self._data = data

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this InternFlashdata.


        :return: The perma_id of this InternFlashdata.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this InternFlashdata.


        :param perma_id: The perma_id of this InternFlashdata.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this InternFlashdata.


        :return: The ephemeral_id of this InternFlashdata.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this InternFlashdata.


        :param ephemeral_id: The ephemeral_id of this InternFlashdata.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this InternFlashdata.


        :return: The class_name of this InternFlashdata.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this InternFlashdata.


        :param class_name: The class_name of this InternFlashdata.
        :type class_name: str
        """

        self._class_name = class_name
