# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server import util


class JsonProblem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type='about:blank', title=None, status=None, detail=None, instance=None, exception=None):  # noqa: E501
        """JsonProblem - a model defined in OpenAPI

        :param type: The type of this JsonProblem.  # noqa: E501
        :type type: str
        :param title: The title of this JsonProblem.  # noqa: E501
        :type title: str
        :param status: The status of this JsonProblem.  # noqa: E501
        :type status: int
        :param detail: The detail of this JsonProblem.  # noqa: E501
        :type detail: str
        :param instance: The instance of this JsonProblem.  # noqa: E501
        :type instance: str
        :param exception: The exception of this JsonProblem.  # noqa: E501
        :type exception: str
        """
        self.openapi_types = {
            'type': str,
            'title': str,
            'status': int,
            'detail': str,
            'instance': str,
            'exception': str
        }

        self.attribute_map = {
            'type': 'type',
            'title': 'title',
            'status': 'status',
            'detail': 'detail',
            'instance': 'instance',
            'exception': 'exception'
        }

        self._type = type
        self._title = title
        self._status = status
        self._detail = detail
        self._instance = instance
        self._exception = exception

    @classmethod
    def from_dict(cls, dikt) -> 'JsonProblem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JsonProblem of this JsonProblem.  # noqa: E501
        :rtype: JsonProblem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this JsonProblem.

        A URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC-9457, it is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.   # noqa: E501

        :return: The type of this JsonProblem.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this JsonProblem.

        A URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC-9457, it is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.   # noqa: E501

        :param type: The type of this JsonProblem.
        :type type: str
        """

        self._type = type

    @property
    def title(self) -> str:
        """Gets the title of this JsonProblem.

        A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.   # noqa: E501

        :return: The title of this JsonProblem.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this JsonProblem.

        A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.   # noqa: E501

        :param title: The title of this JsonProblem.
        :type title: str
        """

        self._title = title

    @property
    def status(self) -> int:
        """Gets the status of this JsonProblem.

        The HTTP status code generated by the origin server for this occurrence of the problem.   # noqa: E501

        :return: The status of this JsonProblem.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this JsonProblem.

        The HTTP status code generated by the origin server for this occurrence of the problem.   # noqa: E501

        :param status: The status of this JsonProblem.
        :type status: int
        """
        if status is not None and status >= 600:  # noqa: E501
            raise ValueError("Invalid value for `status`, must be a value less than `600`")  # noqa: E501
        if status is not None and status < 100:  # noqa: E501
            raise ValueError("Invalid value for `status`, must be a value greater than or equal to `100`")  # noqa: E501

        self._status = status

    @property
    def detail(self) -> str:
        """Gets the detail of this JsonProblem.

        A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.   # noqa: E501

        :return: The detail of this JsonProblem.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail: str):
        """Sets the detail of this JsonProblem.

        A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.   # noqa: E501

        :param detail: The detail of this JsonProblem.
        :type detail: str
        """

        self._detail = detail

    @property
    def instance(self) -> str:
        """Gets the instance of this JsonProblem.

        A URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.   # noqa: E501

        :return: The instance of this JsonProblem.
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance: str):
        """Sets the instance of this JsonProblem.

        A URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.   # noqa: E501

        :param instance: The instance of this JsonProblem.
        :type instance: str
        """

        self._instance = instance

    @property
    def exception(self) -> str:
        """Gets the exception of this JsonProblem.

        An optional underlying technical exception, e.g. a stack trace or something comparable.   # noqa: E501

        :return: The exception of this JsonProblem.
        :rtype: str
        """
        return self._exception

    @exception.setter
    def exception(self, exception: str):
        """Sets the exception of this JsonProblem.

        An optional underlying technical exception, e.g. a stack trace or something comparable.   # noqa: E501

        :param exception: The exception of this JsonProblem.
        :type exception: str
        """

        self._exception = exception
