# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501

class Library(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, code_file=None, encryption=None, syntax=None, revision=None, entrypoint=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """Library - a model defined in OpenAPI

        :param short_name: The short_name of this Library.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this Library.  # noqa: E501
        :type long_name: str
        :param description: The description of this Library.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this Library.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this Library.  # noqa: E501
        :type oid: str
        :param code_file: The code_file of this Library.  # noqa: E501
        :type code_file: str
        :param encryption: The encryption of this Library.  # noqa: E501
        :type encryption: str
        :param syntax: The syntax of this Library.  # noqa: E501
        :type syntax: str
        :param revision: The revision of this Library.  # noqa: E501
        :type revision: str
        :param entrypoint: The entrypoint of this Library.  # noqa: E501
        :type entrypoint: str
        :param perma_id: The perma_id of this Library.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this Library.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this Library.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'code_file': str,
            'encryption': str,
            'syntax': str,
            'revision': str,
            'entrypoint': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'code_file': 'code_file',
            'encryption': 'encryption',
            'syntax': 'syntax',
            'revision': 'revision',
            'entrypoint': 'entrypoint',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._code_file = code_file
        self._encryption = encryption
        self._syntax = syntax
        self._revision = revision
        self._entrypoint = entrypoint
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'Library':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Library of this Library.  # noqa: E501
        :rtype: Library
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this Library.


        :return: The short_name of this Library.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this Library.


        :param short_name: The short_name of this Library.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this Library.


        :return: The long_name of this Library.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this Library.


        :param long_name: The long_name of this Library.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this Library.


        :return: The description of this Library.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this Library.


        :param description: The description of this Library.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this Library.


        :return: The odx_id of this Library.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this Library.


        :param odx_id: The odx_id of this Library.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this Library.


        :return: The oid of this Library.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this Library.


        :param oid: The oid of this Library.
        :type oid: str
        """

        self._oid = oid

    @property
    def code_file(self) -> str:
        """Gets the code_file of this Library.


        :return: The code_file of this Library.
        :rtype: str
        """
        return self._code_file

    @code_file.setter
    def code_file(self, code_file: str):
        """Sets the code_file of this Library.


        :param code_file: The code_file of this Library.
        :type code_file: str
        """

        self._code_file = code_file

    @property
    def encryption(self) -> str:
        """Gets the encryption of this Library.


        :return: The encryption of this Library.
        :rtype: str
        """
        return self._encryption

    @encryption.setter
    def encryption(self, encryption: str):
        """Sets the encryption of this Library.


        :param encryption: The encryption of this Library.
        :type encryption: str
        """

        self._encryption = encryption

    @property
    def syntax(self) -> str:
        """Gets the syntax of this Library.


        :return: The syntax of this Library.
        :rtype: str
        """
        return self._syntax

    @syntax.setter
    def syntax(self, syntax: str):
        """Sets the syntax of this Library.


        :param syntax: The syntax of this Library.
        :type syntax: str
        """

        self._syntax = syntax

    @property
    def revision(self) -> str:
        """Gets the revision of this Library.


        :return: The revision of this Library.
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision: str):
        """Sets the revision of this Library.


        :param revision: The revision of this Library.
        :type revision: str
        """

        self._revision = revision

    @property
    def entrypoint(self) -> str:
        """Gets the entrypoint of this Library.


        :return: The entrypoint of this Library.
        :rtype: str
        """
        return self._entrypoint

    @entrypoint.setter
    def entrypoint(self, entrypoint: str):
        """Sets the entrypoint of this Library.


        :param entrypoint: The entrypoint of this Library.
        :type entrypoint: str
        """

        self._entrypoint = entrypoint

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this Library.


        :return: The perma_id of this Library.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this Library.


        :param perma_id: The perma_id of this Library.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this Library.


        :return: The ephemeral_id of this Library.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this Library.


        :param ephemeral_id: The ephemeral_id of this Library.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this Library.


        :return: The class_name of this Library.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this Library.


        :param class_name: The class_name of this Library.
        :type class_name: str
        """

        self._class_name = class_name
