# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server import util


class MatchingBaseVariantParameter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, expected_value=None, diag_comm_snref=None, out_param_if_snref=None, out_param_if_snpathref=None, use_physical_addressing_raw=None, use_physical_addressing=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """MatchingBaseVariantParameter - a model defined in OpenAPI

        :param expected_value: The expected_value of this MatchingBaseVariantParameter.  # noqa: E501
        :type expected_value: str
        :param diag_comm_snref: The diag_comm_snref of this MatchingBaseVariantParameter.  # noqa: E501
        :type diag_comm_snref: str
        :param out_param_if_snref: The out_param_if_snref of this MatchingBaseVariantParameter.  # noqa: E501
        :type out_param_if_snref: str
        :param out_param_if_snpathref: The out_param_if_snpathref of this MatchingBaseVariantParameter.  # noqa: E501
        :type out_param_if_snpathref: str
        :param use_physical_addressing_raw: The use_physical_addressing_raw of this MatchingBaseVariantParameter.  # noqa: E501
        :type use_physical_addressing_raw: bool
        :param use_physical_addressing: The use_physical_addressing of this MatchingBaseVariantParameter.  # noqa: E501
        :type use_physical_addressing: bool
        :param perma_id: The perma_id of this MatchingBaseVariantParameter.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this MatchingBaseVariantParameter.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this MatchingBaseVariantParameter.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'expected_value': str,
            'diag_comm_snref': str,
            'out_param_if_snref': str,
            'out_param_if_snpathref': str,
            'use_physical_addressing_raw': bool,
            'use_physical_addressing': bool,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'expected_value': 'expected_value',
            'diag_comm_snref': 'diag_comm_snref',
            'out_param_if_snref': 'out_param_if_snref',
            'out_param_if_snpathref': 'out_param_if_snpathref',
            'use_physical_addressing_raw': 'use_physical_addressing_raw',
            'use_physical_addressing': 'use_physical_addressing',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._expected_value = expected_value
        self._diag_comm_snref = diag_comm_snref
        self._out_param_if_snref = out_param_if_snref
        self._out_param_if_snpathref = out_param_if_snpathref
        self._use_physical_addressing_raw = use_physical_addressing_raw
        self._use_physical_addressing = use_physical_addressing
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'MatchingBaseVariantParameter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatchingBaseVariantParameter of this MatchingBaseVariantParameter.  # noqa: E501
        :rtype: MatchingBaseVariantParameter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expected_value(self) -> str:
        """Gets the expected_value of this MatchingBaseVariantParameter.


        :return: The expected_value of this MatchingBaseVariantParameter.
        :rtype: str
        """
        return self._expected_value

    @expected_value.setter
    def expected_value(self, expected_value: str):
        """Sets the expected_value of this MatchingBaseVariantParameter.


        :param expected_value: The expected_value of this MatchingBaseVariantParameter.
        :type expected_value: str
        """

        self._expected_value = expected_value

    @property
    def diag_comm_snref(self) -> str:
        """Gets the diag_comm_snref of this MatchingBaseVariantParameter.


        :return: The diag_comm_snref of this MatchingBaseVariantParameter.
        :rtype: str
        """
        return self._diag_comm_snref

    @diag_comm_snref.setter
    def diag_comm_snref(self, diag_comm_snref: str):
        """Sets the diag_comm_snref of this MatchingBaseVariantParameter.


        :param diag_comm_snref: The diag_comm_snref of this MatchingBaseVariantParameter.
        :type diag_comm_snref: str
        """

        self._diag_comm_snref = diag_comm_snref

    @property
    def out_param_if_snref(self) -> str:
        """Gets the out_param_if_snref of this MatchingBaseVariantParameter.


        :return: The out_param_if_snref of this MatchingBaseVariantParameter.
        :rtype: str
        """
        return self._out_param_if_snref

    @out_param_if_snref.setter
    def out_param_if_snref(self, out_param_if_snref: str):
        """Sets the out_param_if_snref of this MatchingBaseVariantParameter.


        :param out_param_if_snref: The out_param_if_snref of this MatchingBaseVariantParameter.
        :type out_param_if_snref: str
        """

        self._out_param_if_snref = out_param_if_snref

    @property
    def out_param_if_snpathref(self) -> str:
        """Gets the out_param_if_snpathref of this MatchingBaseVariantParameter.


        :return: The out_param_if_snpathref of this MatchingBaseVariantParameter.
        :rtype: str
        """
        return self._out_param_if_snpathref

    @out_param_if_snpathref.setter
    def out_param_if_snpathref(self, out_param_if_snpathref: str):
        """Sets the out_param_if_snpathref of this MatchingBaseVariantParameter.


        :param out_param_if_snpathref: The out_param_if_snpathref of this MatchingBaseVariantParameter.
        :type out_param_if_snpathref: str
        """

        self._out_param_if_snpathref = out_param_if_snpathref

    @property
    def use_physical_addressing_raw(self) -> bool:
        """Gets the use_physical_addressing_raw of this MatchingBaseVariantParameter.


        :return: The use_physical_addressing_raw of this MatchingBaseVariantParameter.
        :rtype: bool
        """
        return self._use_physical_addressing_raw

    @use_physical_addressing_raw.setter
    def use_physical_addressing_raw(self, use_physical_addressing_raw: bool):
        """Sets the use_physical_addressing_raw of this MatchingBaseVariantParameter.


        :param use_physical_addressing_raw: The use_physical_addressing_raw of this MatchingBaseVariantParameter.
        :type use_physical_addressing_raw: bool
        """

        self._use_physical_addressing_raw = use_physical_addressing_raw

    @property
    def use_physical_addressing(self) -> bool:
        """Gets the use_physical_addressing of this MatchingBaseVariantParameter.


        :return: The use_physical_addressing of this MatchingBaseVariantParameter.
        :rtype: bool
        """
        return self._use_physical_addressing

    @use_physical_addressing.setter
    def use_physical_addressing(self, use_physical_addressing: bool):
        """Sets the use_physical_addressing of this MatchingBaseVariantParameter.


        :param use_physical_addressing: The use_physical_addressing of this MatchingBaseVariantParameter.
        :type use_physical_addressing: bool
        """

        self._use_physical_addressing = use_physical_addressing

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this MatchingBaseVariantParameter.


        :return: The perma_id of this MatchingBaseVariantParameter.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this MatchingBaseVariantParameter.


        :param perma_id: The perma_id of this MatchingBaseVariantParameter.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this MatchingBaseVariantParameter.


        :return: The ephemeral_id of this MatchingBaseVariantParameter.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this MatchingBaseVariantParameter.


        :param ephemeral_id: The ephemeral_id of this MatchingBaseVariantParameter.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this MatchingBaseVariantParameter.


        :return: The class_name of this MatchingBaseVariantParameter.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this MatchingBaseVariantParameter.


        :param class_name: The class_name of this MatchingBaseVariantParameter.
        :type class_name: str
        """

        self._class_name = class_name
