# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501

class MatchingRequestParameter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, sdgs=None, semantic=None, oid=None, byte_position=None, bit_position=None, request_byte_position=None, byte_length=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """MatchingRequestParameter - a model defined in OpenAPI

        :param short_name: The short_name of this MatchingRequestParameter.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this MatchingRequestParameter.  # noqa: E501
        :type long_name: str
        :param description: The description of this MatchingRequestParameter.  # noqa: E501
        :type description: Description
        :param sdgs: The sdgs of this MatchingRequestParameter.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param semantic: The semantic of this MatchingRequestParameter.  # noqa: E501
        :type semantic: str
        :param oid: The oid of this MatchingRequestParameter.  # noqa: E501
        :type oid: str
        :param byte_position: The byte_position of this MatchingRequestParameter.  # noqa: E501
        :type byte_position: int
        :param bit_position: The bit_position of this MatchingRequestParameter.  # noqa: E501
        :type bit_position: int
        :param request_byte_position: The request_byte_position of this MatchingRequestParameter.  # noqa: E501
        :type request_byte_position: int
        :param byte_length: The byte_length of this MatchingRequestParameter.  # noqa: E501
        :type byte_length: int
        :param perma_id: The perma_id of this MatchingRequestParameter.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this MatchingRequestParameter.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this MatchingRequestParameter.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'sdgs': List[SpecialDataGroup],
            'semantic': str,
            'oid': str,
            'byte_position': int,
            'bit_position': int,
            'request_byte_position': int,
            'byte_length': int,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'sdgs': 'sdgs',
            'semantic': 'semantic',
            'oid': 'oid',
            'byte_position': 'byte_position',
            'bit_position': 'bit_position',
            'request_byte_position': 'request_byte_position',
            'byte_length': 'byte_length',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._sdgs = sdgs
        self._semantic = semantic
        self._oid = oid
        self._byte_position = byte_position
        self._bit_position = bit_position
        self._request_byte_position = request_byte_position
        self._byte_length = byte_length
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'MatchingRequestParameter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatchingRequestParameter of this MatchingRequestParameter.  # noqa: E501
        :rtype: MatchingRequestParameter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this MatchingRequestParameter.


        :return: The short_name of this MatchingRequestParameter.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this MatchingRequestParameter.


        :param short_name: The short_name of this MatchingRequestParameter.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this MatchingRequestParameter.


        :return: The long_name of this MatchingRequestParameter.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this MatchingRequestParameter.


        :param long_name: The long_name of this MatchingRequestParameter.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this MatchingRequestParameter.


        :return: The description of this MatchingRequestParameter.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this MatchingRequestParameter.


        :param description: The description of this MatchingRequestParameter.
        :type description: Description
        """

        self._description = description

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this MatchingRequestParameter.


        :return: The sdgs of this MatchingRequestParameter.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this MatchingRequestParameter.


        :param sdgs: The sdgs of this MatchingRequestParameter.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def semantic(self) -> str:
        """Gets the semantic of this MatchingRequestParameter.


        :return: The semantic of this MatchingRequestParameter.
        :rtype: str
        """
        return self._semantic

    @semantic.setter
    def semantic(self, semantic: str):
        """Sets the semantic of this MatchingRequestParameter.


        :param semantic: The semantic of this MatchingRequestParameter.
        :type semantic: str
        """

        self._semantic = semantic

    @property
    def oid(self) -> str:
        """Gets the oid of this MatchingRequestParameter.


        :return: The oid of this MatchingRequestParameter.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this MatchingRequestParameter.


        :param oid: The oid of this MatchingRequestParameter.
        :type oid: str
        """

        self._oid = oid

    @property
    def byte_position(self) -> int:
        """Gets the byte_position of this MatchingRequestParameter.


        :return: The byte_position of this MatchingRequestParameter.
        :rtype: int
        """
        return self._byte_position

    @byte_position.setter
    def byte_position(self, byte_position: int):
        """Sets the byte_position of this MatchingRequestParameter.


        :param byte_position: The byte_position of this MatchingRequestParameter.
        :type byte_position: int
        """

        self._byte_position = byte_position

    @property
    def bit_position(self) -> int:
        """Gets the bit_position of this MatchingRequestParameter.


        :return: The bit_position of this MatchingRequestParameter.
        :rtype: int
        """
        return self._bit_position

    @bit_position.setter
    def bit_position(self, bit_position: int):
        """Sets the bit_position of this MatchingRequestParameter.


        :param bit_position: The bit_position of this MatchingRequestParameter.
        :type bit_position: int
        """

        self._bit_position = bit_position

    @property
    def request_byte_position(self) -> int:
        """Gets the request_byte_position of this MatchingRequestParameter.


        :return: The request_byte_position of this MatchingRequestParameter.
        :rtype: int
        """
        return self._request_byte_position

    @request_byte_position.setter
    def request_byte_position(self, request_byte_position: int):
        """Sets the request_byte_position of this MatchingRequestParameter.


        :param request_byte_position: The request_byte_position of this MatchingRequestParameter.
        :type request_byte_position: int
        """

        self._request_byte_position = request_byte_position

    @property
    def byte_length(self) -> int:
        """Gets the byte_length of this MatchingRequestParameter.


        :return: The byte_length of this MatchingRequestParameter.
        :rtype: int
        """
        return self._byte_length

    @byte_length.setter
    def byte_length(self, byte_length: int):
        """Sets the byte_length of this MatchingRequestParameter.


        :param byte_length: The byte_length of this MatchingRequestParameter.
        :type byte_length: int
        """

        self._byte_length = byte_length

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this MatchingRequestParameter.


        :return: The perma_id of this MatchingRequestParameter.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this MatchingRequestParameter.


        :param perma_id: The perma_id of this MatchingRequestParameter.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this MatchingRequestParameter.


        :return: The ephemeral_id of this MatchingRequestParameter.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this MatchingRequestParameter.


        :param ephemeral_id: The ephemeral_id of this MatchingRequestParameter.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this MatchingRequestParameter.


        :return: The class_name of this MatchingRequestParameter.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this MatchingRequestParameter.


        :param class_name: The class_name of this MatchingRequestParameter.
        :type class_name: str
        """

        self._class_name = class_name
