# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.diag_comm import DiagComm
from diag_server.openapi_server.models.multiple_ecu_job import MultipleEcuJob
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server import util

from diag_server.openapi_server.models.diag_comm import DiagComm  # noqa: E501
from diag_server.openapi_server.models.multiple_ecu_job import MultipleEcuJob  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501

class MatchingComponentResolved(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, expected_value=None, out_param_if_snref=None, out_param_if_snpathref=None, multiple_ecu_job_ref=None, multiple_ecu_job=None, diag_comm_ref=None, diag_comm=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """MatchingComponentResolved - a model defined in OpenAPI

        :param expected_value: The expected_value of this MatchingComponentResolved.  # noqa: E501
        :type expected_value: str
        :param out_param_if_snref: The out_param_if_snref of this MatchingComponentResolved.  # noqa: E501
        :type out_param_if_snref: str
        :param out_param_if_snpathref: The out_param_if_snpathref of this MatchingComponentResolved.  # noqa: E501
        :type out_param_if_snpathref: str
        :param multiple_ecu_job_ref: The multiple_ecu_job_ref of this MatchingComponentResolved.  # noqa: E501
        :type multiple_ecu_job_ref: OdxLinkRef
        :param multiple_ecu_job: The multiple_ecu_job of this MatchingComponentResolved.  # noqa: E501
        :type multiple_ecu_job: MultipleEcuJob
        :param diag_comm_ref: The diag_comm_ref of this MatchingComponentResolved.  # noqa: E501
        :type diag_comm_ref: OdxLinkRef
        :param diag_comm: The diag_comm of this MatchingComponentResolved.  # noqa: E501
        :type diag_comm: DiagComm
        :param perma_id: The perma_id of this MatchingComponentResolved.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this MatchingComponentResolved.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this MatchingComponentResolved.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'expected_value': str,
            'out_param_if_snref': str,
            'out_param_if_snpathref': str,
            'multiple_ecu_job_ref': OdxLinkRef,
            'multiple_ecu_job': MultipleEcuJob,
            'diag_comm_ref': OdxLinkRef,
            'diag_comm': DiagComm,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'expected_value': 'expected_value',
            'out_param_if_snref': 'out_param_if_snref',
            'out_param_if_snpathref': 'out_param_if_snpathref',
            'multiple_ecu_job_ref': 'multiple_ecu_job_ref',
            'multiple_ecu_job': 'multiple_ecu_job',
            'diag_comm_ref': 'diag_comm_ref',
            'diag_comm': 'diag_comm',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._expected_value = expected_value
        self._out_param_if_snref = out_param_if_snref
        self._out_param_if_snpathref = out_param_if_snpathref
        self._multiple_ecu_job_ref = multiple_ecu_job_ref
        self._multiple_ecu_job = multiple_ecu_job
        self._diag_comm_ref = diag_comm_ref
        self._diag_comm = diag_comm
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'MatchingComponentResolved':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatchingComponentResolved of this MatchingComponentResolved.  # noqa: E501
        :rtype: MatchingComponentResolved
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expected_value(self) -> str:
        """Gets the expected_value of this MatchingComponentResolved.


        :return: The expected_value of this MatchingComponentResolved.
        :rtype: str
        """
        return self._expected_value

    @expected_value.setter
    def expected_value(self, expected_value: str):
        """Sets the expected_value of this MatchingComponentResolved.


        :param expected_value: The expected_value of this MatchingComponentResolved.
        :type expected_value: str
        """

        self._expected_value = expected_value

    @property
    def out_param_if_snref(self) -> str:
        """Gets the out_param_if_snref of this MatchingComponentResolved.


        :return: The out_param_if_snref of this MatchingComponentResolved.
        :rtype: str
        """
        return self._out_param_if_snref

    @out_param_if_snref.setter
    def out_param_if_snref(self, out_param_if_snref: str):
        """Sets the out_param_if_snref of this MatchingComponentResolved.


        :param out_param_if_snref: The out_param_if_snref of this MatchingComponentResolved.
        :type out_param_if_snref: str
        """

        self._out_param_if_snref = out_param_if_snref

    @property
    def out_param_if_snpathref(self) -> str:
        """Gets the out_param_if_snpathref of this MatchingComponentResolved.


        :return: The out_param_if_snpathref of this MatchingComponentResolved.
        :rtype: str
        """
        return self._out_param_if_snpathref

    @out_param_if_snpathref.setter
    def out_param_if_snpathref(self, out_param_if_snpathref: str):
        """Sets the out_param_if_snpathref of this MatchingComponentResolved.


        :param out_param_if_snpathref: The out_param_if_snpathref of this MatchingComponentResolved.
        :type out_param_if_snpathref: str
        """

        self._out_param_if_snpathref = out_param_if_snpathref

    @property
    def multiple_ecu_job_ref(self) -> OdxLinkRef:
        """Gets the multiple_ecu_job_ref of this MatchingComponentResolved.


        :return: The multiple_ecu_job_ref of this MatchingComponentResolved.
        :rtype: OdxLinkRef
        """
        return self._multiple_ecu_job_ref

    @multiple_ecu_job_ref.setter
    def multiple_ecu_job_ref(self, multiple_ecu_job_ref: OdxLinkRef):
        """Sets the multiple_ecu_job_ref of this MatchingComponentResolved.


        :param multiple_ecu_job_ref: The multiple_ecu_job_ref of this MatchingComponentResolved.
        :type multiple_ecu_job_ref: OdxLinkRef
        """

        self._multiple_ecu_job_ref = multiple_ecu_job_ref

    @property
    def multiple_ecu_job(self) -> MultipleEcuJob:
        """Gets the multiple_ecu_job of this MatchingComponentResolved.


        :return: The multiple_ecu_job of this MatchingComponentResolved.
        :rtype: MultipleEcuJob
        """
        return self._multiple_ecu_job

    @multiple_ecu_job.setter
    def multiple_ecu_job(self, multiple_ecu_job: MultipleEcuJob):
        """Sets the multiple_ecu_job of this MatchingComponentResolved.


        :param multiple_ecu_job: The multiple_ecu_job of this MatchingComponentResolved.
        :type multiple_ecu_job: MultipleEcuJob
        """

        self._multiple_ecu_job = multiple_ecu_job

    @property
    def diag_comm_ref(self) -> OdxLinkRef:
        """Gets the diag_comm_ref of this MatchingComponentResolved.


        :return: The diag_comm_ref of this MatchingComponentResolved.
        :rtype: OdxLinkRef
        """
        return self._diag_comm_ref

    @diag_comm_ref.setter
    def diag_comm_ref(self, diag_comm_ref: OdxLinkRef):
        """Sets the diag_comm_ref of this MatchingComponentResolved.


        :param diag_comm_ref: The diag_comm_ref of this MatchingComponentResolved.
        :type diag_comm_ref: OdxLinkRef
        """

        self._diag_comm_ref = diag_comm_ref

    @property
    def diag_comm(self) -> DiagComm:
        """Gets the diag_comm of this MatchingComponentResolved.


        :return: The diag_comm of this MatchingComponentResolved.
        :rtype: DiagComm
        """
        return self._diag_comm

    @diag_comm.setter
    def diag_comm(self, diag_comm: DiagComm):
        """Sets the diag_comm of this MatchingComponentResolved.


        :param diag_comm: The diag_comm of this MatchingComponentResolved.
        :type diag_comm: DiagComm
        """

        self._diag_comm = diag_comm

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this MatchingComponentResolved.


        :return: The perma_id of this MatchingComponentResolved.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this MatchingComponentResolved.


        :param perma_id: The perma_id of this MatchingComponentResolved.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this MatchingComponentResolved.


        :return: The ephemeral_id of this MatchingComponentResolved.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this MatchingComponentResolved.


        :param ephemeral_id: The ephemeral_id of this MatchingComponentResolved.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this MatchingComponentResolved.


        :return: The class_name of this MatchingComponentResolved.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this MatchingComponentResolved.


        :param class_name: The class_name of this MatchingComponentResolved.
        :type class_name: str
        """

        self._class_name = class_name
