# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server import util

from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501

class MultiplexerSwitchKey(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, byte_position=None, bit_position=None, dop_ref=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """MultiplexerSwitchKey - a model defined in OpenAPI

        :param byte_position: The byte_position of this MultiplexerSwitchKey.  # noqa: E501
        :type byte_position: int
        :param bit_position: The bit_position of this MultiplexerSwitchKey.  # noqa: E501
        :type bit_position: int
        :param dop_ref: The dop_ref of this MultiplexerSwitchKey.  # noqa: E501
        :type dop_ref: OdxLinkRef
        :param perma_id: The perma_id of this MultiplexerSwitchKey.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this MultiplexerSwitchKey.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this MultiplexerSwitchKey.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'byte_position': int,
            'bit_position': int,
            'dop_ref': OdxLinkRef,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'byte_position': 'byte_position',
            'bit_position': 'bit_position',
            'dop_ref': 'dop_ref',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._byte_position = byte_position
        self._bit_position = bit_position
        self._dop_ref = dop_ref
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'MultiplexerSwitchKey':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MultiplexerSwitchKey of this MultiplexerSwitchKey.  # noqa: E501
        :rtype: MultiplexerSwitchKey
        """
        return util.deserialize_model(dikt, cls)

    @property
    def byte_position(self) -> int:
        """Gets the byte_position of this MultiplexerSwitchKey.


        :return: The byte_position of this MultiplexerSwitchKey.
        :rtype: int
        """
        return self._byte_position

    @byte_position.setter
    def byte_position(self, byte_position: int):
        """Sets the byte_position of this MultiplexerSwitchKey.


        :param byte_position: The byte_position of this MultiplexerSwitchKey.
        :type byte_position: int
        """

        self._byte_position = byte_position

    @property
    def bit_position(self) -> int:
        """Gets the bit_position of this MultiplexerSwitchKey.


        :return: The bit_position of this MultiplexerSwitchKey.
        :rtype: int
        """
        return self._bit_position

    @bit_position.setter
    def bit_position(self, bit_position: int):
        """Sets the bit_position of this MultiplexerSwitchKey.


        :param bit_position: The bit_position of this MultiplexerSwitchKey.
        :type bit_position: int
        """

        self._bit_position = bit_position

    @property
    def dop_ref(self) -> OdxLinkRef:
        """Gets the dop_ref of this MultiplexerSwitchKey.


        :return: The dop_ref of this MultiplexerSwitchKey.
        :rtype: OdxLinkRef
        """
        return self._dop_ref

    @dop_ref.setter
    def dop_ref(self, dop_ref: OdxLinkRef):
        """Sets the dop_ref of this MultiplexerSwitchKey.


        :param dop_ref: The dop_ref of this MultiplexerSwitchKey.
        :type dop_ref: OdxLinkRef
        """

        self._dop_ref = dop_ref

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this MultiplexerSwitchKey.


        :return: The perma_id of this MultiplexerSwitchKey.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this MultiplexerSwitchKey.


        :param perma_id: The perma_id of this MultiplexerSwitchKey.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this MultiplexerSwitchKey.


        :return: The ephemeral_id of this MultiplexerSwitchKey.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this MultiplexerSwitchKey.


        :param ephemeral_id: The ephemeral_id of this MultiplexerSwitchKey.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this MultiplexerSwitchKey.


        :return: The class_name of this MultiplexerSwitchKey.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this MultiplexerSwitchKey.


        :param class_name: The class_name of this MultiplexerSwitchKey.
        :type class_name: str
        """

        self._class_name = class_name
