# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.admin_data import AdminData
from diag_server.openapi_server.models.audience import Audience
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.input_param import InputParam
from diag_server.openapi_server.models.neg_output_param import NegOutputParam
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server.models.output_param import OutputParam
from diag_server.openapi_server.models.prog_code import ProgCode
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server import util

from diag_server.openapi_server.models.admin_data import AdminData  # noqa: E501
from diag_server.openapi_server.models.audience import Audience  # noqa: E501
from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.input_param import InputParam  # noqa: E501
from diag_server.openapi_server.models.neg_output_param import NegOutputParam  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501
from diag_server.openapi_server.models.output_param import OutputParam  # noqa: E501
from diag_server.openapi_server.models.prog_code import ProgCode  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501

class MultipleEcuJob(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, admin_data=None, sdgs=None, functional_class_refs=None, prog_codes=None, input_params=None, output_params=None, neg_output_params=None, diag_layer_refs=None, audience=None, semantic=None, is_executable_raw=None, is_executable=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """MultipleEcuJob - a model defined in OpenAPI

        :param short_name: The short_name of this MultipleEcuJob.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this MultipleEcuJob.  # noqa: E501
        :type long_name: str
        :param description: The description of this MultipleEcuJob.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this MultipleEcuJob.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this MultipleEcuJob.  # noqa: E501
        :type oid: str
        :param admin_data: The admin_data of this MultipleEcuJob.  # noqa: E501
        :type admin_data: AdminData
        :param sdgs: The sdgs of this MultipleEcuJob.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param functional_class_refs: The functional_class_refs of this MultipleEcuJob.  # noqa: E501
        :type functional_class_refs: List[OdxLinkRef]
        :param prog_codes: The prog_codes of this MultipleEcuJob.  # noqa: E501
        :type prog_codes: List[ProgCode]
        :param input_params: The input_params of this MultipleEcuJob.  # noqa: E501
        :type input_params: List[InputParam]
        :param output_params: The output_params of this MultipleEcuJob.  # noqa: E501
        :type output_params: List[OutputParam]
        :param neg_output_params: The neg_output_params of this MultipleEcuJob.  # noqa: E501
        :type neg_output_params: List[NegOutputParam]
        :param diag_layer_refs: The diag_layer_refs of this MultipleEcuJob.  # noqa: E501
        :type diag_layer_refs: List[OdxLinkRef]
        :param audience: The audience of this MultipleEcuJob.  # noqa: E501
        :type audience: Audience
        :param semantic: The semantic of this MultipleEcuJob.  # noqa: E501
        :type semantic: str
        :param is_executable_raw: The is_executable_raw of this MultipleEcuJob.  # noqa: E501
        :type is_executable_raw: bool
        :param is_executable: The is_executable of this MultipleEcuJob.  # noqa: E501
        :type is_executable: bool
        :param perma_id: The perma_id of this MultipleEcuJob.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this MultipleEcuJob.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this MultipleEcuJob.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'admin_data': AdminData,
            'sdgs': List[SpecialDataGroup],
            'functional_class_refs': List[OdxLinkRef],
            'prog_codes': List[ProgCode],
            'input_params': List[InputParam],
            'output_params': List[OutputParam],
            'neg_output_params': List[NegOutputParam],
            'diag_layer_refs': List[OdxLinkRef],
            'audience': Audience,
            'semantic': str,
            'is_executable_raw': bool,
            'is_executable': bool,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'admin_data': 'admin_data',
            'sdgs': 'sdgs',
            'functional_class_refs': 'functional_class_refs',
            'prog_codes': 'prog_codes',
            'input_params': 'input_params',
            'output_params': 'output_params',
            'neg_output_params': 'neg_output_params',
            'diag_layer_refs': 'diag_layer_refs',
            'audience': 'audience',
            'semantic': 'semantic',
            'is_executable_raw': 'is_executable_raw',
            'is_executable': 'is_executable',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._admin_data = admin_data
        self._sdgs = sdgs
        self._functional_class_refs = functional_class_refs
        self._prog_codes = prog_codes
        self._input_params = input_params
        self._output_params = output_params
        self._neg_output_params = neg_output_params
        self._diag_layer_refs = diag_layer_refs
        self._audience = audience
        self._semantic = semantic
        self._is_executable_raw = is_executable_raw
        self._is_executable = is_executable
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'MultipleEcuJob':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MultipleEcuJob of this MultipleEcuJob.  # noqa: E501
        :rtype: MultipleEcuJob
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this MultipleEcuJob.


        :return: The short_name of this MultipleEcuJob.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this MultipleEcuJob.


        :param short_name: The short_name of this MultipleEcuJob.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this MultipleEcuJob.


        :return: The long_name of this MultipleEcuJob.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this MultipleEcuJob.


        :param long_name: The long_name of this MultipleEcuJob.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this MultipleEcuJob.


        :return: The description of this MultipleEcuJob.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this MultipleEcuJob.


        :param description: The description of this MultipleEcuJob.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this MultipleEcuJob.


        :return: The odx_id of this MultipleEcuJob.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this MultipleEcuJob.


        :param odx_id: The odx_id of this MultipleEcuJob.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this MultipleEcuJob.


        :return: The oid of this MultipleEcuJob.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this MultipleEcuJob.


        :param oid: The oid of this MultipleEcuJob.
        :type oid: str
        """

        self._oid = oid

    @property
    def admin_data(self) -> AdminData:
        """Gets the admin_data of this MultipleEcuJob.


        :return: The admin_data of this MultipleEcuJob.
        :rtype: AdminData
        """
        return self._admin_data

    @admin_data.setter
    def admin_data(self, admin_data: AdminData):
        """Sets the admin_data of this MultipleEcuJob.


        :param admin_data: The admin_data of this MultipleEcuJob.
        :type admin_data: AdminData
        """

        self._admin_data = admin_data

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this MultipleEcuJob.


        :return: The sdgs of this MultipleEcuJob.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this MultipleEcuJob.


        :param sdgs: The sdgs of this MultipleEcuJob.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def functional_class_refs(self) -> List[OdxLinkRef]:
        """Gets the functional_class_refs of this MultipleEcuJob.


        :return: The functional_class_refs of this MultipleEcuJob.
        :rtype: List[OdxLinkRef]
        """
        return self._functional_class_refs

    @functional_class_refs.setter
    def functional_class_refs(self, functional_class_refs: List[OdxLinkRef]):
        """Sets the functional_class_refs of this MultipleEcuJob.


        :param functional_class_refs: The functional_class_refs of this MultipleEcuJob.
        :type functional_class_refs: List[OdxLinkRef]
        """

        self._functional_class_refs = functional_class_refs

    @property
    def prog_codes(self) -> List[ProgCode]:
        """Gets the prog_codes of this MultipleEcuJob.


        :return: The prog_codes of this MultipleEcuJob.
        :rtype: List[ProgCode]
        """
        return self._prog_codes

    @prog_codes.setter
    def prog_codes(self, prog_codes: List[ProgCode]):
        """Sets the prog_codes of this MultipleEcuJob.


        :param prog_codes: The prog_codes of this MultipleEcuJob.
        :type prog_codes: List[ProgCode]
        """

        self._prog_codes = prog_codes

    @property
    def input_params(self) -> List[InputParam]:
        """Gets the input_params of this MultipleEcuJob.


        :return: The input_params of this MultipleEcuJob.
        :rtype: List[InputParam]
        """
        return self._input_params

    @input_params.setter
    def input_params(self, input_params: List[InputParam]):
        """Sets the input_params of this MultipleEcuJob.


        :param input_params: The input_params of this MultipleEcuJob.
        :type input_params: List[InputParam]
        """

        self._input_params = input_params

    @property
    def output_params(self) -> List[OutputParam]:
        """Gets the output_params of this MultipleEcuJob.


        :return: The output_params of this MultipleEcuJob.
        :rtype: List[OutputParam]
        """
        return self._output_params

    @output_params.setter
    def output_params(self, output_params: List[OutputParam]):
        """Sets the output_params of this MultipleEcuJob.


        :param output_params: The output_params of this MultipleEcuJob.
        :type output_params: List[OutputParam]
        """

        self._output_params = output_params

    @property
    def neg_output_params(self) -> List[NegOutputParam]:
        """Gets the neg_output_params of this MultipleEcuJob.


        :return: The neg_output_params of this MultipleEcuJob.
        :rtype: List[NegOutputParam]
        """
        return self._neg_output_params

    @neg_output_params.setter
    def neg_output_params(self, neg_output_params: List[NegOutputParam]):
        """Sets the neg_output_params of this MultipleEcuJob.


        :param neg_output_params: The neg_output_params of this MultipleEcuJob.
        :type neg_output_params: List[NegOutputParam]
        """

        self._neg_output_params = neg_output_params

    @property
    def diag_layer_refs(self) -> List[OdxLinkRef]:
        """Gets the diag_layer_refs of this MultipleEcuJob.


        :return: The diag_layer_refs of this MultipleEcuJob.
        :rtype: List[OdxLinkRef]
        """
        return self._diag_layer_refs

    @diag_layer_refs.setter
    def diag_layer_refs(self, diag_layer_refs: List[OdxLinkRef]):
        """Sets the diag_layer_refs of this MultipleEcuJob.


        :param diag_layer_refs: The diag_layer_refs of this MultipleEcuJob.
        :type diag_layer_refs: List[OdxLinkRef]
        """

        self._diag_layer_refs = diag_layer_refs

    @property
    def audience(self) -> Audience:
        """Gets the audience of this MultipleEcuJob.


        :return: The audience of this MultipleEcuJob.
        :rtype: Audience
        """
        return self._audience

    @audience.setter
    def audience(self, audience: Audience):
        """Sets the audience of this MultipleEcuJob.


        :param audience: The audience of this MultipleEcuJob.
        :type audience: Audience
        """

        self._audience = audience

    @property
    def semantic(self) -> str:
        """Gets the semantic of this MultipleEcuJob.


        :return: The semantic of this MultipleEcuJob.
        :rtype: str
        """
        return self._semantic

    @semantic.setter
    def semantic(self, semantic: str):
        """Sets the semantic of this MultipleEcuJob.


        :param semantic: The semantic of this MultipleEcuJob.
        :type semantic: str
        """

        self._semantic = semantic

    @property
    def is_executable_raw(self) -> bool:
        """Gets the is_executable_raw of this MultipleEcuJob.


        :return: The is_executable_raw of this MultipleEcuJob.
        :rtype: bool
        """
        return self._is_executable_raw

    @is_executable_raw.setter
    def is_executable_raw(self, is_executable_raw: bool):
        """Sets the is_executable_raw of this MultipleEcuJob.


        :param is_executable_raw: The is_executable_raw of this MultipleEcuJob.
        :type is_executable_raw: bool
        """

        self._is_executable_raw = is_executable_raw

    @property
    def is_executable(self) -> bool:
        """Gets the is_executable of this MultipleEcuJob.


        :return: The is_executable of this MultipleEcuJob.
        :rtype: bool
        """
        return self._is_executable

    @is_executable.setter
    def is_executable(self, is_executable: bool):
        """Sets the is_executable of this MultipleEcuJob.


        :param is_executable: The is_executable of this MultipleEcuJob.
        :type is_executable: bool
        """

        self._is_executable = is_executable

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this MultipleEcuJob.


        :return: The perma_id of this MultipleEcuJob.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this MultipleEcuJob.


        :param perma_id: The perma_id of this MultipleEcuJob.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this MultipleEcuJob.


        :return: The ephemeral_id of this MultipleEcuJob.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this MultipleEcuJob.


        :param ephemeral_id: The ephemeral_id of this MultipleEcuJob.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this MultipleEcuJob.


        :return: The class_name of this MultipleEcuJob.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this MultipleEcuJob.


        :param class_name: The class_name of this MultipleEcuJob.
        :type class_name: str
        """

        self._class_name = class_name
