# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.odx_doc_fragment import OdxDocFragment
from diag_server.openapi_server import util

from diag_server.openapi_server.models.odx_doc_fragment import OdxDocFragment  # noqa: E501

class OdxLinkId(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, local_id=None, doc_fragments=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """OdxLinkId - a model defined in OpenAPI

        :param local_id: The local_id of this OdxLinkId.  # noqa: E501
        :type local_id: str
        :param doc_fragments: The doc_fragments of this OdxLinkId.  # noqa: E501
        :type doc_fragments: List[OdxDocFragment]
        :param perma_id: The perma_id of this OdxLinkId.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this OdxLinkId.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this OdxLinkId.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'local_id': str,
            'doc_fragments': List[OdxDocFragment],
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'local_id': 'local_id',
            'doc_fragments': 'doc_fragments',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._local_id = local_id
        self._doc_fragments = doc_fragments
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'OdxLinkId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OdxLinkId of this OdxLinkId.  # noqa: E501
        :rtype: OdxLinkId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def local_id(self) -> str:
        """Gets the local_id of this OdxLinkId.


        :return: The local_id of this OdxLinkId.
        :rtype: str
        """
        return self._local_id

    @local_id.setter
    def local_id(self, local_id: str):
        """Sets the local_id of this OdxLinkId.


        :param local_id: The local_id of this OdxLinkId.
        :type local_id: str
        """

        self._local_id = local_id

    @property
    def doc_fragments(self) -> List[OdxDocFragment]:
        """Gets the doc_fragments of this OdxLinkId.


        :return: The doc_fragments of this OdxLinkId.
        :rtype: List[OdxDocFragment]
        """
        return self._doc_fragments

    @doc_fragments.setter
    def doc_fragments(self, doc_fragments: List[OdxDocFragment]):
        """Sets the doc_fragments of this OdxLinkId.


        :param doc_fragments: The doc_fragments of this OdxLinkId.
        :type doc_fragments: List[OdxDocFragment]
        """

        self._doc_fragments = doc_fragments

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this OdxLinkId.


        :return: The perma_id of this OdxLinkId.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this OdxLinkId.


        :param perma_id: The perma_id of this OdxLinkId.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this OdxLinkId.


        :return: The ephemeral_id of this OdxLinkId.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this OdxLinkId.


        :param ephemeral_id: The ephemeral_id of this OdxLinkId.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this OdxLinkId.


        :return: The class_name of this OdxLinkId.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this OdxLinkId.


        :param class_name: The class_name of this OdxLinkId.
        :type class_name: str
        """

        self._class_name = class_name
