# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.doc_type import DocType
from diag_server.openapi_server import util

from diag_server.openapi_server.models.doc_type import DocType  # noqa: E501

class OdxDocFragment(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, doc_name=None, doc_type=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """OdxDocFragment - a model defined in OpenAPI

        :param doc_name: The doc_name of this OdxDocFragment.  # noqa: E501
        :type doc_name: str
        :param doc_type: The doc_type of this OdxDocFragment.  # noqa: E501
        :type doc_type: DocType
        :param perma_id: The perma_id of this OdxDocFragment.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this OdxDocFragment.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this OdxDocFragment.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'doc_name': str,
            'doc_type': DocType,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'doc_name': 'doc_name',
            'doc_type': 'doc_type',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._doc_name = doc_name
        self._doc_type = doc_type
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'OdxDocFragment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OdxDocFragment of this OdxDocFragment.  # noqa: E501
        :rtype: OdxDocFragment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def doc_name(self) -> str:
        """Gets the doc_name of this OdxDocFragment.


        :return: The doc_name of this OdxDocFragment.
        :rtype: str
        """
        return self._doc_name

    @doc_name.setter
    def doc_name(self, doc_name: str):
        """Sets the doc_name of this OdxDocFragment.


        :param doc_name: The doc_name of this OdxDocFragment.
        :type doc_name: str
        """

        self._doc_name = doc_name

    @property
    def doc_type(self) -> DocType:
        """Gets the doc_type of this OdxDocFragment.


        :return: The doc_type of this OdxDocFragment.
        :rtype: DocType
        """
        return self._doc_type

    @doc_type.setter
    def doc_type(self, doc_type: DocType):
        """Sets the doc_type of this OdxDocFragment.


        :param doc_type: The doc_type of this OdxDocFragment.
        :type doc_type: DocType
        """

        self._doc_type = doc_type

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this OdxDocFragment.


        :return: The perma_id of this OdxDocFragment.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this OdxDocFragment.


        :param perma_id: The perma_id of this OdxDocFragment.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this OdxDocFragment.


        :return: The ephemeral_id of this OdxDocFragment.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this OdxDocFragment.


        :param ephemeral_id: The ephemeral_id of this OdxDocFragment.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this OdxDocFragment.


        :return: The class_name of this OdxDocFragment.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this OdxDocFragment.


        :param class_name: The class_name of this OdxDocFragment.
        :type class_name: str
        """

        self._class_name = class_name
