# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.data_type import DataType
from diag_server.openapi_server.models.encoding import Encoding
from diag_server.openapi_server.models.length_key_parameter_resolved import LengthKeyParameterResolved
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server import util

from diag_server.openapi_server.models.data_type import DataType  # noqa: E501
from diag_server.openapi_server.models.encoding import Encoding  # noqa: E501
from diag_server.openapi_server.models.length_key_parameter_resolved import LengthKeyParameterResolved  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501

class ParamLengthInfoTypeResolved(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, base_type_encoding=None, base_data_type=None, is_highlow_byte_order_raw=None, is_highlow_byte_order=None, length_key_ref=None, length_key=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """ParamLengthInfoTypeResolved - a model defined in OpenAPI

        :param base_type_encoding: The base_type_encoding of this ParamLengthInfoTypeResolved.  # noqa: E501
        :type base_type_encoding: Encoding
        :param base_data_type: The base_data_type of this ParamLengthInfoTypeResolved.  # noqa: E501
        :type base_data_type: DataType
        :param is_highlow_byte_order_raw: The is_highlow_byte_order_raw of this ParamLengthInfoTypeResolved.  # noqa: E501
        :type is_highlow_byte_order_raw: bool
        :param is_highlow_byte_order: The is_highlow_byte_order of this ParamLengthInfoTypeResolved.  # noqa: E501
        :type is_highlow_byte_order: bool
        :param length_key_ref: The length_key_ref of this ParamLengthInfoTypeResolved.  # noqa: E501
        :type length_key_ref: OdxLinkRef
        :param length_key: The length_key of this ParamLengthInfoTypeResolved.  # noqa: E501
        :type length_key: LengthKeyParameterResolved
        :param perma_id: The perma_id of this ParamLengthInfoTypeResolved.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this ParamLengthInfoTypeResolved.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this ParamLengthInfoTypeResolved.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'base_type_encoding': Encoding,
            'base_data_type': DataType,
            'is_highlow_byte_order_raw': bool,
            'is_highlow_byte_order': bool,
            'length_key_ref': OdxLinkRef,
            'length_key': LengthKeyParameterResolved,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'base_type_encoding': 'base_type_encoding',
            'base_data_type': 'base_data_type',
            'is_highlow_byte_order_raw': 'is_highlow_byte_order_raw',
            'is_highlow_byte_order': 'is_highlow_byte_order',
            'length_key_ref': 'length_key_ref',
            'length_key': 'length_key',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._base_type_encoding = base_type_encoding
        self._base_data_type = base_data_type
        self._is_highlow_byte_order_raw = is_highlow_byte_order_raw
        self._is_highlow_byte_order = is_highlow_byte_order
        self._length_key_ref = length_key_ref
        self._length_key = length_key
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'ParamLengthInfoTypeResolved':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParamLengthInfoTypeResolved of this ParamLengthInfoTypeResolved.  # noqa: E501
        :rtype: ParamLengthInfoTypeResolved
        """
        return util.deserialize_model(dikt, cls)

    @property
    def base_type_encoding(self) -> Encoding:
        """Gets the base_type_encoding of this ParamLengthInfoTypeResolved.


        :return: The base_type_encoding of this ParamLengthInfoTypeResolved.
        :rtype: Encoding
        """
        return self._base_type_encoding

    @base_type_encoding.setter
    def base_type_encoding(self, base_type_encoding: Encoding):
        """Sets the base_type_encoding of this ParamLengthInfoTypeResolved.


        :param base_type_encoding: The base_type_encoding of this ParamLengthInfoTypeResolved.
        :type base_type_encoding: Encoding
        """

        self._base_type_encoding = base_type_encoding

    @property
    def base_data_type(self) -> DataType:
        """Gets the base_data_type of this ParamLengthInfoTypeResolved.


        :return: The base_data_type of this ParamLengthInfoTypeResolved.
        :rtype: DataType
        """
        return self._base_data_type

    @base_data_type.setter
    def base_data_type(self, base_data_type: DataType):
        """Sets the base_data_type of this ParamLengthInfoTypeResolved.


        :param base_data_type: The base_data_type of this ParamLengthInfoTypeResolved.
        :type base_data_type: DataType
        """

        self._base_data_type = base_data_type

    @property
    def is_highlow_byte_order_raw(self) -> bool:
        """Gets the is_highlow_byte_order_raw of this ParamLengthInfoTypeResolved.


        :return: The is_highlow_byte_order_raw of this ParamLengthInfoTypeResolved.
        :rtype: bool
        """
        return self._is_highlow_byte_order_raw

    @is_highlow_byte_order_raw.setter
    def is_highlow_byte_order_raw(self, is_highlow_byte_order_raw: bool):
        """Sets the is_highlow_byte_order_raw of this ParamLengthInfoTypeResolved.


        :param is_highlow_byte_order_raw: The is_highlow_byte_order_raw of this ParamLengthInfoTypeResolved.
        :type is_highlow_byte_order_raw: bool
        """

        self._is_highlow_byte_order_raw = is_highlow_byte_order_raw

    @property
    def is_highlow_byte_order(self) -> bool:
        """Gets the is_highlow_byte_order of this ParamLengthInfoTypeResolved.


        :return: The is_highlow_byte_order of this ParamLengthInfoTypeResolved.
        :rtype: bool
        """
        return self._is_highlow_byte_order

    @is_highlow_byte_order.setter
    def is_highlow_byte_order(self, is_highlow_byte_order: bool):
        """Sets the is_highlow_byte_order of this ParamLengthInfoTypeResolved.


        :param is_highlow_byte_order: The is_highlow_byte_order of this ParamLengthInfoTypeResolved.
        :type is_highlow_byte_order: bool
        """

        self._is_highlow_byte_order = is_highlow_byte_order

    @property
    def length_key_ref(self) -> OdxLinkRef:
        """Gets the length_key_ref of this ParamLengthInfoTypeResolved.


        :return: The length_key_ref of this ParamLengthInfoTypeResolved.
        :rtype: OdxLinkRef
        """
        return self._length_key_ref

    @length_key_ref.setter
    def length_key_ref(self, length_key_ref: OdxLinkRef):
        """Sets the length_key_ref of this ParamLengthInfoTypeResolved.


        :param length_key_ref: The length_key_ref of this ParamLengthInfoTypeResolved.
        :type length_key_ref: OdxLinkRef
        """

        self._length_key_ref = length_key_ref

    @property
    def length_key(self) -> LengthKeyParameterResolved:
        """Gets the length_key of this ParamLengthInfoTypeResolved.


        :return: The length_key of this ParamLengthInfoTypeResolved.
        :rtype: LengthKeyParameterResolved
        """
        return self._length_key

    @length_key.setter
    def length_key(self, length_key: LengthKeyParameterResolved):
        """Sets the length_key of this ParamLengthInfoTypeResolved.


        :param length_key: The length_key of this ParamLengthInfoTypeResolved.
        :type length_key: LengthKeyParameterResolved
        """

        self._length_key = length_key

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this ParamLengthInfoTypeResolved.


        :return: The perma_id of this ParamLengthInfoTypeResolved.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this ParamLengthInfoTypeResolved.


        :param perma_id: The perma_id of this ParamLengthInfoTypeResolved.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this ParamLengthInfoTypeResolved.


        :return: The ephemeral_id of this ParamLengthInfoTypeResolved.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this ParamLengthInfoTypeResolved.


        :param ephemeral_id: The ephemeral_id of this ParamLengthInfoTypeResolved.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this ParamLengthInfoTypeResolved.


        :return: The class_name of this ParamLengthInfoTypeResolved.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this ParamLengthInfoTypeResolved.


        :param class_name: The class_name of this ParamLengthInfoTypeResolved.
        :type class_name: str
        """

        self._class_name = class_name
