# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.data_type import DataType
from diag_server.openapi_server.models.radix import Radix
from diag_server.openapi_server import util

from diag_server.openapi_server.models.data_type import DataType  # noqa: E501
from diag_server.openapi_server.models.radix import Radix  # noqa: E501

class PhysicalType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, precision=None, base_data_type=None, display_radix=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """PhysicalType - a model defined in OpenAPI

        :param precision: The precision of this PhysicalType.  # noqa: E501
        :type precision: int
        :param base_data_type: The base_data_type of this PhysicalType.  # noqa: E501
        :type base_data_type: DataType
        :param display_radix: The display_radix of this PhysicalType.  # noqa: E501
        :type display_radix: Radix
        :param perma_id: The perma_id of this PhysicalType.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this PhysicalType.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this PhysicalType.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'precision': int,
            'base_data_type': DataType,
            'display_radix': Radix,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'precision': 'precision',
            'base_data_type': 'base_data_type',
            'display_radix': 'display_radix',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._precision = precision
        self._base_data_type = base_data_type
        self._display_radix = display_radix
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'PhysicalType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PhysicalType of this PhysicalType.  # noqa: E501
        :rtype: PhysicalType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def precision(self) -> int:
        """Gets the precision of this PhysicalType.


        :return: The precision of this PhysicalType.
        :rtype: int
        """
        return self._precision

    @precision.setter
    def precision(self, precision: int):
        """Sets the precision of this PhysicalType.


        :param precision: The precision of this PhysicalType.
        :type precision: int
        """

        self._precision = precision

    @property
    def base_data_type(self) -> DataType:
        """Gets the base_data_type of this PhysicalType.


        :return: The base_data_type of this PhysicalType.
        :rtype: DataType
        """
        return self._base_data_type

    @base_data_type.setter
    def base_data_type(self, base_data_type: DataType):
        """Sets the base_data_type of this PhysicalType.


        :param base_data_type: The base_data_type of this PhysicalType.
        :type base_data_type: DataType
        """

        self._base_data_type = base_data_type

    @property
    def display_radix(self) -> Radix:
        """Gets the display_radix of this PhysicalType.


        :return: The display_radix of this PhysicalType.
        :rtype: Radix
        """
        return self._display_radix

    @display_radix.setter
    def display_radix(self, display_radix: Radix):
        """Sets the display_radix of this PhysicalType.


        :param display_radix: The display_radix of this PhysicalType.
        :type display_radix: Radix
        """

        self._display_radix = display_radix

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this PhysicalType.


        :return: The perma_id of this PhysicalType.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this PhysicalType.


        :param perma_id: The perma_id of this PhysicalType.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this PhysicalType.


        :return: The ephemeral_id of this PhysicalType.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this PhysicalType.


        :param ephemeral_id: The ephemeral_id of this PhysicalType.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this PhysicalType.


        :return: The class_name of this PhysicalType.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this PhysicalType.


        :param class_name: The class_name of this PhysicalType.
        :type class_name: str
        """

        self._class_name = class_name
