# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501

class ProtStack(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, pdu_protocol_type=None, physical_link_type=None, comparam_subset_refs=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """ProtStack - a model defined in OpenAPI

        :param short_name: The short_name of this ProtStack.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this ProtStack.  # noqa: E501
        :type long_name: str
        :param description: The description of this ProtStack.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this ProtStack.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this ProtStack.  # noqa: E501
        :type oid: str
        :param pdu_protocol_type: The pdu_protocol_type of this ProtStack.  # noqa: E501
        :type pdu_protocol_type: str
        :param physical_link_type: The physical_link_type of this ProtStack.  # noqa: E501
        :type physical_link_type: str
        :param comparam_subset_refs: The comparam_subset_refs of this ProtStack.  # noqa: E501
        :type comparam_subset_refs: List[OdxLinkRef]
        :param perma_id: The perma_id of this ProtStack.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this ProtStack.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this ProtStack.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'pdu_protocol_type': str,
            'physical_link_type': str,
            'comparam_subset_refs': List[OdxLinkRef],
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'pdu_protocol_type': 'pdu_protocol_type',
            'physical_link_type': 'physical_link_type',
            'comparam_subset_refs': 'comparam_subset_refs',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._pdu_protocol_type = pdu_protocol_type
        self._physical_link_type = physical_link_type
        self._comparam_subset_refs = comparam_subset_refs
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'ProtStack':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProtStack of this ProtStack.  # noqa: E501
        :rtype: ProtStack
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this ProtStack.


        :return: The short_name of this ProtStack.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this ProtStack.


        :param short_name: The short_name of this ProtStack.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this ProtStack.


        :return: The long_name of this ProtStack.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this ProtStack.


        :param long_name: The long_name of this ProtStack.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this ProtStack.


        :return: The description of this ProtStack.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this ProtStack.


        :param description: The description of this ProtStack.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this ProtStack.


        :return: The odx_id of this ProtStack.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this ProtStack.


        :param odx_id: The odx_id of this ProtStack.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this ProtStack.


        :return: The oid of this ProtStack.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this ProtStack.


        :param oid: The oid of this ProtStack.
        :type oid: str
        """

        self._oid = oid

    @property
    def pdu_protocol_type(self) -> str:
        """Gets the pdu_protocol_type of this ProtStack.


        :return: The pdu_protocol_type of this ProtStack.
        :rtype: str
        """
        return self._pdu_protocol_type

    @pdu_protocol_type.setter
    def pdu_protocol_type(self, pdu_protocol_type: str):
        """Sets the pdu_protocol_type of this ProtStack.


        :param pdu_protocol_type: The pdu_protocol_type of this ProtStack.
        :type pdu_protocol_type: str
        """

        self._pdu_protocol_type = pdu_protocol_type

    @property
    def physical_link_type(self) -> str:
        """Gets the physical_link_type of this ProtStack.


        :return: The physical_link_type of this ProtStack.
        :rtype: str
        """
        return self._physical_link_type

    @physical_link_type.setter
    def physical_link_type(self, physical_link_type: str):
        """Sets the physical_link_type of this ProtStack.


        :param physical_link_type: The physical_link_type of this ProtStack.
        :type physical_link_type: str
        """

        self._physical_link_type = physical_link_type

    @property
    def comparam_subset_refs(self) -> List[OdxLinkRef]:
        """Gets the comparam_subset_refs of this ProtStack.


        :return: The comparam_subset_refs of this ProtStack.
        :rtype: List[OdxLinkRef]
        """
        return self._comparam_subset_refs

    @comparam_subset_refs.setter
    def comparam_subset_refs(self, comparam_subset_refs: List[OdxLinkRef]):
        """Sets the comparam_subset_refs of this ProtStack.


        :param comparam_subset_refs: The comparam_subset_refs of this ProtStack.
        :type comparam_subset_refs: List[OdxLinkRef]
        """

        self._comparam_subset_refs = comparam_subset_refs

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this ProtStack.


        :return: The perma_id of this ProtStack.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this ProtStack.


        :param perma_id: The perma_id of this ProtStack.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this ProtStack.


        :return: The ephemeral_id of this ProtStack.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this ProtStack.


        :param ephemeral_id: The ephemeral_id of this ProtStack.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this ProtStack.


        :return: The class_name of this ProtStack.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this ProtStack.


        :param class_name: The class_name of this ProtStack.
        :type class_name: str
        """

        self._class_name = class_name
