# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server import util


class ReadParamValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, phys_constant_value=None, in_param_if_snref=None, in_param_if_snpathref=None, semantic=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """ReadParamValue - a model defined in OpenAPI

        :param phys_constant_value: The phys_constant_value of this ReadParamValue.  # noqa: E501
        :type phys_constant_value: str
        :param in_param_if_snref: The in_param_if_snref of this ReadParamValue.  # noqa: E501
        :type in_param_if_snref: str
        :param in_param_if_snpathref: The in_param_if_snpathref of this ReadParamValue.  # noqa: E501
        :type in_param_if_snpathref: str
        :param semantic: The semantic of this ReadParamValue.  # noqa: E501
        :type semantic: str
        :param perma_id: The perma_id of this ReadParamValue.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this ReadParamValue.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this ReadParamValue.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'phys_constant_value': str,
            'in_param_if_snref': str,
            'in_param_if_snpathref': str,
            'semantic': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'phys_constant_value': 'phys_constant_value',
            'in_param_if_snref': 'in_param_if_snref',
            'in_param_if_snpathref': 'in_param_if_snpathref',
            'semantic': 'semantic',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._phys_constant_value = phys_constant_value
        self._in_param_if_snref = in_param_if_snref
        self._in_param_if_snpathref = in_param_if_snpathref
        self._semantic = semantic
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'ReadParamValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReadParamValue of this ReadParamValue.  # noqa: E501
        :rtype: ReadParamValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phys_constant_value(self) -> str:
        """Gets the phys_constant_value of this ReadParamValue.


        :return: The phys_constant_value of this ReadParamValue.
        :rtype: str
        """
        return self._phys_constant_value

    @phys_constant_value.setter
    def phys_constant_value(self, phys_constant_value: str):
        """Sets the phys_constant_value of this ReadParamValue.


        :param phys_constant_value: The phys_constant_value of this ReadParamValue.
        :type phys_constant_value: str
        """

        self._phys_constant_value = phys_constant_value

    @property
    def in_param_if_snref(self) -> str:
        """Gets the in_param_if_snref of this ReadParamValue.


        :return: The in_param_if_snref of this ReadParamValue.
        :rtype: str
        """
        return self._in_param_if_snref

    @in_param_if_snref.setter
    def in_param_if_snref(self, in_param_if_snref: str):
        """Sets the in_param_if_snref of this ReadParamValue.


        :param in_param_if_snref: The in_param_if_snref of this ReadParamValue.
        :type in_param_if_snref: str
        """

        self._in_param_if_snref = in_param_if_snref

    @property
    def in_param_if_snpathref(self) -> str:
        """Gets the in_param_if_snpathref of this ReadParamValue.


        :return: The in_param_if_snpathref of this ReadParamValue.
        :rtype: str
        """
        return self._in_param_if_snpathref

    @in_param_if_snpathref.setter
    def in_param_if_snpathref(self, in_param_if_snpathref: str):
        """Sets the in_param_if_snpathref of this ReadParamValue.


        :param in_param_if_snpathref: The in_param_if_snpathref of this ReadParamValue.
        :type in_param_if_snpathref: str
        """

        self._in_param_if_snpathref = in_param_if_snpathref

    @property
    def semantic(self) -> str:
        """Gets the semantic of this ReadParamValue.


        :return: The semantic of this ReadParamValue.
        :rtype: str
        """
        return self._semantic

    @semantic.setter
    def semantic(self, semantic: str):
        """Sets the semantic of this ReadParamValue.


        :param semantic: The semantic of this ReadParamValue.
        :type semantic: str
        """

        self._semantic = semantic

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this ReadParamValue.


        :return: The perma_id of this ReadParamValue.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this ReadParamValue.


        :param perma_id: The perma_id of this ReadParamValue.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this ReadParamValue.


        :return: The ephemeral_id of this ReadParamValue.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this ReadParamValue.


        :param ephemeral_id: The ephemeral_id of this ReadParamValue.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this ReadParamValue.


        :return: The class_name of this ReadParamValue.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this ReadParamValue.


        :param class_name: The class_name of this ReadParamValue.
        :type class_name: str
        """

        self._class_name = class_name
