# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server import util


class RowFragment(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    KEY = 'KEY'
    STRUCT = 'STRUCT'
    def __init__(self):  # noqa: E501
        """RowFragment - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'RowFragment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RowFragment of this RowFragment.  # noqa: E501
        :rtype: RowFragment
        """
        return util.deserialize_model(dikt, cls)
