# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server import util


class StandardizationLevel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    STANDARD = 'STANDARD'
    OEM_MINUS_SPECIFIC = 'OEM-SPECIFIC'
    OPTIONAL = 'OPTIONAL'
    OEM_MINUS_OPTIONAL = 'OEM-OPTIONAL'
    def __init__(self):  # noqa: E501
        """StandardizationLevel - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'StandardizationLevel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StandardizationLevel of this StandardizationLevel.  # noqa: E501
        :rtype: StandardizationLevel
        """
        return util.deserialize_model(dikt, cls)
