# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.state import State
from diag_server.openapi_server.models.state_transition import StateTransition
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.state import State  # noqa: E501
from diag_server.openapi_server.models.state_transition import StateTransition  # noqa: E501

class StateChartResolved(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, semantic=None, state_transitions=None, start_state_snref=None, start_state=None, states=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """StateChartResolved - a model defined in OpenAPI

        :param short_name: The short_name of this StateChartResolved.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this StateChartResolved.  # noqa: E501
        :type long_name: str
        :param description: The description of this StateChartResolved.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this StateChartResolved.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this StateChartResolved.  # noqa: E501
        :type oid: str
        :param semantic: The semantic of this StateChartResolved.  # noqa: E501
        :type semantic: str
        :param state_transitions: The state_transitions of this StateChartResolved.  # noqa: E501
        :type state_transitions: List[StateTransition]
        :param start_state_snref: The start_state_snref of this StateChartResolved.  # noqa: E501
        :type start_state_snref: str
        :param start_state: The start_state of this StateChartResolved.  # noqa: E501
        :type start_state: State
        :param states: The states of this StateChartResolved.  # noqa: E501
        :type states: List[State]
        :param perma_id: The perma_id of this StateChartResolved.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this StateChartResolved.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this StateChartResolved.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'semantic': str,
            'state_transitions': List[StateTransition],
            'start_state_snref': str,
            'start_state': State,
            'states': List[State],
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'semantic': 'semantic',
            'state_transitions': 'state_transitions',
            'start_state_snref': 'start_state_snref',
            'start_state': 'start_state',
            'states': 'states',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._semantic = semantic
        self._state_transitions = state_transitions
        self._start_state_snref = start_state_snref
        self._start_state = start_state
        self._states = states
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'StateChartResolved':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StateChartResolved of this StateChartResolved.  # noqa: E501
        :rtype: StateChartResolved
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this StateChartResolved.


        :return: The short_name of this StateChartResolved.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this StateChartResolved.


        :param short_name: The short_name of this StateChartResolved.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this StateChartResolved.


        :return: The long_name of this StateChartResolved.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this StateChartResolved.


        :param long_name: The long_name of this StateChartResolved.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this StateChartResolved.


        :return: The description of this StateChartResolved.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this StateChartResolved.


        :param description: The description of this StateChartResolved.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this StateChartResolved.


        :return: The odx_id of this StateChartResolved.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this StateChartResolved.


        :param odx_id: The odx_id of this StateChartResolved.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this StateChartResolved.


        :return: The oid of this StateChartResolved.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this StateChartResolved.


        :param oid: The oid of this StateChartResolved.
        :type oid: str
        """

        self._oid = oid

    @property
    def semantic(self) -> str:
        """Gets the semantic of this StateChartResolved.


        :return: The semantic of this StateChartResolved.
        :rtype: str
        """
        return self._semantic

    @semantic.setter
    def semantic(self, semantic: str):
        """Sets the semantic of this StateChartResolved.


        :param semantic: The semantic of this StateChartResolved.
        :type semantic: str
        """

        self._semantic = semantic

    @property
    def state_transitions(self) -> List[StateTransition]:
        """Gets the state_transitions of this StateChartResolved.


        :return: The state_transitions of this StateChartResolved.
        :rtype: List[StateTransition]
        """
        return self._state_transitions

    @state_transitions.setter
    def state_transitions(self, state_transitions: List[StateTransition]):
        """Sets the state_transitions of this StateChartResolved.


        :param state_transitions: The state_transitions of this StateChartResolved.
        :type state_transitions: List[StateTransition]
        """

        self._state_transitions = state_transitions

    @property
    def start_state_snref(self) -> str:
        """Gets the start_state_snref of this StateChartResolved.


        :return: The start_state_snref of this StateChartResolved.
        :rtype: str
        """
        return self._start_state_snref

    @start_state_snref.setter
    def start_state_snref(self, start_state_snref: str):
        """Sets the start_state_snref of this StateChartResolved.


        :param start_state_snref: The start_state_snref of this StateChartResolved.
        :type start_state_snref: str
        """

        self._start_state_snref = start_state_snref

    @property
    def start_state(self) -> State:
        """Gets the start_state of this StateChartResolved.


        :return: The start_state of this StateChartResolved.
        :rtype: State
        """
        return self._start_state

    @start_state.setter
    def start_state(self, start_state: State):
        """Sets the start_state of this StateChartResolved.


        :param start_state: The start_state of this StateChartResolved.
        :type start_state: State
        """

        self._start_state = start_state

    @property
    def states(self) -> List[State]:
        """Gets the states of this StateChartResolved.


        :return: The states of this StateChartResolved.
        :rtype: List[State]
        """
        return self._states

    @states.setter
    def states(self, states: List[State]):
        """Sets the states of this StateChartResolved.


        :param states: The states of this StateChartResolved.
        :type states: List[State]
        """

        self._states = states

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this StateChartResolved.


        :return: The perma_id of this StateChartResolved.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this StateChartResolved.


        :param perma_id: The perma_id of this StateChartResolved.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this StateChartResolved.


        :return: The ephemeral_id of this StateChartResolved.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this StateChartResolved.


        :param ephemeral_id: The ephemeral_id of this StateChartResolved.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this StateChartResolved.


        :return: The class_name of this StateChartResolved.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this StateChartResolved.


        :param class_name: The class_name of this StateChartResolved.
        :type class_name: str
        """

        self._class_name = class_name
