# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server import util


class StateMachine(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, succeeded=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """StateMachine - a model defined in OpenAPI

        :param succeeded: The succeeded of this StateMachine.  # noqa: E501
        :type succeeded: bool
        :param perma_id: The perma_id of this StateMachine.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this StateMachine.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this StateMachine.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'succeeded': bool,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'succeeded': 'succeeded',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._succeeded = succeeded
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'StateMachine':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StateMachine of this StateMachine.  # noqa: E501
        :rtype: StateMachine
        """
        return util.deserialize_model(dikt, cls)

    @property
    def succeeded(self) -> bool:
        """Gets the succeeded of this StateMachine.


        :return: The succeeded of this StateMachine.
        :rtype: bool
        """
        return self._succeeded

    @succeeded.setter
    def succeeded(self, succeeded: bool):
        """Sets the succeeded of this StateMachine.


        :param succeeded: The succeeded of this StateMachine.
        :type succeeded: bool
        """

        self._succeeded = succeeded

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this StateMachine.


        :return: The perma_id of this StateMachine.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this StateMachine.


        :param perma_id: The perma_id of this StateMachine.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this StateMachine.


        :return: The ephemeral_id of this StateMachine.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this StateMachine.


        :param ephemeral_id: The ephemeral_id of this StateMachine.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this StateMachine.


        :return: The class_name of this StateMachine.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this StateMachine.


        :param class_name: The class_name of this StateMachine.
        :type class_name: str
        """

        self._class_name = class_name
