# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501

class SwVariable(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, origin=None, oid=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """SwVariable - a model defined in OpenAPI

        :param short_name: The short_name of this SwVariable.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this SwVariable.  # noqa: E501
        :type long_name: str
        :param description: The description of this SwVariable.  # noqa: E501
        :type description: Description
        :param origin: The origin of this SwVariable.  # noqa: E501
        :type origin: str
        :param oid: The oid of this SwVariable.  # noqa: E501
        :type oid: str
        :param perma_id: The perma_id of this SwVariable.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this SwVariable.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this SwVariable.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'origin': str,
            'oid': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'origin': 'origin',
            'oid': 'oid',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._origin = origin
        self._oid = oid
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'SwVariable':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SwVariable of this SwVariable.  # noqa: E501
        :rtype: SwVariable
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this SwVariable.


        :return: The short_name of this SwVariable.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this SwVariable.


        :param short_name: The short_name of this SwVariable.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this SwVariable.


        :return: The long_name of this SwVariable.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this SwVariable.


        :param long_name: The long_name of this SwVariable.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this SwVariable.


        :return: The description of this SwVariable.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this SwVariable.


        :param description: The description of this SwVariable.
        :type description: Description
        """

        self._description = description

    @property
    def origin(self) -> str:
        """Gets the origin of this SwVariable.


        :return: The origin of this SwVariable.
        :rtype: str
        """
        return self._origin

    @origin.setter
    def origin(self, origin: str):
        """Sets the origin of this SwVariable.


        :param origin: The origin of this SwVariable.
        :type origin: str
        """

        self._origin = origin

    @property
    def oid(self) -> str:
        """Gets the oid of this SwVariable.


        :return: The oid of this SwVariable.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this SwVariable.


        :param oid: The oid of this SwVariable.
        :type oid: str
        """

        self._oid = oid

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this SwVariable.


        :return: The perma_id of this SwVariable.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this SwVariable.


        :param perma_id: The perma_id of this SwVariable.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this SwVariable.


        :return: The ephemeral_id of this SwVariable.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this SwVariable.


        :param ephemeral_id: The ephemeral_id of this SwVariable.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this SwVariable.


        :return: The class_name of this SwVariable.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this SwVariable.


        :param class_name: The class_name of this SwVariable.
        :type class_name: str
        """

        self._class_name = class_name
