# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.diag_comm_resolved import DiagCommResolved
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server import util

from diag_server.openapi_server.models.diag_comm_resolved import DiagCommResolved  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501

class TableDiagCommConnectorResolved(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, semantic=None, diag_comm_ref=None, diag_comm=None, diag_comm_snref=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """TableDiagCommConnectorResolved - a model defined in OpenAPI

        :param semantic: The semantic of this TableDiagCommConnectorResolved.  # noqa: E501
        :type semantic: str
        :param diag_comm_ref: The diag_comm_ref of this TableDiagCommConnectorResolved.  # noqa: E501
        :type diag_comm_ref: OdxLinkRef
        :param diag_comm: The diag_comm of this TableDiagCommConnectorResolved.  # noqa: E501
        :type diag_comm: DiagCommResolved
        :param diag_comm_snref: The diag_comm_snref of this TableDiagCommConnectorResolved.  # noqa: E501
        :type diag_comm_snref: str
        :param perma_id: The perma_id of this TableDiagCommConnectorResolved.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this TableDiagCommConnectorResolved.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this TableDiagCommConnectorResolved.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'semantic': str,
            'diag_comm_ref': OdxLinkRef,
            'diag_comm': DiagCommResolved,
            'diag_comm_snref': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'semantic': 'semantic',
            'diag_comm_ref': 'diag_comm_ref',
            'diag_comm': 'diag_comm',
            'diag_comm_snref': 'diag_comm_snref',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._semantic = semantic
        self._diag_comm_ref = diag_comm_ref
        self._diag_comm = diag_comm
        self._diag_comm_snref = diag_comm_snref
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'TableDiagCommConnectorResolved':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TableDiagCommConnectorResolved of this TableDiagCommConnectorResolved.  # noqa: E501
        :rtype: TableDiagCommConnectorResolved
        """
        return util.deserialize_model(dikt, cls)

    @property
    def semantic(self) -> str:
        """Gets the semantic of this TableDiagCommConnectorResolved.


        :return: The semantic of this TableDiagCommConnectorResolved.
        :rtype: str
        """
        return self._semantic

    @semantic.setter
    def semantic(self, semantic: str):
        """Sets the semantic of this TableDiagCommConnectorResolved.


        :param semantic: The semantic of this TableDiagCommConnectorResolved.
        :type semantic: str
        """

        self._semantic = semantic

    @property
    def diag_comm_ref(self) -> OdxLinkRef:
        """Gets the diag_comm_ref of this TableDiagCommConnectorResolved.


        :return: The diag_comm_ref of this TableDiagCommConnectorResolved.
        :rtype: OdxLinkRef
        """
        return self._diag_comm_ref

    @diag_comm_ref.setter
    def diag_comm_ref(self, diag_comm_ref: OdxLinkRef):
        """Sets the diag_comm_ref of this TableDiagCommConnectorResolved.


        :param diag_comm_ref: The diag_comm_ref of this TableDiagCommConnectorResolved.
        :type diag_comm_ref: OdxLinkRef
        """

        self._diag_comm_ref = diag_comm_ref

    @property
    def diag_comm(self) -> DiagCommResolved:
        """Gets the diag_comm of this TableDiagCommConnectorResolved.


        :return: The diag_comm of this TableDiagCommConnectorResolved.
        :rtype: DiagCommResolved
        """
        return self._diag_comm

    @diag_comm.setter
    def diag_comm(self, diag_comm: DiagCommResolved):
        """Sets the diag_comm of this TableDiagCommConnectorResolved.


        :param diag_comm: The diag_comm of this TableDiagCommConnectorResolved.
        :type diag_comm: DiagCommResolved
        """

        self._diag_comm = diag_comm

    @property
    def diag_comm_snref(self) -> str:
        """Gets the diag_comm_snref of this TableDiagCommConnectorResolved.


        :return: The diag_comm_snref of this TableDiagCommConnectorResolved.
        :rtype: str
        """
        return self._diag_comm_snref

    @diag_comm_snref.setter
    def diag_comm_snref(self, diag_comm_snref: str):
        """Sets the diag_comm_snref of this TableDiagCommConnectorResolved.


        :param diag_comm_snref: The diag_comm_snref of this TableDiagCommConnectorResolved.
        :type diag_comm_snref: str
        """

        self._diag_comm_snref = diag_comm_snref

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this TableDiagCommConnectorResolved.


        :return: The perma_id of this TableDiagCommConnectorResolved.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this TableDiagCommConnectorResolved.


        :param perma_id: The perma_id of this TableDiagCommConnectorResolved.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this TableDiagCommConnectorResolved.


        :return: The ephemeral_id of this TableDiagCommConnectorResolved.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this TableDiagCommConnectorResolved.


        :param ephemeral_id: The ephemeral_id of this TableDiagCommConnectorResolved.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this TableDiagCommConnectorResolved.


        :return: The class_name of this TableDiagCommConnectorResolved.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this TableDiagCommConnectorResolved.


        :param class_name: The class_name of this TableDiagCommConnectorResolved.
        :type class_name: str
        """

        self._class_name = class_name
