# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.admin_data import AdminData
from diag_server.openapi_server.models.audience import Audience
from diag_server.openapi_server.models.data_object_property import DataObjectProperty
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.functional_class import FunctionalClass
from diag_server.openapi_server.models.limit_value import LimitValue
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server.models.pre_condition_state_ref import PreConditionStateRef
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server.models.state_transition_ref import StateTransitionRef
from diag_server.openapi_server.models.structure import Structure
from diag_server.openapi_server.models.table_resolved import TableResolved
from diag_server.openapi_server import util

from diag_server.openapi_server.models.admin_data import AdminData  # noqa: E501
from diag_server.openapi_server.models.audience import Audience  # noqa: E501
from diag_server.openapi_server.models.data_object_property import DataObjectProperty  # noqa: E501
from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.functional_class import FunctionalClass  # noqa: E501
from diag_server.openapi_server.models.limit_value import LimitValue  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501
from diag_server.openapi_server.models.pre_condition_state_ref import PreConditionStateRef  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501
from diag_server.openapi_server.models.state_transition_ref import StateTransitionRef  # noqa: E501
from diag_server.openapi_server.models.structure import Structure  # noqa: E501
from diag_server.openapi_server.models.table_resolved import TableResolved  # noqa: E501

class TableRowResolved(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, table_ref=None, table=None, key_raw=None, key=None, dop_ref=None, dop=None, dop_snref=None, structure_ref=None, structure=None, structure_snref=None, sdgs=None, audience=None, functional_class_refs=None, functional_classes=None, state_transition_refs=None, pre_condition_state_refs=None, admin_data=None, is_executable_raw=None, is_executable=None, semantic=None, is_mandatory_raw=None, is_mandatory=None, is_final_raw=None, is_final=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """TableRowResolved - a model defined in OpenAPI

        :param short_name: The short_name of this TableRowResolved.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this TableRowResolved.  # noqa: E501
        :type long_name: str
        :param description: The description of this TableRowResolved.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this TableRowResolved.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this TableRowResolved.  # noqa: E501
        :type oid: str
        :param table_ref: The table_ref of this TableRowResolved.  # noqa: E501
        :type table_ref: OdxLinkRef
        :param table: The table of this TableRowResolved.  # noqa: E501
        :type table: TableResolved
        :param key_raw: The key_raw of this TableRowResolved.  # noqa: E501
        :type key_raw: str
        :param key: The key of this TableRowResolved.  # noqa: E501
        :type key: LimitValue
        :param dop_ref: The dop_ref of this TableRowResolved.  # noqa: E501
        :type dop_ref: OdxLinkRef
        :param dop: The dop of this TableRowResolved.  # noqa: E501
        :type dop: DataObjectProperty
        :param dop_snref: The dop_snref of this TableRowResolved.  # noqa: E501
        :type dop_snref: str
        :param structure_ref: The structure_ref of this TableRowResolved.  # noqa: E501
        :type structure_ref: OdxLinkRef
        :param structure: The structure of this TableRowResolved.  # noqa: E501
        :type structure: Structure
        :param structure_snref: The structure_snref of this TableRowResolved.  # noqa: E501
        :type structure_snref: str
        :param sdgs: The sdgs of this TableRowResolved.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param audience: The audience of this TableRowResolved.  # noqa: E501
        :type audience: Audience
        :param functional_class_refs: The functional_class_refs of this TableRowResolved.  # noqa: E501
        :type functional_class_refs: List[OdxLinkRef]
        :param functional_classes: The functional_classes of this TableRowResolved.  # noqa: E501
        :type functional_classes: List[FunctionalClass]
        :param state_transition_refs: The state_transition_refs of this TableRowResolved.  # noqa: E501
        :type state_transition_refs: List[StateTransitionRef]
        :param pre_condition_state_refs: The pre_condition_state_refs of this TableRowResolved.  # noqa: E501
        :type pre_condition_state_refs: List[PreConditionStateRef]
        :param admin_data: The admin_data of this TableRowResolved.  # noqa: E501
        :type admin_data: AdminData
        :param is_executable_raw: The is_executable_raw of this TableRowResolved.  # noqa: E501
        :type is_executable_raw: bool
        :param is_executable: The is_executable of this TableRowResolved.  # noqa: E501
        :type is_executable: bool
        :param semantic: The semantic of this TableRowResolved.  # noqa: E501
        :type semantic: str
        :param is_mandatory_raw: The is_mandatory_raw of this TableRowResolved.  # noqa: E501
        :type is_mandatory_raw: bool
        :param is_mandatory: The is_mandatory of this TableRowResolved.  # noqa: E501
        :type is_mandatory: bool
        :param is_final_raw: The is_final_raw of this TableRowResolved.  # noqa: E501
        :type is_final_raw: bool
        :param is_final: The is_final of this TableRowResolved.  # noqa: E501
        :type is_final: bool
        :param perma_id: The perma_id of this TableRowResolved.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this TableRowResolved.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this TableRowResolved.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'table_ref': OdxLinkRef,
            'table': TableResolved,
            'key_raw': str,
            'key': LimitValue,
            'dop_ref': OdxLinkRef,
            'dop': DataObjectProperty,
            'dop_snref': str,
            'structure_ref': OdxLinkRef,
            'structure': Structure,
            'structure_snref': str,
            'sdgs': List[SpecialDataGroup],
            'audience': Audience,
            'functional_class_refs': List[OdxLinkRef],
            'functional_classes': List[FunctionalClass],
            'state_transition_refs': List[StateTransitionRef],
            'pre_condition_state_refs': List[PreConditionStateRef],
            'admin_data': AdminData,
            'is_executable_raw': bool,
            'is_executable': bool,
            'semantic': str,
            'is_mandatory_raw': bool,
            'is_mandatory': bool,
            'is_final_raw': bool,
            'is_final': bool,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'table_ref': 'table_ref',
            'table': 'table',
            'key_raw': 'key_raw',
            'key': 'key',
            'dop_ref': 'dop_ref',
            'dop': 'dop',
            'dop_snref': 'dop_snref',
            'structure_ref': 'structure_ref',
            'structure': 'structure',
            'structure_snref': 'structure_snref',
            'sdgs': 'sdgs',
            'audience': 'audience',
            'functional_class_refs': 'functional_class_refs',
            'functional_classes': 'functional_classes',
            'state_transition_refs': 'state_transition_refs',
            'pre_condition_state_refs': 'pre_condition_state_refs',
            'admin_data': 'admin_data',
            'is_executable_raw': 'is_executable_raw',
            'is_executable': 'is_executable',
            'semantic': 'semantic',
            'is_mandatory_raw': 'is_mandatory_raw',
            'is_mandatory': 'is_mandatory',
            'is_final_raw': 'is_final_raw',
            'is_final': 'is_final',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._table_ref = table_ref
        self._table = table
        self._key_raw = key_raw
        self._key = key
        self._dop_ref = dop_ref
        self._dop = dop
        self._dop_snref = dop_snref
        self._structure_ref = structure_ref
        self._structure = structure
        self._structure_snref = structure_snref
        self._sdgs = sdgs
        self._audience = audience
        self._functional_class_refs = functional_class_refs
        self._functional_classes = functional_classes
        self._state_transition_refs = state_transition_refs
        self._pre_condition_state_refs = pre_condition_state_refs
        self._admin_data = admin_data
        self._is_executable_raw = is_executable_raw
        self._is_executable = is_executable
        self._semantic = semantic
        self._is_mandatory_raw = is_mandatory_raw
        self._is_mandatory = is_mandatory
        self._is_final_raw = is_final_raw
        self._is_final = is_final
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'TableRowResolved':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TableRowResolved of this TableRowResolved.  # noqa: E501
        :rtype: TableRowResolved
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this TableRowResolved.


        :return: The short_name of this TableRowResolved.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this TableRowResolved.


        :param short_name: The short_name of this TableRowResolved.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this TableRowResolved.


        :return: The long_name of this TableRowResolved.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this TableRowResolved.


        :param long_name: The long_name of this TableRowResolved.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this TableRowResolved.


        :return: The description of this TableRowResolved.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this TableRowResolved.


        :param description: The description of this TableRowResolved.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this TableRowResolved.


        :return: The odx_id of this TableRowResolved.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this TableRowResolved.


        :param odx_id: The odx_id of this TableRowResolved.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this TableRowResolved.


        :return: The oid of this TableRowResolved.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this TableRowResolved.


        :param oid: The oid of this TableRowResolved.
        :type oid: str
        """

        self._oid = oid

    @property
    def table_ref(self) -> OdxLinkRef:
        """Gets the table_ref of this TableRowResolved.


        :return: The table_ref of this TableRowResolved.
        :rtype: OdxLinkRef
        """
        return self._table_ref

    @table_ref.setter
    def table_ref(self, table_ref: OdxLinkRef):
        """Sets the table_ref of this TableRowResolved.


        :param table_ref: The table_ref of this TableRowResolved.
        :type table_ref: OdxLinkRef
        """

        self._table_ref = table_ref

    @property
    def table(self) -> TableResolved:
        """Gets the table of this TableRowResolved.


        :return: The table of this TableRowResolved.
        :rtype: TableResolved
        """
        return self._table

    @table.setter
    def table(self, table: TableResolved):
        """Sets the table of this TableRowResolved.


        :param table: The table of this TableRowResolved.
        :type table: TableResolved
        """

        self._table = table

    @property
    def key_raw(self) -> str:
        """Gets the key_raw of this TableRowResolved.


        :return: The key_raw of this TableRowResolved.
        :rtype: str
        """
        return self._key_raw

    @key_raw.setter
    def key_raw(self, key_raw: str):
        """Sets the key_raw of this TableRowResolved.


        :param key_raw: The key_raw of this TableRowResolved.
        :type key_raw: str
        """

        self._key_raw = key_raw

    @property
    def key(self) -> LimitValue:
        """Gets the key of this TableRowResolved.


        :return: The key of this TableRowResolved.
        :rtype: LimitValue
        """
        return self._key

    @key.setter
    def key(self, key: LimitValue):
        """Sets the key of this TableRowResolved.


        :param key: The key of this TableRowResolved.
        :type key: LimitValue
        """

        self._key = key

    @property
    def dop_ref(self) -> OdxLinkRef:
        """Gets the dop_ref of this TableRowResolved.


        :return: The dop_ref of this TableRowResolved.
        :rtype: OdxLinkRef
        """
        return self._dop_ref

    @dop_ref.setter
    def dop_ref(self, dop_ref: OdxLinkRef):
        """Sets the dop_ref of this TableRowResolved.


        :param dop_ref: The dop_ref of this TableRowResolved.
        :type dop_ref: OdxLinkRef
        """

        self._dop_ref = dop_ref

    @property
    def dop(self) -> DataObjectProperty:
        """Gets the dop of this TableRowResolved.


        :return: The dop of this TableRowResolved.
        :rtype: DataObjectProperty
        """
        return self._dop

    @dop.setter
    def dop(self, dop: DataObjectProperty):
        """Sets the dop of this TableRowResolved.


        :param dop: The dop of this TableRowResolved.
        :type dop: DataObjectProperty
        """

        self._dop = dop

    @property
    def dop_snref(self) -> str:
        """Gets the dop_snref of this TableRowResolved.


        :return: The dop_snref of this TableRowResolved.
        :rtype: str
        """
        return self._dop_snref

    @dop_snref.setter
    def dop_snref(self, dop_snref: str):
        """Sets the dop_snref of this TableRowResolved.


        :param dop_snref: The dop_snref of this TableRowResolved.
        :type dop_snref: str
        """

        self._dop_snref = dop_snref

    @property
    def structure_ref(self) -> OdxLinkRef:
        """Gets the structure_ref of this TableRowResolved.


        :return: The structure_ref of this TableRowResolved.
        :rtype: OdxLinkRef
        """
        return self._structure_ref

    @structure_ref.setter
    def structure_ref(self, structure_ref: OdxLinkRef):
        """Sets the structure_ref of this TableRowResolved.


        :param structure_ref: The structure_ref of this TableRowResolved.
        :type structure_ref: OdxLinkRef
        """

        self._structure_ref = structure_ref

    @property
    def structure(self) -> Structure:
        """Gets the structure of this TableRowResolved.


        :return: The structure of this TableRowResolved.
        :rtype: Structure
        """
        return self._structure

    @structure.setter
    def structure(self, structure: Structure):
        """Sets the structure of this TableRowResolved.


        :param structure: The structure of this TableRowResolved.
        :type structure: Structure
        """

        self._structure = structure

    @property
    def structure_snref(self) -> str:
        """Gets the structure_snref of this TableRowResolved.


        :return: The structure_snref of this TableRowResolved.
        :rtype: str
        """
        return self._structure_snref

    @structure_snref.setter
    def structure_snref(self, structure_snref: str):
        """Sets the structure_snref of this TableRowResolved.


        :param structure_snref: The structure_snref of this TableRowResolved.
        :type structure_snref: str
        """

        self._structure_snref = structure_snref

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this TableRowResolved.


        :return: The sdgs of this TableRowResolved.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this TableRowResolved.


        :param sdgs: The sdgs of this TableRowResolved.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def audience(self) -> Audience:
        """Gets the audience of this TableRowResolved.


        :return: The audience of this TableRowResolved.
        :rtype: Audience
        """
        return self._audience

    @audience.setter
    def audience(self, audience: Audience):
        """Sets the audience of this TableRowResolved.


        :param audience: The audience of this TableRowResolved.
        :type audience: Audience
        """

        self._audience = audience

    @property
    def functional_class_refs(self) -> List[OdxLinkRef]:
        """Gets the functional_class_refs of this TableRowResolved.


        :return: The functional_class_refs of this TableRowResolved.
        :rtype: List[OdxLinkRef]
        """
        return self._functional_class_refs

    @functional_class_refs.setter
    def functional_class_refs(self, functional_class_refs: List[OdxLinkRef]):
        """Sets the functional_class_refs of this TableRowResolved.


        :param functional_class_refs: The functional_class_refs of this TableRowResolved.
        :type functional_class_refs: List[OdxLinkRef]
        """

        self._functional_class_refs = functional_class_refs

    @property
    def functional_classes(self) -> List[FunctionalClass]:
        """Gets the functional_classes of this TableRowResolved.


        :return: The functional_classes of this TableRowResolved.
        :rtype: List[FunctionalClass]
        """
        return self._functional_classes

    @functional_classes.setter
    def functional_classes(self, functional_classes: List[FunctionalClass]):
        """Sets the functional_classes of this TableRowResolved.


        :param functional_classes: The functional_classes of this TableRowResolved.
        :type functional_classes: List[FunctionalClass]
        """

        self._functional_classes = functional_classes

    @property
    def state_transition_refs(self) -> List[StateTransitionRef]:
        """Gets the state_transition_refs of this TableRowResolved.


        :return: The state_transition_refs of this TableRowResolved.
        :rtype: List[StateTransitionRef]
        """
        return self._state_transition_refs

    @state_transition_refs.setter
    def state_transition_refs(self, state_transition_refs: List[StateTransitionRef]):
        """Sets the state_transition_refs of this TableRowResolved.


        :param state_transition_refs: The state_transition_refs of this TableRowResolved.
        :type state_transition_refs: List[StateTransitionRef]
        """

        self._state_transition_refs = state_transition_refs

    @property
    def pre_condition_state_refs(self) -> List[PreConditionStateRef]:
        """Gets the pre_condition_state_refs of this TableRowResolved.


        :return: The pre_condition_state_refs of this TableRowResolved.
        :rtype: List[PreConditionStateRef]
        """
        return self._pre_condition_state_refs

    @pre_condition_state_refs.setter
    def pre_condition_state_refs(self, pre_condition_state_refs: List[PreConditionStateRef]):
        """Sets the pre_condition_state_refs of this TableRowResolved.


        :param pre_condition_state_refs: The pre_condition_state_refs of this TableRowResolved.
        :type pre_condition_state_refs: List[PreConditionStateRef]
        """

        self._pre_condition_state_refs = pre_condition_state_refs

    @property
    def admin_data(self) -> AdminData:
        """Gets the admin_data of this TableRowResolved.


        :return: The admin_data of this TableRowResolved.
        :rtype: AdminData
        """
        return self._admin_data

    @admin_data.setter
    def admin_data(self, admin_data: AdminData):
        """Sets the admin_data of this TableRowResolved.


        :param admin_data: The admin_data of this TableRowResolved.
        :type admin_data: AdminData
        """

        self._admin_data = admin_data

    @property
    def is_executable_raw(self) -> bool:
        """Gets the is_executable_raw of this TableRowResolved.


        :return: The is_executable_raw of this TableRowResolved.
        :rtype: bool
        """
        return self._is_executable_raw

    @is_executable_raw.setter
    def is_executable_raw(self, is_executable_raw: bool):
        """Sets the is_executable_raw of this TableRowResolved.


        :param is_executable_raw: The is_executable_raw of this TableRowResolved.
        :type is_executable_raw: bool
        """

        self._is_executable_raw = is_executable_raw

    @property
    def is_executable(self) -> bool:
        """Gets the is_executable of this TableRowResolved.


        :return: The is_executable of this TableRowResolved.
        :rtype: bool
        """
        return self._is_executable

    @is_executable.setter
    def is_executable(self, is_executable: bool):
        """Sets the is_executable of this TableRowResolved.


        :param is_executable: The is_executable of this TableRowResolved.
        :type is_executable: bool
        """

        self._is_executable = is_executable

    @property
    def semantic(self) -> str:
        """Gets the semantic of this TableRowResolved.


        :return: The semantic of this TableRowResolved.
        :rtype: str
        """
        return self._semantic

    @semantic.setter
    def semantic(self, semantic: str):
        """Sets the semantic of this TableRowResolved.


        :param semantic: The semantic of this TableRowResolved.
        :type semantic: str
        """

        self._semantic = semantic

    @property
    def is_mandatory_raw(self) -> bool:
        """Gets the is_mandatory_raw of this TableRowResolved.


        :return: The is_mandatory_raw of this TableRowResolved.
        :rtype: bool
        """
        return self._is_mandatory_raw

    @is_mandatory_raw.setter
    def is_mandatory_raw(self, is_mandatory_raw: bool):
        """Sets the is_mandatory_raw of this TableRowResolved.


        :param is_mandatory_raw: The is_mandatory_raw of this TableRowResolved.
        :type is_mandatory_raw: bool
        """

        self._is_mandatory_raw = is_mandatory_raw

    @property
    def is_mandatory(self) -> bool:
        """Gets the is_mandatory of this TableRowResolved.


        :return: The is_mandatory of this TableRowResolved.
        :rtype: bool
        """
        return self._is_mandatory

    @is_mandatory.setter
    def is_mandatory(self, is_mandatory: bool):
        """Sets the is_mandatory of this TableRowResolved.


        :param is_mandatory: The is_mandatory of this TableRowResolved.
        :type is_mandatory: bool
        """

        self._is_mandatory = is_mandatory

    @property
    def is_final_raw(self) -> bool:
        """Gets the is_final_raw of this TableRowResolved.


        :return: The is_final_raw of this TableRowResolved.
        :rtype: bool
        """
        return self._is_final_raw

    @is_final_raw.setter
    def is_final_raw(self, is_final_raw: bool):
        """Sets the is_final_raw of this TableRowResolved.


        :param is_final_raw: The is_final_raw of this TableRowResolved.
        :type is_final_raw: bool
        """

        self._is_final_raw = is_final_raw

    @property
    def is_final(self) -> bool:
        """Gets the is_final of this TableRowResolved.


        :return: The is_final of this TableRowResolved.
        :rtype: bool
        """
        return self._is_final

    @is_final.setter
    def is_final(self, is_final: bool):
        """Sets the is_final of this TableRowResolved.


        :param is_final: The is_final of this TableRowResolved.
        :type is_final: bool
        """

        self._is_final = is_final

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this TableRowResolved.


        :return: The perma_id of this TableRowResolved.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this TableRowResolved.


        :param perma_id: The perma_id of this TableRowResolved.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this TableRowResolved.


        :return: The ephemeral_id of this TableRowResolved.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this TableRowResolved.


        :param ephemeral_id: The ephemeral_id of this TableRowResolved.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this TableRowResolved.


        :return: The class_name of this TableRowResolved.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this TableRowResolved.


        :param class_name: The class_name of this TableRowResolved.
        :type class_name: str
        """

        self._class_name = class_name
