# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server.models.unit import Unit
from diag_server.openapi_server.models.unit_group_category import UnitGroupCategory
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501
from diag_server.openapi_server.models.unit import Unit  # noqa: E501
from diag_server.openapi_server.models.unit_group_category import UnitGroupCategory  # noqa: E501

class UnitGroupResolved(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, category=None, unit_refs=None, units=None, oid=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """UnitGroupResolved - a model defined in OpenAPI

        :param short_name: The short_name of this UnitGroupResolved.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this UnitGroupResolved.  # noqa: E501
        :type long_name: str
        :param description: The description of this UnitGroupResolved.  # noqa: E501
        :type description: Description
        :param category: The category of this UnitGroupResolved.  # noqa: E501
        :type category: UnitGroupCategory
        :param unit_refs: The unit_refs of this UnitGroupResolved.  # noqa: E501
        :type unit_refs: List[OdxLinkRef]
        :param units: The units of this UnitGroupResolved.  # noqa: E501
        :type units: List[Unit]
        :param oid: The oid of this UnitGroupResolved.  # noqa: E501
        :type oid: str
        :param perma_id: The perma_id of this UnitGroupResolved.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this UnitGroupResolved.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this UnitGroupResolved.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'category': UnitGroupCategory,
            'unit_refs': List[OdxLinkRef],
            'units': List[Unit],
            'oid': str,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'category': 'category',
            'unit_refs': 'unit_refs',
            'units': 'units',
            'oid': 'oid',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._category = category
        self._unit_refs = unit_refs
        self._units = units
        self._oid = oid
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'UnitGroupResolved':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UnitGroupResolved of this UnitGroupResolved.  # noqa: E501
        :rtype: UnitGroupResolved
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this UnitGroupResolved.


        :return: The short_name of this UnitGroupResolved.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this UnitGroupResolved.


        :param short_name: The short_name of this UnitGroupResolved.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this UnitGroupResolved.


        :return: The long_name of this UnitGroupResolved.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this UnitGroupResolved.


        :param long_name: The long_name of this UnitGroupResolved.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this UnitGroupResolved.


        :return: The description of this UnitGroupResolved.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this UnitGroupResolved.


        :param description: The description of this UnitGroupResolved.
        :type description: Description
        """

        self._description = description

    @property
    def category(self) -> UnitGroupCategory:
        """Gets the category of this UnitGroupResolved.


        :return: The category of this UnitGroupResolved.
        :rtype: UnitGroupCategory
        """
        return self._category

    @category.setter
    def category(self, category: UnitGroupCategory):
        """Sets the category of this UnitGroupResolved.


        :param category: The category of this UnitGroupResolved.
        :type category: UnitGroupCategory
        """

        self._category = category

    @property
    def unit_refs(self) -> List[OdxLinkRef]:
        """Gets the unit_refs of this UnitGroupResolved.


        :return: The unit_refs of this UnitGroupResolved.
        :rtype: List[OdxLinkRef]
        """
        return self._unit_refs

    @unit_refs.setter
    def unit_refs(self, unit_refs: List[OdxLinkRef]):
        """Sets the unit_refs of this UnitGroupResolved.


        :param unit_refs: The unit_refs of this UnitGroupResolved.
        :type unit_refs: List[OdxLinkRef]
        """

        self._unit_refs = unit_refs

    @property
    def units(self) -> List[Unit]:
        """Gets the units of this UnitGroupResolved.


        :return: The units of this UnitGroupResolved.
        :rtype: List[Unit]
        """
        return self._units

    @units.setter
    def units(self, units: List[Unit]):
        """Sets the units of this UnitGroupResolved.


        :param units: The units of this UnitGroupResolved.
        :type units: List[Unit]
        """

        self._units = units

    @property
    def oid(self) -> str:
        """Gets the oid of this UnitGroupResolved.


        :return: The oid of this UnitGroupResolved.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this UnitGroupResolved.


        :param oid: The oid of this UnitGroupResolved.
        :type oid: str
        """

        self._oid = oid

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this UnitGroupResolved.


        :return: The perma_id of this UnitGroupResolved.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this UnitGroupResolved.


        :param perma_id: The perma_id of this UnitGroupResolved.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this UnitGroupResolved.


        :return: The ephemeral_id of this UnitGroupResolved.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this UnitGroupResolved.


        :param ephemeral_id: The ephemeral_id of this UnitGroupResolved.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this UnitGroupResolved.


        :return: The class_name of this UnitGroupResolved.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this UnitGroupResolved.


        :param class_name: The class_name of this UnitGroupResolved.
        :type class_name: str
        """

        self._class_name = class_name
