# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server import util


class ValidType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    VALID = 'VALID'
    NOT_MINUS_VALID = 'NOT-VALID'
    NOT_MINUS_DEFINED = 'NOT-DEFINED'
    NOT_MINUS_AVAILABLE = 'NOT-AVAILABLE'
    def __init__(self):  # noqa: E501
        """ValidType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ValidType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValidType of this ValidType.  # noqa: E501
        :rtype: ValidType
        """
        return util.deserialize_model(dikt, cls)
