# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.limit_value import LimitValue
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server import util

from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.limit_value import LimitValue  # noqa: E501
from diag_server.openapi_server.models.odx_link_ref import OdxLinkRef  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501

class ValueParameter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, sdgs=None, semantic=None, oid=None, byte_position=None, bit_position=None, dop_ref=None, dop_snref=None, physical_default_value_raw=None, physical_default_value=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """ValueParameter - a model defined in OpenAPI

        :param short_name: The short_name of this ValueParameter.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this ValueParameter.  # noqa: E501
        :type long_name: str
        :param description: The description of this ValueParameter.  # noqa: E501
        :type description: Description
        :param sdgs: The sdgs of this ValueParameter.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param semantic: The semantic of this ValueParameter.  # noqa: E501
        :type semantic: str
        :param oid: The oid of this ValueParameter.  # noqa: E501
        :type oid: str
        :param byte_position: The byte_position of this ValueParameter.  # noqa: E501
        :type byte_position: int
        :param bit_position: The bit_position of this ValueParameter.  # noqa: E501
        :type bit_position: int
        :param dop_ref: The dop_ref of this ValueParameter.  # noqa: E501
        :type dop_ref: OdxLinkRef
        :param dop_snref: The dop_snref of this ValueParameter.  # noqa: E501
        :type dop_snref: str
        :param physical_default_value_raw: The physical_default_value_raw of this ValueParameter.  # noqa: E501
        :type physical_default_value_raw: str
        :param physical_default_value: The physical_default_value of this ValueParameter.  # noqa: E501
        :type physical_default_value: LimitValue
        :param perma_id: The perma_id of this ValueParameter.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this ValueParameter.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this ValueParameter.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'sdgs': List[SpecialDataGroup],
            'semantic': str,
            'oid': str,
            'byte_position': int,
            'bit_position': int,
            'dop_ref': OdxLinkRef,
            'dop_snref': str,
            'physical_default_value_raw': str,
            'physical_default_value': LimitValue,
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'sdgs': 'sdgs',
            'semantic': 'semantic',
            'oid': 'oid',
            'byte_position': 'byte_position',
            'bit_position': 'bit_position',
            'dop_ref': 'dop_ref',
            'dop_snref': 'dop_snref',
            'physical_default_value_raw': 'physical_default_value_raw',
            'physical_default_value': 'physical_default_value',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._sdgs = sdgs
        self._semantic = semantic
        self._oid = oid
        self._byte_position = byte_position
        self._bit_position = bit_position
        self._dop_ref = dop_ref
        self._dop_snref = dop_snref
        self._physical_default_value_raw = physical_default_value_raw
        self._physical_default_value = physical_default_value
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'ValueParameter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValueParameter of this ValueParameter.  # noqa: E501
        :rtype: ValueParameter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this ValueParameter.


        :return: The short_name of this ValueParameter.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this ValueParameter.


        :param short_name: The short_name of this ValueParameter.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this ValueParameter.


        :return: The long_name of this ValueParameter.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this ValueParameter.


        :param long_name: The long_name of this ValueParameter.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this ValueParameter.


        :return: The description of this ValueParameter.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this ValueParameter.


        :param description: The description of this ValueParameter.
        :type description: Description
        """

        self._description = description

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this ValueParameter.


        :return: The sdgs of this ValueParameter.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this ValueParameter.


        :param sdgs: The sdgs of this ValueParameter.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def semantic(self) -> str:
        """Gets the semantic of this ValueParameter.


        :return: The semantic of this ValueParameter.
        :rtype: str
        """
        return self._semantic

    @semantic.setter
    def semantic(self, semantic: str):
        """Sets the semantic of this ValueParameter.


        :param semantic: The semantic of this ValueParameter.
        :type semantic: str
        """

        self._semantic = semantic

    @property
    def oid(self) -> str:
        """Gets the oid of this ValueParameter.


        :return: The oid of this ValueParameter.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this ValueParameter.


        :param oid: The oid of this ValueParameter.
        :type oid: str
        """

        self._oid = oid

    @property
    def byte_position(self) -> int:
        """Gets the byte_position of this ValueParameter.


        :return: The byte_position of this ValueParameter.
        :rtype: int
        """
        return self._byte_position

    @byte_position.setter
    def byte_position(self, byte_position: int):
        """Sets the byte_position of this ValueParameter.


        :param byte_position: The byte_position of this ValueParameter.
        :type byte_position: int
        """

        self._byte_position = byte_position

    @property
    def bit_position(self) -> int:
        """Gets the bit_position of this ValueParameter.


        :return: The bit_position of this ValueParameter.
        :rtype: int
        """
        return self._bit_position

    @bit_position.setter
    def bit_position(self, bit_position: int):
        """Sets the bit_position of this ValueParameter.


        :param bit_position: The bit_position of this ValueParameter.
        :type bit_position: int
        """

        self._bit_position = bit_position

    @property
    def dop_ref(self) -> OdxLinkRef:
        """Gets the dop_ref of this ValueParameter.


        :return: The dop_ref of this ValueParameter.
        :rtype: OdxLinkRef
        """
        return self._dop_ref

    @dop_ref.setter
    def dop_ref(self, dop_ref: OdxLinkRef):
        """Sets the dop_ref of this ValueParameter.


        :param dop_ref: The dop_ref of this ValueParameter.
        :type dop_ref: OdxLinkRef
        """

        self._dop_ref = dop_ref

    @property
    def dop_snref(self) -> str:
        """Gets the dop_snref of this ValueParameter.


        :return: The dop_snref of this ValueParameter.
        :rtype: str
        """
        return self._dop_snref

    @dop_snref.setter
    def dop_snref(self, dop_snref: str):
        """Sets the dop_snref of this ValueParameter.


        :param dop_snref: The dop_snref of this ValueParameter.
        :type dop_snref: str
        """

        self._dop_snref = dop_snref

    @property
    def physical_default_value_raw(self) -> str:
        """Gets the physical_default_value_raw of this ValueParameter.


        :return: The physical_default_value_raw of this ValueParameter.
        :rtype: str
        """
        return self._physical_default_value_raw

    @physical_default_value_raw.setter
    def physical_default_value_raw(self, physical_default_value_raw: str):
        """Sets the physical_default_value_raw of this ValueParameter.


        :param physical_default_value_raw: The physical_default_value_raw of this ValueParameter.
        :type physical_default_value_raw: str
        """

        self._physical_default_value_raw = physical_default_value_raw

    @property
    def physical_default_value(self) -> LimitValue:
        """Gets the physical_default_value of this ValueParameter.


        :return: The physical_default_value of this ValueParameter.
        :rtype: LimitValue
        """
        return self._physical_default_value

    @physical_default_value.setter
    def physical_default_value(self, physical_default_value: LimitValue):
        """Sets the physical_default_value of this ValueParameter.


        :param physical_default_value: The physical_default_value of this ValueParameter.
        :type physical_default_value: LimitValue
        """

        self._physical_default_value = physical_default_value

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this ValueParameter.


        :return: The perma_id of this ValueParameter.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this ValueParameter.


        :param perma_id: The perma_id of this ValueParameter.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this ValueParameter.


        :return: The ephemeral_id of this ValueParameter.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this ValueParameter.


        :param ephemeral_id: The ephemeral_id of this ValueParameter.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this ValueParameter.


        :return: The class_name of this ValueParameter.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this ValueParameter.


        :param class_name: The class_name of this ValueParameter.
        :type class_name: str
        """

        self._class_name = class_name
