# SPDX-License-Identifier: AGPL-3.0-only
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from diag_server.openapi_server.models.base_model import Model
from diag_server.openapi_server.models.admin_data import AdminData
from diag_server.openapi_server.models.company_data1 import CompanyData1
from diag_server.openapi_server.models.description import Description
from diag_server.openapi_server.models.info_component import InfoComponent
from diag_server.openapi_server.models.odx_link_id import OdxLinkId
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup
from diag_server.openapi_server.models.vehicle_information import VehicleInformation
from diag_server.openapi_server import util

from diag_server.openapi_server.models.admin_data import AdminData  # noqa: E501
from diag_server.openapi_server.models.company_data1 import CompanyData1  # noqa: E501
from diag_server.openapi_server.models.description import Description  # noqa: E501
from diag_server.openapi_server.models.info_component import InfoComponent  # noqa: E501
from diag_server.openapi_server.models.odx_link_id import OdxLinkId  # noqa: E501
from diag_server.openapi_server.models.special_data_group import SpecialDataGroup  # noqa: E501
from diag_server.openapi_server.models.vehicle_information import VehicleInformation  # noqa: E501

class VehicleInfoSpec(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, description=None, odx_id=None, oid=None, admin_data=None, company_datas=None, sdgs=None, info_components=None, vehicle_informations=None, perma_id=None, ephemeral_id=None, class_name=None):  # noqa: E501
        """VehicleInfoSpec - a model defined in OpenAPI

        :param short_name: The short_name of this VehicleInfoSpec.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this VehicleInfoSpec.  # noqa: E501
        :type long_name: str
        :param description: The description of this VehicleInfoSpec.  # noqa: E501
        :type description: Description
        :param odx_id: The odx_id of this VehicleInfoSpec.  # noqa: E501
        :type odx_id: OdxLinkId
        :param oid: The oid of this VehicleInfoSpec.  # noqa: E501
        :type oid: str
        :param admin_data: The admin_data of this VehicleInfoSpec.  # noqa: E501
        :type admin_data: AdminData
        :param company_datas: The company_datas of this VehicleInfoSpec.  # noqa: E501
        :type company_datas: List[CompanyData1]
        :param sdgs: The sdgs of this VehicleInfoSpec.  # noqa: E501
        :type sdgs: List[SpecialDataGroup]
        :param info_components: The info_components of this VehicleInfoSpec.  # noqa: E501
        :type info_components: List[InfoComponent]
        :param vehicle_informations: The vehicle_informations of this VehicleInfoSpec.  # noqa: E501
        :type vehicle_informations: List[VehicleInformation]
        :param perma_id: The perma_id of this VehicleInfoSpec.  # noqa: E501
        :type perma_id: str
        :param ephemeral_id: The ephemeral_id of this VehicleInfoSpec.  # noqa: E501
        :type ephemeral_id: int
        :param class_name: The class_name of this VehicleInfoSpec.  # noqa: E501
        :type class_name: str
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'description': Description,
            'odx_id': OdxLinkId,
            'oid': str,
            'admin_data': AdminData,
            'company_datas': List[CompanyData1],
            'sdgs': List[SpecialDataGroup],
            'info_components': List[InfoComponent],
            'vehicle_informations': List[VehicleInformation],
            'perma_id': str,
            'ephemeral_id': int,
            'class_name': str
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'description': 'description',
            'odx_id': 'odx_id',
            'oid': 'oid',
            'admin_data': 'admin_data',
            'company_datas': 'company_datas',
            'sdgs': 'sdgs',
            'info_components': 'info_components',
            'vehicle_informations': 'vehicle_informations',
            'perma_id': 'perma_id',
            'ephemeral_id': 'ephemeral_id',
            'class_name': 'class_name'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._description = description
        self._odx_id = odx_id
        self._oid = oid
        self._admin_data = admin_data
        self._company_datas = company_datas
        self._sdgs = sdgs
        self._info_components = info_components
        self._vehicle_informations = vehicle_informations
        self._perma_id = perma_id
        self._ephemeral_id = ephemeral_id
        self._class_name = class_name

    @classmethod
    def from_dict(cls, dikt) -> 'VehicleInfoSpec':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VehicleInfoSpec of this VehicleInfoSpec.  # noqa: E501
        :rtype: VehicleInfoSpec
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self) -> str:
        """Gets the short_name of this VehicleInfoSpec.


        :return: The short_name of this VehicleInfoSpec.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this VehicleInfoSpec.


        :param short_name: The short_name of this VehicleInfoSpec.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def long_name(self) -> str:
        """Gets the long_name of this VehicleInfoSpec.


        :return: The long_name of this VehicleInfoSpec.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name: str):
        """Sets the long_name of this VehicleInfoSpec.


        :param long_name: The long_name of this VehicleInfoSpec.
        :type long_name: str
        """

        self._long_name = long_name

    @property
    def description(self) -> Description:
        """Gets the description of this VehicleInfoSpec.


        :return: The description of this VehicleInfoSpec.
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description: Description):
        """Sets the description of this VehicleInfoSpec.


        :param description: The description of this VehicleInfoSpec.
        :type description: Description
        """

        self._description = description

    @property
    def odx_id(self) -> OdxLinkId:
        """Gets the odx_id of this VehicleInfoSpec.


        :return: The odx_id of this VehicleInfoSpec.
        :rtype: OdxLinkId
        """
        return self._odx_id

    @odx_id.setter
    def odx_id(self, odx_id: OdxLinkId):
        """Sets the odx_id of this VehicleInfoSpec.


        :param odx_id: The odx_id of this VehicleInfoSpec.
        :type odx_id: OdxLinkId
        """

        self._odx_id = odx_id

    @property
    def oid(self) -> str:
        """Gets the oid of this VehicleInfoSpec.


        :return: The oid of this VehicleInfoSpec.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this VehicleInfoSpec.


        :param oid: The oid of this VehicleInfoSpec.
        :type oid: str
        """

        self._oid = oid

    @property
    def admin_data(self) -> AdminData:
        """Gets the admin_data of this VehicleInfoSpec.


        :return: The admin_data of this VehicleInfoSpec.
        :rtype: AdminData
        """
        return self._admin_data

    @admin_data.setter
    def admin_data(self, admin_data: AdminData):
        """Sets the admin_data of this VehicleInfoSpec.


        :param admin_data: The admin_data of this VehicleInfoSpec.
        :type admin_data: AdminData
        """

        self._admin_data = admin_data

    @property
    def company_datas(self) -> List[CompanyData1]:
        """Gets the company_datas of this VehicleInfoSpec.


        :return: The company_datas of this VehicleInfoSpec.
        :rtype: List[CompanyData1]
        """
        return self._company_datas

    @company_datas.setter
    def company_datas(self, company_datas: List[CompanyData1]):
        """Sets the company_datas of this VehicleInfoSpec.


        :param company_datas: The company_datas of this VehicleInfoSpec.
        :type company_datas: List[CompanyData1]
        """

        self._company_datas = company_datas

    @property
    def sdgs(self) -> List[SpecialDataGroup]:
        """Gets the sdgs of this VehicleInfoSpec.


        :return: The sdgs of this VehicleInfoSpec.
        :rtype: List[SpecialDataGroup]
        """
        return self._sdgs

    @sdgs.setter
    def sdgs(self, sdgs: List[SpecialDataGroup]):
        """Sets the sdgs of this VehicleInfoSpec.


        :param sdgs: The sdgs of this VehicleInfoSpec.
        :type sdgs: List[SpecialDataGroup]
        """

        self._sdgs = sdgs

    @property
    def info_components(self) -> List[InfoComponent]:
        """Gets the info_components of this VehicleInfoSpec.


        :return: The info_components of this VehicleInfoSpec.
        :rtype: List[InfoComponent]
        """
        return self._info_components

    @info_components.setter
    def info_components(self, info_components: List[InfoComponent]):
        """Sets the info_components of this VehicleInfoSpec.


        :param info_components: The info_components of this VehicleInfoSpec.
        :type info_components: List[InfoComponent]
        """

        self._info_components = info_components

    @property
    def vehicle_informations(self) -> List[VehicleInformation]:
        """Gets the vehicle_informations of this VehicleInfoSpec.


        :return: The vehicle_informations of this VehicleInfoSpec.
        :rtype: List[VehicleInformation]
        """
        return self._vehicle_informations

    @vehicle_informations.setter
    def vehicle_informations(self, vehicle_informations: List[VehicleInformation]):
        """Sets the vehicle_informations of this VehicleInfoSpec.


        :param vehicle_informations: The vehicle_informations of this VehicleInfoSpec.
        :type vehicle_informations: List[VehicleInformation]
        """

        self._vehicle_informations = vehicle_informations

    @property
    def perma_id(self) -> str:
        """Gets the perma_id of this VehicleInfoSpec.


        :return: The perma_id of this VehicleInfoSpec.
        :rtype: str
        """
        return self._perma_id

    @perma_id.setter
    def perma_id(self, perma_id: str):
        """Sets the perma_id of this VehicleInfoSpec.


        :param perma_id: The perma_id of this VehicleInfoSpec.
        :type perma_id: str
        """

        self._perma_id = perma_id

    @property
    def ephemeral_id(self) -> int:
        """Gets the ephemeral_id of this VehicleInfoSpec.


        :return: The ephemeral_id of this VehicleInfoSpec.
        :rtype: int
        """
        return self._ephemeral_id

    @ephemeral_id.setter
    def ephemeral_id(self, ephemeral_id: int):
        """Sets the ephemeral_id of this VehicleInfoSpec.


        :param ephemeral_id: The ephemeral_id of this VehicleInfoSpec.
        :type ephemeral_id: int
        """

        self._ephemeral_id = ephemeral_id

    @property
    def class_name(self) -> str:
        """Gets the class_name of this VehicleInfoSpec.


        :return: The class_name of this VehicleInfoSpec.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this VehicleInfoSpec.


        :param class_name: The class_name of this VehicleInfoSpec.
        :type class_name: str
        """

        self._class_name = class_name
