name: odex.viewer - OpenAPI test pipeline
on:
  push:
    branches: [main]
    paths:
      - 'diag-server.yml'
      - 'odxtools-types.json'
  pull_request:
    branches: [main]
    paths:
      - 'diag-server.yml'
      - 'odxtools-types.json'
  workflow_dispatch:

jobs: 
  linting:
    runs-on:  ${{ matrix.os }}    
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v6

      # Run Spectral
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'diag-server.yml'