name: odex.viewer - backend server test pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs: 
  linting:
    runs-on:  ${{ matrix.os }}    
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        python-version: ["3.12", "3.14"]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}
          cache: "pip"

      - name: Install development and testing dependencies
        working-directory: ./server
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Static type checking (mypy)
        working-directory: ./server
        run: |
          python -m mypy .

      - name: Lint code quality (ruff)
        working-directory: ./server
        run: |
          ruff check .

  testing:
    runs-on:  ${{ matrix.os }}    
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        python-version: ["3.12", "3.14"]
      fail-fast: false
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}
          cache: "pip"

      - name: Install development and testing dependencies
        working-directory: ./server
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Create somersault.pdx
        working-directory: ./server
        run: |
          python -m tests.pdx.somersaultecu

      - name: Run unit tests and report line coverage
        working-directory: ./server
        run: |
          coverage run -m pytest
          coverage report
          coverage html